/*
 * Bambuddy
 *
 * Archive and manage Bambu Lab 3MF files
 *
 * The version of the OpenAPI document: 0.2.4.5
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Xunit;
using Microsoft.Extensions.DependencyInjection;
using Bambuddy.Api.Api;
using Bambuddy.Api.Model;


/* *********************************************************************************
*              Follow these manual steps to construct tests.
*              This file will not be overwritten.
*  *********************************************************************************
* 1. Navigate to ApiTests.Base.cs and ensure any tokens are being created correctly.
*    Take care not to commit credentials to any repository.
*
* 2. Mocking is coordinated by ApiTestsBase#AddApiHttpClients.
*    To mock the client, use the generic AddApiHttpClients.
*    To mock the server, change the client's BaseAddress.
*
* 3. Locate the test you want below
*      - remove the skip property from the Fact attribute
*      - set the value of any variables if necessary
*
* 4. Run the tests and ensure they work.
*
*/


namespace Bambuddy.Api.Test.Api
{
    /// <summary>
    ///  Class for testing MakerworldApi
    /// </summary>
    public sealed class MakerworldApiTests : ApiTestsBase
    {
        private readonly IMakerworldApi _instance;

        public MakerworldApiTests(): base(Array.Empty<string>())
        {
            _instance = _host.Services.GetRequiredService<IMakerworldApi>();
        }

        /// <summary>
        /// Test GetStatusApiV1MakerworldStatusGet
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task GetStatusApiV1MakerworldStatusGetAsyncTest()
        {
            Client.Option<string?> xAPIKey = default!;
            var response = await _instance.GetStatusApiV1MakerworldStatusGetAsync(xAPIKey);
            var model = response.Ok();
            Assert.IsType<MakerWorldStatus>(model);
        }

        /// <summary>
        /// Test ImportInstanceApiV1MakerworldImportPost
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task ImportInstanceApiV1MakerworldImportPostAsyncTest()
        {
            MakerWorldImportRequest makerWorldImportRequest = default!;
            Client.Option<string?> xAPIKey = default!;
            var response = await _instance.ImportInstanceApiV1MakerworldImportPostAsync(makerWorldImportRequest, xAPIKey);
            var model = response.Ok();
            Assert.IsType<MakerWorldImportResponse>(model);
        }

        /// <summary>
        /// Test ProxyThumbnailApiV1MakerworldThumbnailGet
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task ProxyThumbnailApiV1MakerworldThumbnailGetAsyncTest()
        {
            string url = default!;
            var response = await _instance.ProxyThumbnailApiV1MakerworldThumbnailGetAsync(url);
            var model = response.Ok();
            Assert.IsType<Object>(model);
        }

        /// <summary>
        /// Test RecentImportsApiV1MakerworldRecentImportsGet
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task RecentImportsApiV1MakerworldRecentImportsGetAsyncTest()
        {
            Client.Option<int> limit = default!;
            Client.Option<string?> xAPIKey = default!;
            var response = await _instance.RecentImportsApiV1MakerworldRecentImportsGetAsync(limit, xAPIKey);
            var model = response.Ok();
            Assert.IsType<List<MakerWorldRecentImport>>(model);
        }

        /// <summary>
        /// Test ResolveUrlApiV1MakerworldResolvePost
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task ResolveUrlApiV1MakerworldResolvePostAsyncTest()
        {
            MakerWorldResolveRequest makerWorldResolveRequest = default!;
            Client.Option<string?> xAPIKey = default!;
            var response = await _instance.ResolveUrlApiV1MakerworldResolvePostAsync(makerWorldResolveRequest, xAPIKey);
            var model = response.Ok();
            Assert.IsType<MakerWorldResolvedModel>(model);
        }
    }
}
