/*
 * Bambuddy
 *
 * Archive and manage Bambu Lab 3MF files
 *
 * The version of the OpenAPI document: 0.2.4.5
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Xunit;
using Microsoft.Extensions.DependencyInjection;
using Bambuddy.Api.Api;
using Bambuddy.Api.Model;


/* *********************************************************************************
*              Follow these manual steps to construct tests.
*              This file will not be overwritten.
*  *********************************************************************************
* 1. Navigate to ApiTests.Base.cs and ensure any tokens are being created correctly.
*    Take care not to commit credentials to any repository.
*
* 2. Mocking is coordinated by ApiTestsBase#AddApiHttpClients.
*    To mock the client, use the generic AddApiHttpClients.
*    To mock the server, change the client's BaseAddress.
*
* 3. Locate the test you want below
*      - remove the skip property from the Fact attribute
*      - set the value of any variables if necessary
*
* 4. Run the tests and ensure they work.
*
*/


namespace Bambuddy.Api.Test.Api
{
    /// <summary>
    ///  Class for testing SmartPlugsApi
    /// </summary>
    public sealed class SmartPlugsApiTests : ApiTestsBase
    {
        private readonly ISmartPlugsApi _instance;

        public SmartPlugsApiTests(): base(Array.Empty<string>())
        {
            _instance = _host.Services.GetRequiredService<ISmartPlugsApi>();
        }

        /// <summary>
        /// Test ControlSmartPlugApiV1SmartPlugsPlugIdControlPost
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task ControlSmartPlugApiV1SmartPlugsPlugIdControlPostAsyncTest()
        {
            int plugId = default!;
            SmartPlugControl smartPlugControl = default!;
            Client.Option<string?> xAPIKey = default!;
            var response = await _instance.ControlSmartPlugApiV1SmartPlugsPlugIdControlPostAsync(plugId, smartPlugControl, xAPIKey);
            var model = response.Ok();
            Assert.IsType<Object>(model);
        }

        /// <summary>
        /// Test CreateSmartPlugApiV1SmartPlugsPost
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task CreateSmartPlugApiV1SmartPlugsPostAsyncTest()
        {
            SmartPlugCreate smartPlugCreate = default!;
            Client.Option<string?> xAPIKey = default!;
            var response = await _instance.CreateSmartPlugApiV1SmartPlugsPostAsync(smartPlugCreate, xAPIKey);
            var model = response.Ok();
            Assert.IsType<SmartPlugResponse>(model);
        }

        /// <summary>
        /// Test DeleteSmartPlugApiV1SmartPlugsPlugIdDelete
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task DeleteSmartPlugApiV1SmartPlugsPlugIdDeleteAsyncTest()
        {
            int plugId = default!;
            Client.Option<string?> xAPIKey = default!;
            var response = await _instance.DeleteSmartPlugApiV1SmartPlugsPlugIdDeleteAsync(plugId, xAPIKey);
            var model = response.Ok();
            Assert.IsType<Object>(model);
        }

        /// <summary>
        /// Test GetDiscoveredTasmotaDevicesApiV1SmartPlugsDiscoverDevicesGet
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task GetDiscoveredTasmotaDevicesApiV1SmartPlugsDiscoverDevicesGetAsyncTest()
        {
            Client.Option<string?> xAPIKey = default!;
            var response = await _instance.GetDiscoveredTasmotaDevicesApiV1SmartPlugsDiscoverDevicesGetAsync(xAPIKey);
            var model = response.Ok();
            Assert.IsType<List<DiscoveredTasmotaDevice>>(model);
        }

        /// <summary>
        /// Test GetPlugStatusApiV1SmartPlugsPlugIdStatusGet
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task GetPlugStatusApiV1SmartPlugsPlugIdStatusGetAsyncTest()
        {
            int plugId = default!;
            Client.Option<string?> xAPIKey = default!;
            var response = await _instance.GetPlugStatusApiV1SmartPlugsPlugIdStatusGetAsync(plugId, xAPIKey);
            var model = response.Ok();
            Assert.IsType<SmartPlugStatus>(model);
        }

        /// <summary>
        /// Test GetScriptPlugsByPrinterApiV1SmartPlugsByPrinterPrinterIdScriptsGet
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task GetScriptPlugsByPrinterApiV1SmartPlugsByPrinterPrinterIdScriptsGetAsyncTest()
        {
            int printerId = default!;
            Client.Option<string?> xAPIKey = default!;
            var response = await _instance.GetScriptPlugsByPrinterApiV1SmartPlugsByPrinterPrinterIdScriptsGetAsync(printerId, xAPIKey);
            var model = response.Ok();
            Assert.IsType<List<SmartPlugResponse>>(model);
        }

        /// <summary>
        /// Test GetSmartPlugApiV1SmartPlugsPlugIdGet
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task GetSmartPlugApiV1SmartPlugsPlugIdGetAsyncTest()
        {
            int plugId = default!;
            Client.Option<string?> xAPIKey = default!;
            var response = await _instance.GetSmartPlugApiV1SmartPlugsPlugIdGetAsync(plugId, xAPIKey);
            var model = response.Ok();
            Assert.IsType<SmartPlugResponse>(model);
        }

        /// <summary>
        /// Test GetSmartPlugByPrinterApiV1SmartPlugsByPrinterPrinterIdGet
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task GetSmartPlugByPrinterApiV1SmartPlugsByPrinterPrinterIdGetAsyncTest()
        {
            int printerId = default!;
            Client.Option<string?> xAPIKey = default!;
            var response = await _instance.GetSmartPlugByPrinterApiV1SmartPlugsByPrinterPrinterIdGetAsync(printerId, xAPIKey);
            var model = response.Ok();
            Assert.IsType<SmartPlugResponse>(model);
        }

        /// <summary>
        /// Test GetTasmotaScanStatusApiV1SmartPlugsDiscoverStatusGet
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task GetTasmotaScanStatusApiV1SmartPlugsDiscoverStatusGetAsyncTest()
        {
            Client.Option<string?> xAPIKey = default!;
            var response = await _instance.GetTasmotaScanStatusApiV1SmartPlugsDiscoverStatusGetAsync(xAPIKey);
            var model = response.Ok();
            Assert.IsType<TasmotaScanStatus>(model);
        }

        /// <summary>
        /// Test ListHaEntitiesApiV1SmartPlugsHaEntitiesGet
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task ListHaEntitiesApiV1SmartPlugsHaEntitiesGetAsyncTest()
        {
            Client.Option<string?> search = default!;
            Client.Option<string?> xAPIKey = default!;
            var response = await _instance.ListHaEntitiesApiV1SmartPlugsHaEntitiesGetAsync(search, xAPIKey);
            var model = response.Ok();
            Assert.IsType<List<HAEntity>>(model);
        }

        /// <summary>
        /// Test ListHaSensorEntitiesApiV1SmartPlugsHaSensorsGet
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task ListHaSensorEntitiesApiV1SmartPlugsHaSensorsGetAsyncTest()
        {
            Client.Option<string?> xAPIKey = default!;
            var response = await _instance.ListHaSensorEntitiesApiV1SmartPlugsHaSensorsGetAsync(xAPIKey);
            var model = response.Ok();
            Assert.IsType<List<HASensorEntity>>(model);
        }

        /// <summary>
        /// Test ListSmartPlugsApiV1SmartPlugsGet
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task ListSmartPlugsApiV1SmartPlugsGetAsyncTest()
        {
            Client.Option<string?> xAPIKey = default!;
            var response = await _instance.ListSmartPlugsApiV1SmartPlugsGetAsync(xAPIKey);
            var model = response.Ok();
            Assert.IsType<List<SmartPlugResponse>>(model);
        }

        /// <summary>
        /// Test StartTasmotaScanApiV1SmartPlugsDiscoverScanPost
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task StartTasmotaScanApiV1SmartPlugsDiscoverScanPostAsyncTest()
        {
            Client.Option<string?> xAPIKey = default!;
            Client.Option<TasmotaScanRequest?> tasmotaScanRequest = default!;
            var response = await _instance.StartTasmotaScanApiV1SmartPlugsDiscoverScanPostAsync(xAPIKey, tasmotaScanRequest);
            var model = response.Ok();
            Assert.IsType<TasmotaScanStatus>(model);
        }

        /// <summary>
        /// Test StopTasmotaScanApiV1SmartPlugsDiscoverStopPost
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task StopTasmotaScanApiV1SmartPlugsDiscoverStopPostAsyncTest()
        {
            Client.Option<string?> xAPIKey = default!;
            var response = await _instance.StopTasmotaScanApiV1SmartPlugsDiscoverStopPostAsync(xAPIKey);
            var model = response.Ok();
            Assert.IsType<TasmotaScanStatus>(model);
        }

        /// <summary>
        /// Test TestConnectionApiV1SmartPlugsTestConnectionPost
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task TestConnectionApiV1SmartPlugsTestConnectionPostAsyncTest()
        {
            SmartPlugTestConnection smartPlugTestConnection = default!;
            Client.Option<string?> xAPIKey = default!;
            var response = await _instance.TestConnectionApiV1SmartPlugsTestConnectionPostAsync(smartPlugTestConnection, xAPIKey);
            var model = response.Ok();
            Assert.IsType<Object>(model);
        }

        /// <summary>
        /// Test TestHaConnectionApiV1SmartPlugsHaTestConnectionPost
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task TestHaConnectionApiV1SmartPlugsHaTestConnectionPostAsyncTest()
        {
            HATestConnectionRequest hATestConnectionRequest = default!;
            Client.Option<string?> xAPIKey = default!;
            var response = await _instance.TestHaConnectionApiV1SmartPlugsHaTestConnectionPostAsync(hATestConnectionRequest, xAPIKey);
            var model = response.Ok();
            Assert.IsType<HATestConnectionResponse>(model);
        }

        /// <summary>
        /// Test TestRestConnectionApiV1SmartPlugsRestTestConnectionPost
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task TestRestConnectionApiV1SmartPlugsRestTestConnectionPostAsyncTest()
        {
            RESTTestConnectionRequest rESTTestConnectionRequest = default!;
            Client.Option<string?> xAPIKey = default!;
            var response = await _instance.TestRestConnectionApiV1SmartPlugsRestTestConnectionPostAsync(rESTTestConnectionRequest, xAPIKey);
            var model = response.Ok();
            Assert.IsType<RESTTestConnectionResponse>(model);
        }

        /// <summary>
        /// Test UpdateSmartPlugApiV1SmartPlugsPlugIdPatch
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task UpdateSmartPlugApiV1SmartPlugsPlugIdPatchAsyncTest()
        {
            int plugId = default!;
            SmartPlugUpdate smartPlugUpdate = default!;
            Client.Option<string?> xAPIKey = default!;
            var response = await _instance.UpdateSmartPlugApiV1SmartPlugsPlugIdPatchAsync(plugId, smartPlugUpdate, xAPIKey);
            var model = response.Ok();
            Assert.IsType<SmartPlugResponse>(model);
        }
    }
}
