// <auto-generated />
// Generated by BambuMan.Export from the Bambu-Lab-RFID-Library README.md — do not edit by hand.
// Source: https://github.com/queengooborg/Bambu-Lab-RFID-Library
// 274 rows, 298 variants, 12 collisions resolved against the tag dumps.

namespace BambuMan.Shared
{
    /// <summary>
    /// Bambu's five-digit filament codes keyed by material variant identifier. Served to the app inside
    /// <see cref="FilamentMatchOverrides.Internal"/>, so a regeneration needs a <c>CurrentVersion</c> bump.
    /// </summary>
    public static class FilamentCodeMap
    {
        public static readonly Dictionary<string, string> ByMaterialVariant = new(StringComparer.OrdinalIgnoreCase)
        {
            #region PLA Basic

            { "A00-A0", "10300" }, // Orange (collision, dumps: Orange 51, Pink 1)
            { "A00-A00", "10300" }, // Orange
            { "A00-A1", "10301" }, // Pumpkin Orange (collision, dumps: Pumpkin Orange 38, Orange 2)
            { "A00-B01", "10602" }, // Blue Gray
            { "A00-B1", "10602" }, // Blue Gray
            { "A00-B3", "10604" }, // Cobalt Blue
            { "A00-B5", "10605" }, // Turquoise
            { "A00-B08", "10603" }, // Cyan
            { "A00-B8", "10603" }, // Cyan
            { "A00-B09", "10601" }, // Blue
            { "A00-B9", "10601" }, // Blue
            { "A00-D0", "10103" }, // Gray
            { "A00-D00", "10103" }, // Gray
            { "A00-D01", "10102" }, // Silver
            { "A00-D1", "10102" }, // Silver
            { "A00-D02", "10104" }, // Light Gray
            { "A00-D2", "10104" }, // Light Gray
            { "A00-D03", "10105" }, // Dark Gray
            { "A00-D3", "10105" }, // Dark Gray
            { "A00-G02", "10502" }, // Mistletoe Green
            { "A00-G2", "10502" }, // Mistletoe Green
            { "A00-G3", "10503" }, // Bright Green
            { "A00-G06", "10501" }, // Bambu Green
            { "A00-G1", "10501" }, // Bambu Green
            { "A00-G6", "10501" }, // Bambu Green
            { "A00-K0", "10101" }, // Black
            { "A00-K00", "10101" }, // Black
            { "A00-N0", "10800" }, // Brown
            { "A00-N1", "10802" }, // Cocoa Brown
            { "A00-P0", "10201" }, // Beige
            { "A00-P00", "10201" }, // Beige
            { "A00-P01", "10203" }, // Pink
            { "A00-P1", "10203" }, // Pink
            { "A00-P2", "10701" }, // Indigo Purple
            { "A00-P05", "10700" }, // Purple
            { "A00-P5", "10700" }, // Purple
            { "A00-P06", "10202" }, // Magenta
            { "A00-P6", "10202" }, // Magenta
            { "A00-R0", "10200" }, // Red
            { "A00-R00", "10200" }, // Red
            { "A00-R2", "10205" }, // Maroon Red
            { "A00-R3", "10204" }, // Hot Pink
            { "A00-W01", "10100" }, // Jade White
            { "A00-W1", "10100" }, // Jade White
            { "A00-Y0", "10400" }, // Yellow
            { "A00-Y00", "10400" }, // Yellow
            { "A00-Y2", "10402" }, // Sunflower Yellow
            { "A00-Y03", "10801" }, // Bronze
            { "A00-Y3", "10801" }, // Bronze
            { "A00-Y04", "10401" }, // Gold
            { "A00-Y4", "10401" }, // Gold
            { "A00-G0", "10500" }, // Green

            #endregion

            #region PLA Lite

            { "A18-K0", "16100" }, // Black
            { "A18-Y0", "16400" }, // Yellow
            { "A18-W0", "16103" }, // White
            { "A18-B0", "16600" }, // Cyan
            { "A18-R0", "16200" }, // Red
            { "A18-D0", "16101" }, // Gray
            { "A18-B1", "16601" }, // Blue
            { "A18-Y1", "16401" }, // Sunflower Yellow
            { "A18-A1", "16301" }, // Orange
            { "A18-P0", "16700" }, // Matte Beige

            #endregion

            #region PLA Matte

            { "A01-A2", "11300" }, // Mandarin Orange (collision, dumps: Mandarin Orange 35, Lemon Yellow 1)
            { "A01-B0", "11603" }, // Sky Blue
            { "A01-B3", "11600" }, // Marine Blue
            { "A01-B4", "11601" }, // Ice Blue
            { "A01-B6", "11602" }, // Dark Blue
            { "A01-D0", "11104" }, // Nardo Gray
            { "A01-D03", "11102" }, // Ash Gray
            { "A01-D3", "11102" }, // Ash Gray
            { "A01-G0", "11502" }, // Apple Green
            { "A01-G1", "11500" }, // Grass Green
            { "A01-G7", "11501" }, // Dark Green
            { "A01-K01", "11101" }, // Charcoal
            { "A01-K1", "11101" }, // Charcoal
            { "A01-N0", "11802" }, // Dark Chocolate
            { "A01-N1", "11800" }, // Latte Brown
            { "A01-N2", "11801" }, // Dark Brown
            { "A01-N3", "11803" }, // Caramel
            { "A01-P03", "11201" }, // Sakura Pink
            { "A01-P3", "11201" }, // Sakura Pink
            { "A01-P4", "11700" }, // Lilac Purple
            { "A01-R1", "11200" }, // Scarlet Red
            { "A01-R2", "11203" }, // Terracotta
            { "A01-R3", "11204" }, // Plum
            { "A01-R4", "11202" }, // Dark Red
            { "A01-W02", "11100" }, // Ivory White
            { "A01-W2", "11100" }, // Ivory White
            { "A01-W3", "11103" }, // Bone White
            { "A01-Y2", "11400" }, // Lemon Yellow
            { "A01-Y3", "11401" }, // Desert Tan

            #endregion

            #region PLA Basic Gradient

            { "A00-M0", "10900" }, // Arctic Whisper
            { "A00-M1", "10901" }, // Solar Breeze (collision, dumps: Solar Breeze 8, Gilded Rose 0)
            { "A00-M2", "10902" }, // Ocean to Meadow
            { "A00-M3", "10903" }, // Pink Citrus
            { "A00-M4", "10904" }, // Mint Lime
            { "A00-M5", "10905" }, // Blueberry Bubblegum
            { "A00-M6", "10906" }, // Dusk Glare
            { "A00-M7", "10907" }, // Cotton Candy Cloud

            #endregion

            #region PLA Glow

            { "A12-A0", "15300" }, // Glow Orange
            { "A12-B0", "15600" }, // Glow Blue
            { "A12-G0", "15500" }, // Glow Green
            { "A12-R0", "15200" }, // Glow Pink
            { "A12-Y0", "15400" }, // Glow Yellow

            #endregion

            #region PLA Marble

            { "A07-D4", "13103" }, // White Marble
            { "A07-R5", "13201" }, // Red Granite

            #endregion

            #region PLA Aero

            { "A11-K0", "14103" }, // Black
            { "A11-W0", "14102" }, // White

            #endregion

            #region PLA Sparkle

            { "A08-B7", "13700" }, // Royal Purple Sparkle
            { "A08-D5", "13102" }, // Slate Gray Sparkle
            { "A08-G3", "13501" }, // Alpine Green Sparkle
            { "A08-K02", "13101" }, // Onyx Black Sparkle
            { "A08-K2", "13101" }, // Onyx Black Sparkle
            { "A08-R2", "13200" }, // Crimson Red Sparkle
            { "A08-Y1", "13402" }, // Classic Gold Sparkle

            #endregion

            #region PLA Metal

            { "A02-D2", "13100" }, // Iron Gray Metallic
            { "A02-Y1", "13400" }, // Iridium Gold Metallic
            { "A02-G2", "13500" }, // Oxide Green Metallic
            { "A02-B2", "13600" }, // Cobalt Blue Metallic
            { "A02-N3", "13800" }, // Copper Brown Metallic

            #endregion

            #region PLA Translucent

            { "A17-R0", "13210" }, // Red
            { "A17-R1", "13211" }, // Cherry Pink
            { "A17-A0", "13301" }, // Orange
            { "A17-Y0", "13410" }, // Mellow Yellow
            { "A17-G0", "13510" }, // Light Jade
            { "A17-B0", "13610" }, // Ice Blue
            { "A17-B1", "13611" }, // Blue
            { "A17-P0", "13710" }, // Purple
            { "A17-P1", "13711" }, // Lavender

            #endregion

            #region PLA Silk+

            { "A06-B0", "13603" }, // Baby Blue
            { "A06-B00", "13603" }, // Baby Blue
            { "A06-B01", "13604" }, // Blue
            { "A06-B1", "13604" }, // Blue
            { "A06-D0", "13108" }, // Titan Gray
            { "A06-D00", "13109" }, // Silver (collision, dumps: Silver 2, Titan Gray 2)
            { "A06-D01", "13109" }, // Silver
            { "A06-D1", "13109" }, // Silver
            { "A06-G0", "13506" }, // Candy Green
            { "A06-G00", "13506" }, // Candy Green
            { "A06-G01", "13507" }, // Mint
            { "A06-G1", "13507" }, // Mint
            { "A06-P0", "13702" }, // Purple
            { "A06-P00", "13702" }, // Purple
            { "A06-R0", "13205" }, // Candy Red
            { "A06-R01", "13206" }, // Rose Gold
            { "A06-R1", "13206" }, // Rose Gold
            { "A06-R2", "13207" }, // Pink
            { "A06-W0", "13110" }, // White
            { "A06-W00", "13110" }, // White
            { "A06-Y0", "13404" }, // Champagne
            { "A06-Y1", "13405" }, // Gold

            #endregion

            #region PLA Silk Multi-Color

            { "A05-T1", "13901" }, // Gilded Rose
            { "A05-T2", "13902" }, // Midnight Blaze
            { "A05-T3", "13903" }, // Neon City (collision, dumps: Neon City 10, Midnight Blaze 2)
            { "A05-T4", "13904" }, // Blue Hawaii
            { "A05-T5", "13905" }, // Velvet Eclipse (Black-Red)
            { "A05-M1", "13906" }, // South Beach
            { "A05-M4", "13909" }, // Aurora Purple (collision, dumps: Aurora Purple 2, Neon City 2)
            { "A05-M8", "13912" }, // Dawn Radiance
            { "A05-T7", "13913" }, // Mystic Magenta
            { "A05-T9", "13916" }, // Phantom Blue

            #endregion

            #region PLA Galaxy

            { "A15-B0", "13602" }, // Purple
            { "A15-G0", "13503" }, // Green
            { "A15-G01", "13504" }, // Nebulae
            { "A15-G1", "13504" }, // Nebulae
            { "A15-R0", "13203" }, // Brown

            #endregion

            #region PLA Wood

            { "A16-G0", "13505" }, // Classic Birch
            { "A16-K0", "13107" }, // Black Walnut
            { "A16-N0", "13801" }, // Clay Brown
            { "A16-R0", "13204" }, // Rosewood (collision, dumps: Rosewood 8, Black Walnut 1)
            { "A16-W0", "13106" }, // White Oak
            { "A16-Y0", "13403" }, // Ochre Yellow

            #endregion

            #region PLA-CF

            { "A50-B6", "14601" }, // Royal Blue
            { "A50-B9", "14600" }, // Jeans Blue
            { "A50-D6", "14101" }, // Lava Gray
            { "A50-K0", "14100" }, // Black
            { "A50-P7", "14700" }, // Iris Purple
            { "A50-R4", "14200" }, // Burgundy Red

            #endregion

            #region PLA Tough+

            { "A10-K0", "12104" }, // Black
            { "A10-D0", "12105" }, // Gray
            { "A10-D1", "12106" }, // Silver
            { "A10-W0", "12107" }, // White
            { "A10-A0", "12301" }, // Orange
            { "A10-Y0", "12401" }, // Yellow
            { "A10-B0", "12601" }, // Cyan

            #endregion

            #region PLA Tough

            { "A09-A0", "12300" }, // Orange
            { "A09-B4", "12600" }, // Light Blue
            { "A09-B5", "12700" }, // Lavender Blue
            { "A09-D1", "12103" }, // Silver
            { "A09-R3", "12200" }, // Vermilion Red
            { "A09-Y0", "12400" }, // Yellow

            #endregion

            #region PLA Pure

            { "A19-W00", "17100" }, // Pure White
            { "A19-K00", "17101" }, // Absolute Black
            { "A19-P00", "17200" }, // Milky Pink
            { "A19-B00", "17600" }, // Baby Blue
            { "A19-A00", "17300" }, // Apricot

            #endregion

            #region PETG Basic

            { "G00-K0", "30105" }, // Black
            { "G00-K00", "30105" }, // Black
            { "G00-W0", "30106" }, // White
            { "G00-W00", "30106" }, // White
            { "G00-D0", "30107" }, // Gray
            { "G00-D00", "30107" }, // Gray
            { "G00-Y0", "30402" }, // Yellow
            { "G00-R0", "30201" }, // Red
            { "G00-B00", "30603" }, // Reflex Blue
            { "G00-N00", "30800" }, // Dark Brown
            { "G00-G00", "30502" }, // Green
            { "G00-A00", "30301" }, // Orange
            { "G00-G01", "30503" }, // Pine Green
            { "G00-B01", "30604" }, // Navy Blue
            { "G00-D01", "30108" }, // Misty Blue
            { "G00-Y01", "30403" }, // Dark Beige
            { "G00-G8", "30404" }, // Lime Green

            #endregion

            #region PETG HF

            { "G02-A0", "33300" }, // Orange (collision, dumps: Orange 28, Translucent Orange 0)
            { "G02-B0", "33600" }, // Blue
            { "G02-B1", "33601" }, // Lake Blue
            { "G02-D0", "33101" }, // Gray
            { "G02-D1", "33103" }, // Dark Gray
            { "G02-G0", "33500" }, // Green
            { "G02-G1", "33501" }, // Lime Green
            { "G02-G2", "33502" }, // Forest Green
            { "G02-K0", "33102" }, // Black (collision, dumps: Black 180, Black 0)
            { "G02-N1", "33801" }, // Peanut Brown
            { "G02-R0", "33200" }, // Red
            { "G02-W0", "33100" }, // White
            { "G02-Y0", "33400" }, // Yellow
            { "G02-Y1", "33401" }, // Cream

            #endregion

            #region PETG Translucent

            { "G01-A0", "32300" }, // Translucent Orange
            { "G01-B0", "32600" }, // Translucent Light Blue
            { "G01-C0", "32101" }, // Clear
            { "G01-D0", "32100" }, // Translucent Gray
            { "G01-G0", "32500" }, // Translucent Olive
            { "G01-G1", "32501" }, // Translucent Teal
            { "G01-N0", "32800" }, // Translucent Brown
            { "G01-P0", "32700" }, // Translucent Purple
            { "G01-P1", "32200" }, // Translucent Pink

            #endregion

            #region PETG-CF

            { "G50-B6", "31600" }, // Indigo Blue
            { "G50-D6", "31101" }, // Titan Gray
            { "G50-G7", "31500" }, // Malachite Green
            { "G50-K0", "31100" }, // Black
            { "G50-P7", "31700" }, // Violet Purple
            { "G50-R4", "31200" }, // Brick Red

            #endregion

            #region ABS

            { "B00-A0", "40300" }, // Orange
            { "B00-B0", "40600" }, // Blue
            { "B00-B4", "40601" }, // Azure
            { "B00-B6", "40602" }, // Navy Blue
            { "B00-D1", "40102" }, // Silver
            { "B00-G6", "40500" }, // Bambu Green
            { "B00-G7", "40502" }, // Olive
            { "B00-K0", "40101" }, // Black
            { "B00-P4", "40701" }, // Lavender
            { "B00-R0", "40200" }, // Red
            { "B00-W0", "40100" }, // White
            { "B00-W00", "40100" }, // White
            { "B00-Y0", "40400" }, // Yellow
            { "B00-Y1", "40402" }, // Tangerine Yellow

            #endregion

            #region ABS-GF

            { "B50-A0", "41300" }, // Orange
            { "B50-K0", "41101" }, // Black
            { "B50-R0", "41200" }, // Red
            { "B50-W0", "41100" }, // White

            #endregion

            #region ASA

            { "B01-B0", "45600" }, // Blue
            { "B01-D0", "45102" }, // Gray
            { "B01-G0", "45500" }, // Green
            { "B01-K0", "45101" }, // Black
            { "B01-R0", "45200" }, // Red
            { "B01-W0", "45100" }, // White

            #endregion

            #region ASA Aero

            { "B02-W0", "46100" }, // White

            #endregion

            #region ASA-CF

            { "B51-K0", "46101" }, // Black

            #endregion

            #region PC

            { "C00-C0", "60102" }, // Clear Black
            { "C00-C1", "60102" }, // Clear Black (collision, dumps: Clear Black 7, Transparent 3)
            { "C00-K0", "60101" }, // Black
            { "C00-W0", "60100" }, // White

            #endregion

            #region PC FR

            { "C01-D0", "63102" }, // Gray
            { "C01-K0", "63100" }, // Black
            { "C01-W0", "63101" }, // White

            #endregion

            #region TPU for AMS

            { "U02-B0", "53600" }, // Blue
            { "U02-D0", "53102" }, // Gray
            { "U02-G0", "53500" }, // Neon Green
            { "U02-K0", "53101" }, // Black
            { "U02-R0", "53200" }, // Red
            { "U02-W0", "53100" }, // White
            { "U02-Y0", "53400" }, // Yellow

            #endregion

            #region PAHT-CF

            { "N04-K0", "70100" }, // Black

            #endregion

            #region PA6-GF

            { "N08-B0", "72600" }, // Blue
            { "N08-D0", "72102" }, // White
            { "N08-D1", "72103" }, // Gray
            { "N08-G0", "72500" }, // Lime
            { "N08-K0", "72104" }, // Black
            { "N08-N0", "72800" }, // Brown
            { "N08-R0", "72200" }, // Orange
            { "N08-Y0", "72400" }, // Yellow

            #endregion

            #region Support for PLA/PETG

            { "S05-C0", "65103" }, // Black (collision, dumps: Black 9, Nature 2)
            { "S05-K0", "65103" }, // Black

            #endregion

            #region Support for PLA (New Version)

            { "S02-W1", "65104" }, // White

            #endregion

            #region Support for ABS

            { "S06-W0", "66100" }, // White

            #endregion

            #region Support for PA/PET

            { "S01-G1", "65500" }, // Green
            { "S03-G1", "65500" }, // Green

            #endregion

            #region PVA

            { "S04-Y0", "66400" }, // Clear

            #endregion

        };
    }
}
