// <auto-generated>
/*
 * Bambuddy
 *
 * Archive and manage Bambu Lab 3MF files
 *
 * The version of the OpenAPI document: 0.2.4.5
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Bambuddy.Api.Client;

namespace Bambuddy.Api.Model
{
    /// <summary>
    /// Lightweight archive response for stats/dashboard widgets.
    /// </summary>
    public partial class ArchiveSlim : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ArchiveSlim" /> class.
        /// </summary>
        /// <param name="status">status</param>
        /// <param name="createdAt">createdAt</param>
        /// <param name="printerId">printerId</param>
        /// <param name="printName">printName</param>
        /// <param name="printTimeSeconds">printTimeSeconds</param>
        /// <param name="actualTimeSeconds">actualTimeSeconds</param>
        /// <param name="filamentUsedGrams">filamentUsedGrams</param>
        /// <param name="filamentType">filamentType</param>
        /// <param name="filamentColor">filamentColor</param>
        /// <param name="startedAt">startedAt</param>
        /// <param name="completedAt">completedAt</param>
        /// <param name="cost">cost</param>
        /// <param name="quantity">quantity (default to 1)</param>
        [JsonConstructor]
        public ArchiveSlim(string status, DateTime createdAt, int? printerId = default, string? printName = default, int? printTimeSeconds = default, Option<int?> actualTimeSeconds = default, decimal? filamentUsedGrams = default, string? filamentType = default, string? filamentColor = default, DateTime? startedAt = default, DateTime? completedAt = default, decimal? cost = default, Option<int?> quantity = default)
        {
            Status = status;
            CreatedAt = createdAt;
            PrinterId = printerId;
            PrintName = printName;
            PrintTimeSeconds = printTimeSeconds;
            ActualTimeSecondsOption = actualTimeSeconds;
            FilamentUsedGrams = filamentUsedGrams;
            FilamentType = filamentType;
            FilamentColor = filamentColor;
            StartedAt = startedAt;
            CompletedAt = completedAt;
            Cost = cost;
            QuantityOption = quantity;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [JsonPropertyName("status")]
        public string Status { get; set; }

        /// <summary>
        /// Gets or Sets CreatedAt
        /// </summary>
        [JsonPropertyName("created_at")]
        public DateTime CreatedAt { get; set; }

        /// <summary>
        /// Gets or Sets PrinterId
        /// </summary>
        [JsonPropertyName("printer_id")]
        public int? PrinterId { get; set; }

        /// <summary>
        /// Gets or Sets PrintName
        /// </summary>
        [JsonPropertyName("print_name")]
        public string? PrintName { get; set; }

        /// <summary>
        /// Gets or Sets PrintTimeSeconds
        /// </summary>
        [JsonPropertyName("print_time_seconds")]
        public int? PrintTimeSeconds { get; set; }

        /// <summary>
        /// Used to track the state of ActualTimeSeconds
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> ActualTimeSecondsOption { get; private set; }

        /// <summary>
        /// Gets or Sets ActualTimeSeconds
        /// </summary>
        [JsonPropertyName("actual_time_seconds")]
        public int? ActualTimeSeconds { get { return this.ActualTimeSecondsOption.Value; } set { this.ActualTimeSecondsOption = new(value); } }

        /// <summary>
        /// Gets or Sets FilamentUsedGrams
        /// </summary>
        [JsonPropertyName("filament_used_grams")]
        public decimal? FilamentUsedGrams { get; set; }

        /// <summary>
        /// Gets or Sets FilamentType
        /// </summary>
        [JsonPropertyName("filament_type")]
        public string? FilamentType { get; set; }

        /// <summary>
        /// Gets or Sets FilamentColor
        /// </summary>
        [JsonPropertyName("filament_color")]
        public string? FilamentColor { get; set; }

        /// <summary>
        /// Gets or Sets StartedAt
        /// </summary>
        [JsonPropertyName("started_at")]
        public DateTime? StartedAt { get; set; }

        /// <summary>
        /// Gets or Sets CompletedAt
        /// </summary>
        [JsonPropertyName("completed_at")]
        public DateTime? CompletedAt { get; set; }

        /// <summary>
        /// Gets or Sets Cost
        /// </summary>
        [JsonPropertyName("cost")]
        public decimal? Cost { get; set; }

        /// <summary>
        /// Used to track the state of Quantity
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> QuantityOption { get; private set; }

        /// <summary>
        /// Gets or Sets Quantity
        /// </summary>
        [JsonPropertyName("quantity")]
        public int? Quantity { get { return this.QuantityOption.Value; } set { this.QuantityOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ArchiveSlim {\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  CreatedAt: ").Append(CreatedAt).Append("\n");
            sb.Append("  PrinterId: ").Append(PrinterId).Append("\n");
            sb.Append("  PrintName: ").Append(PrintName).Append("\n");
            sb.Append("  PrintTimeSeconds: ").Append(PrintTimeSeconds).Append("\n");
            sb.Append("  ActualTimeSeconds: ").Append(ActualTimeSeconds).Append("\n");
            sb.Append("  FilamentUsedGrams: ").Append(FilamentUsedGrams).Append("\n");
            sb.Append("  FilamentType: ").Append(FilamentType).Append("\n");
            sb.Append("  FilamentColor: ").Append(FilamentColor).Append("\n");
            sb.Append("  StartedAt: ").Append(StartedAt).Append("\n");
            sb.Append("  CompletedAt: ").Append(CompletedAt).Append("\n");
            sb.Append("  Cost: ").Append(Cost).Append("\n");
            sb.Append("  Quantity: ").Append(Quantity).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="ArchiveSlim" />
    /// </summary>
    public class ArchiveSlimJsonConverter : JsonConverter<ArchiveSlim>
    {
        /// <summary>
        /// The format to use to serialize CreatedAt
        /// </summary>
        public static string CreatedAtFormat { get; set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// The format to use to serialize StartedAt
        /// </summary>
        public static string StartedAtFormat { get; set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// The format to use to serialize CompletedAt
        /// </summary>
        public static string CompletedAtFormat { get; set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// Deserializes json to <see cref="ArchiveSlim" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override ArchiveSlim Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> status = default;
            Option<DateTime?> createdAt = default;
            Option<int?> printerId = default;
            Option<string?> printName = default;
            Option<int?> printTimeSeconds = default;
            Option<int?> actualTimeSeconds = default;
            Option<decimal?> filamentUsedGrams = default;
            Option<string?> filamentType = default;
            Option<string?> filamentColor = default;
            Option<DateTime?> startedAt = default;
            Option<DateTime?> completedAt = default;
            Option<decimal?> cost = default;
            Option<int?> quantity = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "status":
                            status = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "created_at":
                            createdAt = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "printer_id":
                            printerId = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "print_name":
                            printName = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "print_time_seconds":
                            printTimeSeconds = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "actual_time_seconds":
                            actualTimeSeconds = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "filament_used_grams":
                            filamentUsedGrams = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        case "filament_type":
                            filamentType = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "filament_color":
                            filamentColor = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "started_at":
                            startedAt = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime?>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "completed_at":
                            completedAt = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime?>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "cost":
                            cost = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        case "quantity":
                            quantity = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!status.IsSet)
                throw new ArgumentException("Property is required for class ArchiveSlim.", nameof(status));

            if (!createdAt.IsSet)
                throw new ArgumentException("Property is required for class ArchiveSlim.", nameof(createdAt));

            if (!printerId.IsSet)
                throw new ArgumentException("Property is required for class ArchiveSlim.", nameof(printerId));

            if (!printName.IsSet)
                throw new ArgumentException("Property is required for class ArchiveSlim.", nameof(printName));

            if (!printTimeSeconds.IsSet)
                throw new ArgumentException("Property is required for class ArchiveSlim.", nameof(printTimeSeconds));

            if (!filamentUsedGrams.IsSet)
                throw new ArgumentException("Property is required for class ArchiveSlim.", nameof(filamentUsedGrams));

            if (!filamentType.IsSet)
                throw new ArgumentException("Property is required for class ArchiveSlim.", nameof(filamentType));

            if (!filamentColor.IsSet)
                throw new ArgumentException("Property is required for class ArchiveSlim.", nameof(filamentColor));

            if (!startedAt.IsSet)
                throw new ArgumentException("Property is required for class ArchiveSlim.", nameof(startedAt));

            if (!completedAt.IsSet)
                throw new ArgumentException("Property is required for class ArchiveSlim.", nameof(completedAt));

            if (!cost.IsSet)
                throw new ArgumentException("Property is required for class ArchiveSlim.", nameof(cost));

            if (status.IsSet && status.Value == null)
                throw new ArgumentNullException(nameof(status), "Property is not nullable for class ArchiveSlim.");

            if (createdAt.IsSet && createdAt.Value == null)
                throw new ArgumentNullException(nameof(createdAt), "Property is not nullable for class ArchiveSlim.");

            if (quantity.IsSet && quantity.Value == null)
                throw new ArgumentNullException(nameof(quantity), "Property is not nullable for class ArchiveSlim.");

            return new ArchiveSlim(status.Value!, createdAt.Value!.Value!, printerId.Value!, printName.Value!, printTimeSeconds.Value!, actualTimeSeconds, filamentUsedGrams.Value!, filamentType.Value!, filamentColor.Value!, startedAt.Value!, completedAt.Value!, cost.Value!, quantity);
        }

        /// <summary>
        /// Serializes a <see cref="ArchiveSlim" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="archiveSlim"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, ArchiveSlim archiveSlim, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, archiveSlim, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="ArchiveSlim" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="archiveSlim"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, ArchiveSlim archiveSlim, JsonSerializerOptions jsonSerializerOptions)
        {
            if (archiveSlim.Status == null)
                throw new ArgumentNullException(nameof(archiveSlim.Status), "Property is required for class ArchiveSlim.");

            writer.WriteString("status", archiveSlim.Status);

            writer.WriteString("created_at", archiveSlim.CreatedAt.ToString(CreatedAtFormat));

            if (archiveSlim.PrinterId != null)
                writer.WriteNumber("printer_id", archiveSlim.PrinterId.Value);
            else
                writer.WriteNull("printer_id");

            if (archiveSlim.PrintName != null)
                writer.WriteString("print_name", archiveSlim.PrintName);
            else
                writer.WriteNull("print_name");

            if (archiveSlim.PrintTimeSeconds != null)
                writer.WriteNumber("print_time_seconds", archiveSlim.PrintTimeSeconds.Value);
            else
                writer.WriteNull("print_time_seconds");

            if (archiveSlim.ActualTimeSecondsOption.IsSet)
                if (archiveSlim.ActualTimeSecondsOption.Value != null)
                    writer.WriteNumber("actual_time_seconds", archiveSlim.ActualTimeSecondsOption.Value!.Value);
                else
                    writer.WriteNull("actual_time_seconds");

            if (archiveSlim.FilamentUsedGrams != null)
                writer.WriteNumber("filament_used_grams", archiveSlim.FilamentUsedGrams.Value);
            else
                writer.WriteNull("filament_used_grams");

            if (archiveSlim.FilamentType != null)
                writer.WriteString("filament_type", archiveSlim.FilamentType);
            else
                writer.WriteNull("filament_type");

            if (archiveSlim.FilamentColor != null)
                writer.WriteString("filament_color", archiveSlim.FilamentColor);
            else
                writer.WriteNull("filament_color");

            if (archiveSlim.StartedAt != null)
                writer.WriteString("started_at", archiveSlim.StartedAt.Value.ToString(StartedAtFormat));
            else
                writer.WriteNull("started_at");

            if (archiveSlim.CompletedAt != null)
                writer.WriteString("completed_at", archiveSlim.CompletedAt.Value.ToString(CompletedAtFormat));
            else
                writer.WriteNull("completed_at");

            if (archiveSlim.Cost != null)
                writer.WriteNumber("cost", archiveSlim.Cost.Value);
            else
                writer.WriteNull("cost");

            if (archiveSlim.QuantityOption.IsSet)
                writer.WriteNumber("quantity", archiveSlim.QuantityOption.Value!.Value);
        }
    }
}
