// <auto-generated>
/*
 * Bambuddy
 *
 * Archive and manage Bambu Lab 3MF files
 *
 * The version of the OpenAPI document: 0.2.4.5
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Bambuddy.Api.Client;

namespace Bambuddy.Api.Model
{
    /// <summary>
    /// Response containing firmware updates for all devices.
    /// </summary>
    public partial class BackendAppSchemasCloudFirmwareUpdatesResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BackendAppSchemasCloudFirmwareUpdatesResponse" /> class.
        /// </summary>
        /// <param name="updates">updates</param>
        /// <param name="updatesAvailable">Total number of devices with updates available (default to 0)</param>
        [JsonConstructor]
        public BackendAppSchemasCloudFirmwareUpdatesResponse(Option<List<BackendAppSchemasCloudFirmwareUpdateInfo>?> updates = default, Option<int?> updatesAvailable = default)
        {
            UpdatesOption = updates;
            UpdatesAvailableOption = updatesAvailable;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Updates
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<BackendAppSchemasCloudFirmwareUpdateInfo>?> UpdatesOption { get; private set; }

        /// <summary>
        /// Gets or Sets Updates
        /// </summary>
        [JsonPropertyName("updates")]
        public List<BackendAppSchemasCloudFirmwareUpdateInfo>? Updates { get { return this.UpdatesOption.Value; } set { this.UpdatesOption = new(value); } }

        /// <summary>
        /// Used to track the state of UpdatesAvailable
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> UpdatesAvailableOption { get; private set; }

        /// <summary>
        /// Total number of devices with updates available
        /// </summary>
        /// <value>Total number of devices with updates available</value>
        [JsonPropertyName("updates_available")]
        public int? UpdatesAvailable { get { return this.UpdatesAvailableOption.Value; } set { this.UpdatesAvailableOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class BackendAppSchemasCloudFirmwareUpdatesResponse {\n");
            sb.Append("  Updates: ").Append(Updates).Append("\n");
            sb.Append("  UpdatesAvailable: ").Append(UpdatesAvailable).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="BackendAppSchemasCloudFirmwareUpdatesResponse" />
    /// </summary>
    public class BackendAppSchemasCloudFirmwareUpdatesResponseJsonConverter : JsonConverter<BackendAppSchemasCloudFirmwareUpdatesResponse>
    {
        /// <summary>
        /// Deserializes json to <see cref="BackendAppSchemasCloudFirmwareUpdatesResponse" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override BackendAppSchemasCloudFirmwareUpdatesResponse Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<List<BackendAppSchemasCloudFirmwareUpdateInfo>?> updates = default;
            Option<int?> updatesAvailable = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "updates":
                            updates = new Option<List<BackendAppSchemasCloudFirmwareUpdateInfo>?>(JsonSerializer.Deserialize<List<BackendAppSchemasCloudFirmwareUpdateInfo>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "updates_available":
                            updatesAvailable = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (updates.IsSet && updates.Value == null)
                throw new ArgumentNullException(nameof(updates), "Property is not nullable for class BackendAppSchemasCloudFirmwareUpdatesResponse.");

            if (updatesAvailable.IsSet && updatesAvailable.Value == null)
                throw new ArgumentNullException(nameof(updatesAvailable), "Property is not nullable for class BackendAppSchemasCloudFirmwareUpdatesResponse.");

            return new BackendAppSchemasCloudFirmwareUpdatesResponse(updates, updatesAvailable);
        }

        /// <summary>
        /// Serializes a <see cref="BackendAppSchemasCloudFirmwareUpdatesResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="backendAppSchemasCloudFirmwareUpdatesResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, BackendAppSchemasCloudFirmwareUpdatesResponse backendAppSchemasCloudFirmwareUpdatesResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, backendAppSchemasCloudFirmwareUpdatesResponse, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="BackendAppSchemasCloudFirmwareUpdatesResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="backendAppSchemasCloudFirmwareUpdatesResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, BackendAppSchemasCloudFirmwareUpdatesResponse backendAppSchemasCloudFirmwareUpdatesResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            if (backendAppSchemasCloudFirmwareUpdatesResponse.UpdatesOption.IsSet && backendAppSchemasCloudFirmwareUpdatesResponse.Updates == null)
                throw new ArgumentNullException(nameof(backendAppSchemasCloudFirmwareUpdatesResponse.Updates), "Property is required for class BackendAppSchemasCloudFirmwareUpdatesResponse.");

            if (backendAppSchemasCloudFirmwareUpdatesResponse.UpdatesOption.IsSet)
            {
                writer.WritePropertyName("updates");
                JsonSerializer.Serialize(writer, backendAppSchemasCloudFirmwareUpdatesResponse.Updates, jsonSerializerOptions);
            }
            if (backendAppSchemasCloudFirmwareUpdatesResponse.UpdatesAvailableOption.IsSet)
                writer.WriteNumber("updates_available", backendAppSchemasCloudFirmwareUpdatesResponse.UpdatesAvailableOption.Value!.Value);
        }
    }
}
