// <auto-generated>
/*
 * Bambuddy
 *
 * Archive and manage Bambu Lab 3MF files
 *
 * The version of the OpenAPI document: 0.2.4.5
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Bambuddy.Api.Client;

namespace Bambuddy.Api.Model
{
    /// <summary>
    /// Git hosting provider types.
    /// </summary>
    /// <value>Git hosting provider types.</value>
    public enum BackendAppSchemasGithubBackupProviderType
    {
        /// <summary>
        /// Enum Github for value: github
        /// </summary>
        Github = 1,

        /// <summary>
        /// Enum Gitlab for value: gitlab
        /// </summary>
        Gitlab = 2,

        /// <summary>
        /// Enum Gitea for value: gitea
        /// </summary>
        Gitea = 3,

        /// <summary>
        /// Enum Forgejo for value: forgejo
        /// </summary>
        Forgejo = 4
    }

    /// <summary>
    /// Converts <see cref="BackendAppSchemasGithubBackupProviderType"/> to and from the JSON value
    /// </summary>
    public static class BackendAppSchemasGithubBackupProviderTypeValueConverter
    {
        /// <summary>
        /// Parses a given value to <see cref="BackendAppSchemasGithubBackupProviderType"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static BackendAppSchemasGithubBackupProviderType FromString(string value)
        {
            if (value.Equals("github"))
                return BackendAppSchemasGithubBackupProviderType.Github;

            if (value.Equals("gitlab"))
                return BackendAppSchemasGithubBackupProviderType.Gitlab;

            if (value.Equals("gitea"))
                return BackendAppSchemasGithubBackupProviderType.Gitea;

            if (value.Equals("forgejo"))
                return BackendAppSchemasGithubBackupProviderType.Forgejo;

            throw new NotImplementedException($"Could not convert value to type BackendAppSchemasGithubBackupProviderType: '{value}'");
        }

        /// <summary>
        /// Parses a given value to <see cref="BackendAppSchemasGithubBackupProviderType"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static BackendAppSchemasGithubBackupProviderType? FromStringOrDefault(string value)
        {
            if (value.Equals("github"))
                return BackendAppSchemasGithubBackupProviderType.Github;

            if (value.Equals("gitlab"))
                return BackendAppSchemasGithubBackupProviderType.Gitlab;

            if (value.Equals("gitea"))
                return BackendAppSchemasGithubBackupProviderType.Gitea;

            if (value.Equals("forgejo"))
                return BackendAppSchemasGithubBackupProviderType.Forgejo;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="BackendAppSchemasGithubBackupProviderType"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string ToJsonValue(BackendAppSchemasGithubBackupProviderType value)
        {
            if (value == BackendAppSchemasGithubBackupProviderType.Github)
                return "github";

            if (value == BackendAppSchemasGithubBackupProviderType.Gitlab)
                return "gitlab";

            if (value == BackendAppSchemasGithubBackupProviderType.Gitea)
                return "gitea";

            if (value == BackendAppSchemasGithubBackupProviderType.Forgejo)
                return "forgejo";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="BackendAppSchemasGithubBackupProviderType"/>
    /// </summary>
    /// <exception cref="NotImplementedException"></exception>
    public class BackendAppSchemasGithubBackupProviderTypeJsonConverter : JsonConverter<BackendAppSchemasGithubBackupProviderType>
    {
        /// <summary>
        /// Returns a  from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override BackendAppSchemasGithubBackupProviderType Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string? rawValue = reader.GetString();

            BackendAppSchemasGithubBackupProviderType? result = rawValue == null
                ? null
                : BackendAppSchemasGithubBackupProviderTypeValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the BackendAppSchemasGithubBackupProviderType to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="backendAppSchemasGithubBackupProviderType"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, BackendAppSchemasGithubBackupProviderType backendAppSchemasGithubBackupProviderType, JsonSerializerOptions options)
        {
            writer.WriteStringValue(BackendAppSchemasGithubBackupProviderTypeValueConverter.ToJsonValue(backendAppSchemasGithubBackupProviderType).ToString());
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="BackendAppSchemasGithubBackupProviderType"/>
    /// </summary>
    public class BackendAppSchemasGithubBackupProviderTypeNullableJsonConverter : JsonConverter<BackendAppSchemasGithubBackupProviderType?>
    {
        /// <summary>
        /// Returns a BackendAppSchemasGithubBackupProviderType from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override BackendAppSchemasGithubBackupProviderType? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string? rawValue = reader.GetString();

            BackendAppSchemasGithubBackupProviderType? result = rawValue == null
                ? null
                : BackendAppSchemasGithubBackupProviderTypeValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the BackendAppSchemasGithubBackupProviderType to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="backendAppSchemasGithubBackupProviderType"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, BackendAppSchemasGithubBackupProviderType? backendAppSchemasGithubBackupProviderType, JsonSerializerOptions options)
        {
            writer.WriteStringValue(backendAppSchemasGithubBackupProviderType.HasValue ? BackendAppSchemasGithubBackupProviderTypeValueConverter.ToJsonValue(backendAppSchemasGithubBackupProviderType.Value).ToString() : "null");
        }
    }
}
