// <auto-generated>
/*
 * Bambuddy
 *
 * Archive and manage Bambu Lab 3MF files
 *
 * The version of the OpenAPI document: 0.2.4.5
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Bambuddy.Api.Client;

namespace Bambuddy.Api.Model
{
    /// <summary>
    /// Schema for bulk delete operations.
    /// </summary>
    public partial class BulkDeleteRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BulkDeleteRequest" /> class.
        /// </summary>
        /// <param name="fileIds">fileIds</param>
        /// <param name="folderIds">folderIds</param>
        [JsonConstructor]
        public BulkDeleteRequest(Option<List<int>?> fileIds = default, Option<List<int>?> folderIds = default)
        {
            FileIdsOption = fileIds;
            FolderIdsOption = folderIds;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of FileIds
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<int>?> FileIdsOption { get; private set; }

        /// <summary>
        /// Gets or Sets FileIds
        /// </summary>
        [JsonPropertyName("file_ids")]
        public List<int>? FileIds { get { return this.FileIdsOption.Value; } set { this.FileIdsOption = new(value); } }

        /// <summary>
        /// Used to track the state of FolderIds
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<int>?> FolderIdsOption { get; private set; }

        /// <summary>
        /// Gets or Sets FolderIds
        /// </summary>
        [JsonPropertyName("folder_ids")]
        public List<int>? FolderIds { get { return this.FolderIdsOption.Value; } set { this.FolderIdsOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class BulkDeleteRequest {\n");
            sb.Append("  FileIds: ").Append(FileIds).Append("\n");
            sb.Append("  FolderIds: ").Append(FolderIds).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="BulkDeleteRequest" />
    /// </summary>
    public class BulkDeleteRequestJsonConverter : JsonConverter<BulkDeleteRequest>
    {
        /// <summary>
        /// Deserializes json to <see cref="BulkDeleteRequest" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override BulkDeleteRequest Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<List<int>?> fileIds = default;
            Option<List<int>?> folderIds = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "file_ids":
                            fileIds = new Option<List<int>?>(JsonSerializer.Deserialize<List<int>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "folder_ids":
                            folderIds = new Option<List<int>?>(JsonSerializer.Deserialize<List<int>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (fileIds.IsSet && fileIds.Value == null)
                throw new ArgumentNullException(nameof(fileIds), "Property is not nullable for class BulkDeleteRequest.");

            if (folderIds.IsSet && folderIds.Value == null)
                throw new ArgumentNullException(nameof(folderIds), "Property is not nullable for class BulkDeleteRequest.");

            return new BulkDeleteRequest(fileIds, folderIds);
        }

        /// <summary>
        /// Serializes a <see cref="BulkDeleteRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="bulkDeleteRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, BulkDeleteRequest bulkDeleteRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, bulkDeleteRequest, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="BulkDeleteRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="bulkDeleteRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, BulkDeleteRequest bulkDeleteRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            if (bulkDeleteRequest.FileIdsOption.IsSet && bulkDeleteRequest.FileIds == null)
                throw new ArgumentNullException(nameof(bulkDeleteRequest.FileIds), "Property is required for class BulkDeleteRequest.");

            if (bulkDeleteRequest.FolderIdsOption.IsSet && bulkDeleteRequest.FolderIds == null)
                throw new ArgumentNullException(nameof(bulkDeleteRequest.FolderIds), "Property is required for class BulkDeleteRequest.");

            if (bulkDeleteRequest.FileIdsOption.IsSet)
            {
                writer.WritePropertyName("file_ids");
                JsonSerializer.Serialize(writer, bulkDeleteRequest.FileIds, jsonSerializerOptions);
            }
            if (bulkDeleteRequest.FolderIdsOption.IsSet)
            {
                writer.WritePropertyName("folder_ids");
                JsonSerializer.Serialize(writer, bulkDeleteRequest.FolderIds, jsonSerializerOptions);
            }
        }
    }
}
