// <auto-generated>
/*
 * Bambuddy
 *
 * Archive and manage Bambu Lab 3MF files
 *
 * The version of the OpenAPI document: 0.2.4.5
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Bambuddy.Api.Client;

namespace Bambuddy.Api.Model
{
    /// <summary>
    /// ColorEntryUpdate
    /// </summary>
    public partial class ColorEntryUpdate : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ColorEntryUpdate" /> class.
        /// </summary>
        /// <param name="manufacturer">manufacturer</param>
        /// <param name="colorName">colorName</param>
        /// <param name="hexColor">hexColor</param>
        /// <param name="material">material</param>
        /// <param name="extraColors">extraColors</param>
        /// <param name="effectType">effectType</param>
        [JsonConstructor]
        public ColorEntryUpdate(string manufacturer, string colorName, string hexColor, Option<string?> material = default, Option<string?> extraColors = default, Option<string?> effectType = default)
        {
            Manufacturer = manufacturer;
            ColorName = colorName;
            HexColor = hexColor;
            MaterialOption = material;
            ExtraColorsOption = extraColors;
            EffectTypeOption = effectType;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Manufacturer
        /// </summary>
        [JsonPropertyName("manufacturer")]
        public string Manufacturer { get; set; }

        /// <summary>
        /// Gets or Sets ColorName
        /// </summary>
        [JsonPropertyName("color_name")]
        public string ColorName { get; set; }

        /// <summary>
        /// Gets or Sets HexColor
        /// </summary>
        [JsonPropertyName("hex_color")]
        public string HexColor { get; set; }

        /// <summary>
        /// Used to track the state of Material
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> MaterialOption { get; private set; }

        /// <summary>
        /// Gets or Sets Material
        /// </summary>
        [JsonPropertyName("material")]
        public string? Material { get { return this.MaterialOption.Value; } set { this.MaterialOption = new(value); } }

        /// <summary>
        /// Used to track the state of ExtraColors
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ExtraColorsOption { get; private set; }

        /// <summary>
        /// Gets or Sets ExtraColors
        /// </summary>
        [JsonPropertyName("extra_colors")]
        public string? ExtraColors { get { return this.ExtraColorsOption.Value; } set { this.ExtraColorsOption = new(value); } }

        /// <summary>
        /// Used to track the state of EffectType
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> EffectTypeOption { get; private set; }

        /// <summary>
        /// Gets or Sets EffectType
        /// </summary>
        [JsonPropertyName("effect_type")]
        public string? EffectType { get { return this.EffectTypeOption.Value; } set { this.EffectTypeOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ColorEntryUpdate {\n");
            sb.Append("  Manufacturer: ").Append(Manufacturer).Append("\n");
            sb.Append("  ColorName: ").Append(ColorName).Append("\n");
            sb.Append("  HexColor: ").Append(HexColor).Append("\n");
            sb.Append("  Material: ").Append(Material).Append("\n");
            sb.Append("  ExtraColors: ").Append(ExtraColors).Append("\n");
            sb.Append("  EffectType: ").Append(EffectType).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            if (this.HexColor != null) {
                // HexColor (string) pattern
                Regex regexHexColor = new Regex(@"^#[0-9A-Fa-f]{6}([0-9A-Fa-f]{2})?$", RegexOptions.CultureInvariant);

                if (!regexHexColor.Match(this.HexColor).Success)
                {
                    yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for HexColor, must match a pattern of " + regexHexColor, new [] { "HexColor" });
                }
            }

            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="ColorEntryUpdate" />
    /// </summary>
    public class ColorEntryUpdateJsonConverter : JsonConverter<ColorEntryUpdate>
    {
        /// <summary>
        /// Deserializes json to <see cref="ColorEntryUpdate" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override ColorEntryUpdate Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> manufacturer = default;
            Option<string?> colorName = default;
            Option<string?> hexColor = default;
            Option<string?> material = default;
            Option<string?> extraColors = default;
            Option<string?> effectType = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "manufacturer":
                            manufacturer = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "color_name":
                            colorName = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "hex_color":
                            hexColor = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "material":
                            material = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "extra_colors":
                            extraColors = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "effect_type":
                            effectType = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!manufacturer.IsSet)
                throw new ArgumentException("Property is required for class ColorEntryUpdate.", nameof(manufacturer));

            if (!colorName.IsSet)
                throw new ArgumentException("Property is required for class ColorEntryUpdate.", nameof(colorName));

            if (!hexColor.IsSet)
                throw new ArgumentException("Property is required for class ColorEntryUpdate.", nameof(hexColor));

            if (manufacturer.IsSet && manufacturer.Value == null)
                throw new ArgumentNullException(nameof(manufacturer), "Property is not nullable for class ColorEntryUpdate.");

            if (colorName.IsSet && colorName.Value == null)
                throw new ArgumentNullException(nameof(colorName), "Property is not nullable for class ColorEntryUpdate.");

            if (hexColor.IsSet && hexColor.Value == null)
                throw new ArgumentNullException(nameof(hexColor), "Property is not nullable for class ColorEntryUpdate.");

            return new ColorEntryUpdate(manufacturer.Value!, colorName.Value!, hexColor.Value!, material, extraColors, effectType);
        }

        /// <summary>
        /// Serializes a <see cref="ColorEntryUpdate" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="colorEntryUpdate"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, ColorEntryUpdate colorEntryUpdate, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, colorEntryUpdate, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="ColorEntryUpdate" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="colorEntryUpdate"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, ColorEntryUpdate colorEntryUpdate, JsonSerializerOptions jsonSerializerOptions)
        {
            if (colorEntryUpdate.Manufacturer == null)
                throw new ArgumentNullException(nameof(colorEntryUpdate.Manufacturer), "Property is required for class ColorEntryUpdate.");

            if (colorEntryUpdate.ColorName == null)
                throw new ArgumentNullException(nameof(colorEntryUpdate.ColorName), "Property is required for class ColorEntryUpdate.");

            if (colorEntryUpdate.HexColor == null)
                throw new ArgumentNullException(nameof(colorEntryUpdate.HexColor), "Property is required for class ColorEntryUpdate.");

            writer.WriteString("manufacturer", colorEntryUpdate.Manufacturer);

            writer.WriteString("color_name", colorEntryUpdate.ColorName);

            writer.WriteString("hex_color", colorEntryUpdate.HexColor);

            if (colorEntryUpdate.MaterialOption.IsSet)
                if (colorEntryUpdate.MaterialOption.Value != null)
                    writer.WriteString("material", colorEntryUpdate.Material);
                else
                    writer.WriteNull("material");

            if (colorEntryUpdate.ExtraColorsOption.IsSet)
                if (colorEntryUpdate.ExtraColorsOption.Value != null)
                    writer.WriteString("extra_colors", colorEntryUpdate.ExtraColors);
                else
                    writer.WriteNull("extra_colors");

            if (colorEntryUpdate.EffectTypeOption.IsSet)
                if (colorEntryUpdate.EffectTypeOption.Value != null)
                    writer.WriteString("effect_type", colorEntryUpdate.EffectType);
                else
                    writer.WriteNull("effect_type");
        }
    }
}
