// <auto-generated>
/*
 * Bambuddy
 *
 * Archive and manage Bambu Lab 3MF files
 *
 * The version of the OpenAPI document: 0.2.4.5
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Bambuddy.Api.Client;

namespace Bambuddy.Api.Model
{
    /// <summary>
    /// Discovery environment info.
    /// </summary>
    public partial class DiscoveryInfo : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DiscoveryInfo" /> class.
        /// </summary>
        /// <param name="isDocker">isDocker</param>
        /// <param name="ssdpRunning">ssdpRunning</param>
        /// <param name="scanRunning">scanRunning</param>
        /// <param name="subnets">subnets</param>
        [JsonConstructor]
        public DiscoveryInfo(bool isDocker, bool ssdpRunning, bool scanRunning, Option<List<string>?> subnets = default)
        {
            IsDocker = isDocker;
            SsdpRunning = ssdpRunning;
            ScanRunning = scanRunning;
            SubnetsOption = subnets;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets IsDocker
        /// </summary>
        [JsonPropertyName("is_docker")]
        public bool IsDocker { get; set; }

        /// <summary>
        /// Gets or Sets SsdpRunning
        /// </summary>
        [JsonPropertyName("ssdp_running")]
        public bool SsdpRunning { get; set; }

        /// <summary>
        /// Gets or Sets ScanRunning
        /// </summary>
        [JsonPropertyName("scan_running")]
        public bool ScanRunning { get; set; }

        /// <summary>
        /// Used to track the state of Subnets
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<string>?> SubnetsOption { get; private set; }

        /// <summary>
        /// Gets or Sets Subnets
        /// </summary>
        [JsonPropertyName("subnets")]
        public List<string>? Subnets { get { return this.SubnetsOption.Value; } set { this.SubnetsOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class DiscoveryInfo {\n");
            sb.Append("  IsDocker: ").Append(IsDocker).Append("\n");
            sb.Append("  SsdpRunning: ").Append(SsdpRunning).Append("\n");
            sb.Append("  ScanRunning: ").Append(ScanRunning).Append("\n");
            sb.Append("  Subnets: ").Append(Subnets).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="DiscoveryInfo" />
    /// </summary>
    public class DiscoveryInfoJsonConverter : JsonConverter<DiscoveryInfo>
    {
        /// <summary>
        /// Deserializes json to <see cref="DiscoveryInfo" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override DiscoveryInfo Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<bool?> isDocker = default;
            Option<bool?> ssdpRunning = default;
            Option<bool?> scanRunning = default;
            Option<List<string>?> subnets = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "is_docker":
                            isDocker = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "ssdp_running":
                            ssdpRunning = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "scan_running":
                            scanRunning = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "subnets":
                            subnets = new Option<List<string>?>(JsonSerializer.Deserialize<List<string>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!isDocker.IsSet)
                throw new ArgumentException("Property is required for class DiscoveryInfo.", nameof(isDocker));

            if (!ssdpRunning.IsSet)
                throw new ArgumentException("Property is required for class DiscoveryInfo.", nameof(ssdpRunning));

            if (!scanRunning.IsSet)
                throw new ArgumentException("Property is required for class DiscoveryInfo.", nameof(scanRunning));

            if (isDocker.IsSet && isDocker.Value == null)
                throw new ArgumentNullException(nameof(isDocker), "Property is not nullable for class DiscoveryInfo.");

            if (ssdpRunning.IsSet && ssdpRunning.Value == null)
                throw new ArgumentNullException(nameof(ssdpRunning), "Property is not nullable for class DiscoveryInfo.");

            if (scanRunning.IsSet && scanRunning.Value == null)
                throw new ArgumentNullException(nameof(scanRunning), "Property is not nullable for class DiscoveryInfo.");

            if (subnets.IsSet && subnets.Value == null)
                throw new ArgumentNullException(nameof(subnets), "Property is not nullable for class DiscoveryInfo.");

            return new DiscoveryInfo(isDocker.Value!.Value!, ssdpRunning.Value!.Value!, scanRunning.Value!.Value!, subnets);
        }

        /// <summary>
        /// Serializes a <see cref="DiscoveryInfo" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="discoveryInfo"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, DiscoveryInfo discoveryInfo, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, discoveryInfo, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="DiscoveryInfo" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="discoveryInfo"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, DiscoveryInfo discoveryInfo, JsonSerializerOptions jsonSerializerOptions)
        {
            if (discoveryInfo.SubnetsOption.IsSet && discoveryInfo.Subnets == null)
                throw new ArgumentNullException(nameof(discoveryInfo.Subnets), "Property is required for class DiscoveryInfo.");

            writer.WriteBoolean("is_docker", discoveryInfo.IsDocker);

            writer.WriteBoolean("ssdp_running", discoveryInfo.SsdpRunning);

            writer.WriteBoolean("scan_running", discoveryInfo.ScanRunning);

            if (discoveryInfo.SubnetsOption.IsSet)
            {
                writer.WritePropertyName("subnets");
                JsonSerializer.Serialize(writer, discoveryInfo.Subnets, jsonSerializerOptions);
            }
        }
    }
}
