// <auto-generated>
/*
 * Bambuddy
 *
 * Archive and manage Bambu Lab 3MF files
 *
 * The version of the OpenAPI document: 0.2.4.5
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Bambuddy.Api.Client;

namespace Bambuddy.Api.Model
{
    /// <summary>
    /// EncryptionStatusResponse
    /// </summary>
    public partial class EncryptionStatusResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EncryptionStatusResponse" /> class.
        /// </summary>
        /// <param name="keyConfigured">keyConfigured</param>
        /// <param name="keySource">keySource</param>
        /// <param name="legacyPlaintextRows">legacyPlaintextRows</param>
        /// <param name="encryptedRows">encryptedRows</param>
        /// <param name="decryptionBroken">decryptionBroken (default to false)</param>
        /// <param name="migrationErrorCount">migrationErrorCount (default to 0)</param>
        [JsonConstructor]
        public EncryptionStatusResponse(bool keyConfigured, KeySourceEnum keySource, EncryptionRowCounts legacyPlaintextRows, EncryptionRowCounts encryptedRows, Option<bool?> decryptionBroken = default, Option<int?> migrationErrorCount = default)
        {
            KeyConfigured = keyConfigured;
            KeySource = keySource;
            LegacyPlaintextRows = legacyPlaintextRows;
            EncryptedRows = encryptedRows;
            DecryptionBrokenOption = decryptionBroken;
            MigrationErrorCountOption = migrationErrorCount;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Defines KeySource
        /// </summary>
        public enum KeySourceEnum
        {
            /// <summary>
            /// Enum Env for value: env
            /// </summary>
            Env = 1,

            /// <summary>
            /// Enum File for value: file
            /// </summary>
            File = 2,

            /// <summary>
            /// Enum Generated for value: generated
            /// </summary>
            Generated = 3,

            /// <summary>
            /// Enum None for value: none
            /// </summary>
            None = 4
        }

        /// <summary>
        /// Returns a <see cref="KeySourceEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static KeySourceEnum KeySourceEnumFromString(string value)
        {
            if (value.Equals("env"))
                return KeySourceEnum.Env;

            if (value.Equals("file"))
                return KeySourceEnum.File;

            if (value.Equals("generated"))
                return KeySourceEnum.Generated;

            if (value.Equals("none"))
                return KeySourceEnum.None;

            throw new NotImplementedException($"Could not convert value to type KeySourceEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="KeySourceEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static KeySourceEnum? KeySourceEnumFromStringOrDefault(string value)
        {
            if (value.Equals("env"))
                return KeySourceEnum.Env;

            if (value.Equals("file"))
                return KeySourceEnum.File;

            if (value.Equals("generated"))
                return KeySourceEnum.Generated;

            if (value.Equals("none"))
                return KeySourceEnum.None;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="KeySourceEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string KeySourceEnumToJsonValue(KeySourceEnum value)
        {
            if (value == KeySourceEnum.Env)
                return "env";

            if (value == KeySourceEnum.File)
                return "file";

            if (value == KeySourceEnum.Generated)
                return "generated";

            if (value == KeySourceEnum.None)
                return "none";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Gets or Sets KeySource
        /// </summary>
        [JsonPropertyName("key_source")]
        public KeySourceEnum KeySource { get; set; }

        /// <summary>
        /// Gets or Sets KeyConfigured
        /// </summary>
        [JsonPropertyName("key_configured")]
        public bool KeyConfigured { get; set; }

        /// <summary>
        /// Gets or Sets LegacyPlaintextRows
        /// </summary>
        [JsonPropertyName("legacy_plaintext_rows")]
        public EncryptionRowCounts LegacyPlaintextRows { get; set; }

        /// <summary>
        /// Gets or Sets EncryptedRows
        /// </summary>
        [JsonPropertyName("encrypted_rows")]
        public EncryptionRowCounts EncryptedRows { get; set; }

        /// <summary>
        /// Used to track the state of DecryptionBroken
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> DecryptionBrokenOption { get; private set; }

        /// <summary>
        /// Gets or Sets DecryptionBroken
        /// </summary>
        [JsonPropertyName("decryption_broken")]
        public bool? DecryptionBroken { get { return this.DecryptionBrokenOption.Value; } set { this.DecryptionBrokenOption = new(value); } }

        /// <summary>
        /// Used to track the state of MigrationErrorCount
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> MigrationErrorCountOption { get; private set; }

        /// <summary>
        /// Gets or Sets MigrationErrorCount
        /// </summary>
        [JsonPropertyName("migration_error_count")]
        public int? MigrationErrorCount { get { return this.MigrationErrorCountOption.Value; } set { this.MigrationErrorCountOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class EncryptionStatusResponse {\n");
            sb.Append("  KeyConfigured: ").Append(KeyConfigured).Append("\n");
            sb.Append("  KeySource: ").Append(KeySource).Append("\n");
            sb.Append("  LegacyPlaintextRows: ").Append(LegacyPlaintextRows).Append("\n");
            sb.Append("  EncryptedRows: ").Append(EncryptedRows).Append("\n");
            sb.Append("  DecryptionBroken: ").Append(DecryptionBroken).Append("\n");
            sb.Append("  MigrationErrorCount: ").Append(MigrationErrorCount).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="EncryptionStatusResponse" />
    /// </summary>
    public class EncryptionStatusResponseJsonConverter : JsonConverter<EncryptionStatusResponse>
    {
        /// <summary>
        /// Deserializes json to <see cref="EncryptionStatusResponse" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override EncryptionStatusResponse Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<bool?> keyConfigured = default;
            Option<EncryptionStatusResponse.KeySourceEnum?> keySource = default;
            Option<EncryptionRowCounts?> legacyPlaintextRows = default;
            Option<EncryptionRowCounts?> encryptedRows = default;
            Option<bool?> decryptionBroken = default;
            Option<int?> migrationErrorCount = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "key_configured":
                            keyConfigured = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "key_source":
                            string? keySourceRawValue = utf8JsonReader.GetString();
                            if (keySourceRawValue != null)
                                keySource = new Option<EncryptionStatusResponse.KeySourceEnum?>(EncryptionStatusResponse.KeySourceEnumFromStringOrDefault(keySourceRawValue));
                            break;
                        case "legacy_plaintext_rows":
                            legacyPlaintextRows = new Option<EncryptionRowCounts?>(JsonSerializer.Deserialize<EncryptionRowCounts>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "encrypted_rows":
                            encryptedRows = new Option<EncryptionRowCounts?>(JsonSerializer.Deserialize<EncryptionRowCounts>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "decryption_broken":
                            decryptionBroken = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "migration_error_count":
                            migrationErrorCount = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!keyConfigured.IsSet)
                throw new ArgumentException("Property is required for class EncryptionStatusResponse.", nameof(keyConfigured));

            if (!keySource.IsSet)
                throw new ArgumentException("Property is required for class EncryptionStatusResponse.", nameof(keySource));

            if (!legacyPlaintextRows.IsSet)
                throw new ArgumentException("Property is required for class EncryptionStatusResponse.", nameof(legacyPlaintextRows));

            if (!encryptedRows.IsSet)
                throw new ArgumentException("Property is required for class EncryptionStatusResponse.", nameof(encryptedRows));

            if (keyConfigured.IsSet && keyConfigured.Value == null)
                throw new ArgumentNullException(nameof(keyConfigured), "Property is not nullable for class EncryptionStatusResponse.");

            if (keySource.IsSet && keySource.Value == null)
                throw new ArgumentNullException(nameof(keySource), "Property is not nullable for class EncryptionStatusResponse.");

            if (legacyPlaintextRows.IsSet && legacyPlaintextRows.Value == null)
                throw new ArgumentNullException(nameof(legacyPlaintextRows), "Property is not nullable for class EncryptionStatusResponse.");

            if (encryptedRows.IsSet && encryptedRows.Value == null)
                throw new ArgumentNullException(nameof(encryptedRows), "Property is not nullable for class EncryptionStatusResponse.");

            if (decryptionBroken.IsSet && decryptionBroken.Value == null)
                throw new ArgumentNullException(nameof(decryptionBroken), "Property is not nullable for class EncryptionStatusResponse.");

            if (migrationErrorCount.IsSet && migrationErrorCount.Value == null)
                throw new ArgumentNullException(nameof(migrationErrorCount), "Property is not nullable for class EncryptionStatusResponse.");

            return new EncryptionStatusResponse(keyConfigured.Value!.Value!, keySource.Value!.Value!, legacyPlaintextRows.Value!, encryptedRows.Value!, decryptionBroken, migrationErrorCount);
        }

        /// <summary>
        /// Serializes a <see cref="EncryptionStatusResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="encryptionStatusResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, EncryptionStatusResponse encryptionStatusResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, encryptionStatusResponse, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="EncryptionStatusResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="encryptionStatusResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, EncryptionStatusResponse encryptionStatusResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            if (encryptionStatusResponse.LegacyPlaintextRows == null)
                throw new ArgumentNullException(nameof(encryptionStatusResponse.LegacyPlaintextRows), "Property is required for class EncryptionStatusResponse.");

            if (encryptionStatusResponse.EncryptedRows == null)
                throw new ArgumentNullException(nameof(encryptionStatusResponse.EncryptedRows), "Property is required for class EncryptionStatusResponse.");

            writer.WriteBoolean("key_configured", encryptionStatusResponse.KeyConfigured);

            var keySourceRawValue = EncryptionStatusResponse.KeySourceEnumToJsonValue(encryptionStatusResponse.KeySource);
            writer.WriteString("key_source", keySourceRawValue);
            writer.WritePropertyName("legacy_plaintext_rows");
            JsonSerializer.Serialize(writer, encryptionStatusResponse.LegacyPlaintextRows, jsonSerializerOptions);
            writer.WritePropertyName("encrypted_rows");
            JsonSerializer.Serialize(writer, encryptionStatusResponse.EncryptedRows, jsonSerializerOptions);
            if (encryptionStatusResponse.DecryptionBrokenOption.IsSet)
                writer.WriteBoolean("decryption_broken", encryptionStatusResponse.DecryptionBrokenOption.Value!.Value);

            if (encryptionStatusResponse.MigrationErrorCountOption.IsSet)
                writer.WriteNumber("migration_error_count", encryptionStatusResponse.MigrationErrorCountOption.Value!.Value);
        }
    }
}
