// <auto-generated>
/*
 * Bambuddy
 *
 * Archive and manage Bambu Lab 3MF files
 *
 * The version of the OpenAPI document: 0.2.4.5
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Bambuddy.Api.Client;

namespace Bambuddy.Api.Model
{
    /// <summary>
    /// Schema for reordering external links.
    /// </summary>
    public partial class ExternalLinkReorder : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ExternalLinkReorder" /> class.
        /// </summary>
        /// <param name="ids">List of link IDs in desired order</param>
        [JsonConstructor]
        public ExternalLinkReorder(List<int> ids)
        {
            Ids = ids;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// List of link IDs in desired order
        /// </summary>
        /// <value>List of link IDs in desired order</value>
        [JsonPropertyName("ids")]
        public List<int> Ids { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ExternalLinkReorder {\n");
            sb.Append("  Ids: ").Append(Ids).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="ExternalLinkReorder" />
    /// </summary>
    public class ExternalLinkReorderJsonConverter : JsonConverter<ExternalLinkReorder>
    {
        /// <summary>
        /// Deserializes json to <see cref="ExternalLinkReorder" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override ExternalLinkReorder Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<List<int>?> ids = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "ids":
                            ids = new Option<List<int>?>(JsonSerializer.Deserialize<List<int>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!ids.IsSet)
                throw new ArgumentException("Property is required for class ExternalLinkReorder.", nameof(ids));

            if (ids.IsSet && ids.Value == null)
                throw new ArgumentNullException(nameof(ids), "Property is not nullable for class ExternalLinkReorder.");

            return new ExternalLinkReorder(ids.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="ExternalLinkReorder" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="externalLinkReorder"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, ExternalLinkReorder externalLinkReorder, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, externalLinkReorder, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="ExternalLinkReorder" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="externalLinkReorder"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, ExternalLinkReorder externalLinkReorder, JsonSerializerOptions jsonSerializerOptions)
        {
            if (externalLinkReorder.Ids == null)
                throw new ArgumentNullException(nameof(externalLinkReorder.Ids), "Property is required for class ExternalLinkReorder.");

            writer.WritePropertyName("ids");
            JsonSerializer.Serialize(writer, externalLinkReorder.Ids, jsonSerializerOptions);
        }
    }
}
