// <auto-generated>
/*
 * Bambuddy
 *
 * Archive and manage Bambu Lab 3MF files
 *
 * The version of the OpenAPI document: 0.2.4.5
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Bambuddy.Api.Client;

namespace Bambuddy.Api.Model
{
    /// <summary>
    /// Schema for linking an external folder.
    /// </summary>
    public partial class ExternalFolderCreate : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ExternalFolderCreate" /> class.
        /// </summary>
        /// <param name="name">name</param>
        /// <param name="externalPath">externalPath</param>
        /// <param name="readonly">readonly (default to true)</param>
        /// <param name="showHidden">showHidden (default to false)</param>
        /// <param name="parentId">parentId</param>
        [JsonConstructor]
        public ExternalFolderCreate(string name, string externalPath, Option<bool?> @readonly = default, Option<bool?> showHidden = default, Option<int?> parentId = default)
        {
            Name = name;
            ExternalPath = externalPath;
            ReadonlyOption = @readonly;
            ShowHiddenOption = showHidden;
            ParentIdOption = parentId;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [JsonPropertyName("name")]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets ExternalPath
        /// </summary>
        [JsonPropertyName("external_path")]
        public string ExternalPath { get; set; }

        /// <summary>
        /// Used to track the state of Readonly
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> ReadonlyOption { get; private set; }

        /// <summary>
        /// Gets or Sets Readonly
        /// </summary>
        [JsonPropertyName("readonly")]
        public bool? Readonly { get { return this.ReadonlyOption.Value; } set { this.ReadonlyOption = new(value); } }

        /// <summary>
        /// Used to track the state of ShowHidden
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> ShowHiddenOption { get; private set; }

        /// <summary>
        /// Gets or Sets ShowHidden
        /// </summary>
        [JsonPropertyName("show_hidden")]
        public bool? ShowHidden { get { return this.ShowHiddenOption.Value; } set { this.ShowHiddenOption = new(value); } }

        /// <summary>
        /// Used to track the state of ParentId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> ParentIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets ParentId
        /// </summary>
        [JsonPropertyName("parent_id")]
        public int? ParentId { get { return this.ParentIdOption.Value; } set { this.ParentIdOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ExternalFolderCreate {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  ExternalPath: ").Append(ExternalPath).Append("\n");
            sb.Append("  Readonly: ").Append(Readonly).Append("\n");
            sb.Append("  ShowHidden: ").Append(ShowHidden).Append("\n");
            sb.Append("  ParentId: ").Append(ParentId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Name (string) maxLength
            if (this.Name != null && this.Name.Length > 255)
            {
                yield return new ValidationResult("Invalid value for Name, length must be less than 255.", new [] { "Name" });
            }

            // Name (string) minLength
            if (this.Name != null && this.Name.Length < 1)
            {
                yield return new ValidationResult("Invalid value for Name, length must be greater than 1.", new [] { "Name" });
            }

            // ExternalPath (string) maxLength
            if (this.ExternalPath != null && this.ExternalPath.Length > 500)
            {
                yield return new ValidationResult("Invalid value for ExternalPath, length must be less than 500.", new [] { "ExternalPath" });
            }

            // ExternalPath (string) minLength
            if (this.ExternalPath != null && this.ExternalPath.Length < 1)
            {
                yield return new ValidationResult("Invalid value for ExternalPath, length must be greater than 1.", new [] { "ExternalPath" });
            }

            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="ExternalFolderCreate" />
    /// </summary>
    public class ExternalFolderCreateJsonConverter : JsonConverter<ExternalFolderCreate>
    {
        /// <summary>
        /// Deserializes json to <see cref="ExternalFolderCreate" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override ExternalFolderCreate Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> name = default;
            Option<string?> externalPath = default;
            Option<bool?> varReadonly = default;
            Option<bool?> showHidden = default;
            Option<int?> parentId = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "name":
                            name = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "external_path":
                            externalPath = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "readonly":
                            varReadonly = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "show_hidden":
                            showHidden = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "parent_id":
                            parentId = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!name.IsSet)
                throw new ArgumentException("Property is required for class ExternalFolderCreate.", nameof(name));

            if (!externalPath.IsSet)
                throw new ArgumentException("Property is required for class ExternalFolderCreate.", nameof(externalPath));

            if (name.IsSet && name.Value == null)
                throw new ArgumentNullException(nameof(name), "Property is not nullable for class ExternalFolderCreate.");

            if (externalPath.IsSet && externalPath.Value == null)
                throw new ArgumentNullException(nameof(externalPath), "Property is not nullable for class ExternalFolderCreate.");

            if (varReadonly.IsSet && varReadonly.Value == null)
                throw new ArgumentNullException(nameof(varReadonly), "Property is not nullable for class ExternalFolderCreate.");

            if (showHidden.IsSet && showHidden.Value == null)
                throw new ArgumentNullException(nameof(showHidden), "Property is not nullable for class ExternalFolderCreate.");

            return new ExternalFolderCreate(name.Value!, externalPath.Value!, varReadonly, showHidden, parentId);
        }

        /// <summary>
        /// Serializes a <see cref="ExternalFolderCreate" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="externalFolderCreate"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, ExternalFolderCreate externalFolderCreate, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, externalFolderCreate, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="ExternalFolderCreate" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="externalFolderCreate"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, ExternalFolderCreate externalFolderCreate, JsonSerializerOptions jsonSerializerOptions)
        {
            if (externalFolderCreate.Name == null)
                throw new ArgumentNullException(nameof(externalFolderCreate.Name), "Property is required for class ExternalFolderCreate.");

            if (externalFolderCreate.ExternalPath == null)
                throw new ArgumentNullException(nameof(externalFolderCreate.ExternalPath), "Property is required for class ExternalFolderCreate.");

            writer.WriteString("name", externalFolderCreate.Name);

            writer.WriteString("external_path", externalFolderCreate.ExternalPath);

            if (externalFolderCreate.ReadonlyOption.IsSet)
                writer.WriteBoolean("readonly", externalFolderCreate.ReadonlyOption.Value!.Value);

            if (externalFolderCreate.ShowHiddenOption.IsSet)
                writer.WriteBoolean("show_hidden", externalFolderCreate.ShowHiddenOption.Value!.Value);

            if (externalFolderCreate.ParentIdOption.IsSet)
                if (externalFolderCreate.ParentIdOption.Value != null)
                    writer.WriteNumber("parent_id", externalFolderCreate.ParentIdOption.Value!.Value);
                else
                    writer.WriteNull("parent_id");
        }
    }
}
