// <auto-generated>
/*
 * Bambuddy
 *
 * Archive and manage Bambu Lab 3MF files
 *
 * The version of the OpenAPI document: 0.2.4.5
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Bambuddy.Api.Client;

namespace Bambuddy.Api.Model
{
    /// <summary>
    /// A Home Assistant entity that can be used as a smart plug.
    /// </summary>
    public partial class HAEntity : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="HAEntity" /> class.
        /// </summary>
        /// <param name="entityId">entityId</param>
        /// <param name="friendlyName">friendlyName</param>
        /// <param name="domain">domain</param>
        /// <param name="state">state</param>
        [JsonConstructor]
        public HAEntity(string entityId, string friendlyName, string domain, Option<string?> state = default)
        {
            EntityId = entityId;
            FriendlyName = friendlyName;
            Domain = domain;
            StateOption = state;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets EntityId
        /// </summary>
        [JsonPropertyName("entity_id")]
        public string EntityId { get; set; }

        /// <summary>
        /// Gets or Sets FriendlyName
        /// </summary>
        [JsonPropertyName("friendly_name")]
        public string FriendlyName { get; set; }

        /// <summary>
        /// Gets or Sets Domain
        /// </summary>
        [JsonPropertyName("domain")]
        public string Domain { get; set; }

        /// <summary>
        /// Used to track the state of State
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> StateOption { get; private set; }

        /// <summary>
        /// Gets or Sets State
        /// </summary>
        [JsonPropertyName("state")]
        public string? State { get { return this.StateOption.Value; } set { this.StateOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class HAEntity {\n");
            sb.Append("  EntityId: ").Append(EntityId).Append("\n");
            sb.Append("  FriendlyName: ").Append(FriendlyName).Append("\n");
            sb.Append("  Domain: ").Append(Domain).Append("\n");
            sb.Append("  State: ").Append(State).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="HAEntity" />
    /// </summary>
    public class HAEntityJsonConverter : JsonConverter<HAEntity>
    {
        /// <summary>
        /// Deserializes json to <see cref="HAEntity" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override HAEntity Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> entityId = default;
            Option<string?> friendlyName = default;
            Option<string?> domain = default;
            Option<string?> state = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "entity_id":
                            entityId = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "friendly_name":
                            friendlyName = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "domain":
                            domain = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "state":
                            state = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!entityId.IsSet)
                throw new ArgumentException("Property is required for class HAEntity.", nameof(entityId));

            if (!friendlyName.IsSet)
                throw new ArgumentException("Property is required for class HAEntity.", nameof(friendlyName));

            if (!domain.IsSet)
                throw new ArgumentException("Property is required for class HAEntity.", nameof(domain));

            if (entityId.IsSet && entityId.Value == null)
                throw new ArgumentNullException(nameof(entityId), "Property is not nullable for class HAEntity.");

            if (friendlyName.IsSet && friendlyName.Value == null)
                throw new ArgumentNullException(nameof(friendlyName), "Property is not nullable for class HAEntity.");

            if (domain.IsSet && domain.Value == null)
                throw new ArgumentNullException(nameof(domain), "Property is not nullable for class HAEntity.");

            return new HAEntity(entityId.Value!, friendlyName.Value!, domain.Value!, state);
        }

        /// <summary>
        /// Serializes a <see cref="HAEntity" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="hAEntity"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, HAEntity hAEntity, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, hAEntity, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="HAEntity" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="hAEntity"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, HAEntity hAEntity, JsonSerializerOptions jsonSerializerOptions)
        {
            if (hAEntity.EntityId == null)
                throw new ArgumentNullException(nameof(hAEntity.EntityId), "Property is required for class HAEntity.");

            if (hAEntity.FriendlyName == null)
                throw new ArgumentNullException(nameof(hAEntity.FriendlyName), "Property is required for class HAEntity.");

            if (hAEntity.Domain == null)
                throw new ArgumentNullException(nameof(hAEntity.Domain), "Property is required for class HAEntity.");

            writer.WriteString("entity_id", hAEntity.EntityId);

            writer.WriteString("friendly_name", hAEntity.FriendlyName);

            writer.WriteString("domain", hAEntity.Domain);

            if (hAEntity.StateOption.IsSet)
                if (hAEntity.StateOption.Value != null)
                    writer.WriteString("state", hAEntity.State);
                else
                    writer.WriteNull("state");
        }
    }
}
