// <auto-generated>
/*
 * Bambuddy
 *
 * Archive and manage Bambu Lab 3MF files
 *
 * The version of the OpenAPI document: 0.2.4.5
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Bambuddy.Api.Client;

namespace Bambuddy.Api.Model
{
    /// <summary>
    /// Body for POST /makerworld/import.
    /// </summary>
    public partial class MakerWorldImportRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MakerWorldImportRequest" /> class.
        /// </summary>
        /// <param name="modelId">The MakerWorld design ID (the number in /models/{id}).</param>
        /// <param name="profileId">The profileId of the selected instance (plate configuration). Each instance in &#x60;/design/{id}/instances&#x60; carries a &#x60;profileId&#x60; field — the frontend forwards the picked one here. If omitted, the backend falls back to the first available instance of the model.</param>
        /// <param name="instanceId">Retained for backwards compatibility; no longer used by the download flow.</param>
        /// <param name="folderId">Target library folder; null &#x3D; root</param>
        [JsonConstructor]
        public MakerWorldImportRequest(int modelId, Option<int?> profileId = default, Option<int?> instanceId = default, Option<int?> folderId = default)
        {
            ModelId = modelId;
            ProfileIdOption = profileId;
            InstanceIdOption = instanceId;
            FolderIdOption = folderId;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// The MakerWorld design ID (the number in /models/{id}).
        /// </summary>
        /// <value>The MakerWorld design ID (the number in /models/{id}).</value>
        [JsonPropertyName("model_id")]
        public int ModelId { get; set; }

        /// <summary>
        /// Used to track the state of ProfileId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> ProfileIdOption { get; private set; }

        /// <summary>
        /// The profileId of the selected instance (plate configuration). Each instance in &#x60;/design/{id}/instances&#x60; carries a &#x60;profileId&#x60; field — the frontend forwards the picked one here. If omitted, the backend falls back to the first available instance of the model.
        /// </summary>
        /// <value>The profileId of the selected instance (plate configuration). Each instance in &#x60;/design/{id}/instances&#x60; carries a &#x60;profileId&#x60; field — the frontend forwards the picked one here. If omitted, the backend falls back to the first available instance of the model.</value>
        [JsonPropertyName("profile_id")]
        public int? ProfileId { get { return this.ProfileIdOption.Value; } set { this.ProfileIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of InstanceId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> InstanceIdOption { get; private set; }

        /// <summary>
        /// Retained for backwards compatibility; no longer used by the download flow.
        /// </summary>
        /// <value>Retained for backwards compatibility; no longer used by the download flow.</value>
        [JsonPropertyName("instance_id")]
        public int? InstanceId { get { return this.InstanceIdOption.Value; } set { this.InstanceIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of FolderId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> FolderIdOption { get; private set; }

        /// <summary>
        /// Target library folder; null &#x3D; root
        /// </summary>
        /// <value>Target library folder; null &#x3D; root</value>
        [JsonPropertyName("folder_id")]
        public int? FolderId { get { return this.FolderIdOption.Value; } set { this.FolderIdOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class MakerWorldImportRequest {\n");
            sb.Append("  ModelId: ").Append(ModelId).Append("\n");
            sb.Append("  ProfileId: ").Append(ProfileId).Append("\n");
            sb.Append("  InstanceId: ").Append(InstanceId).Append("\n");
            sb.Append("  FolderId: ").Append(FolderId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="MakerWorldImportRequest" />
    /// </summary>
    public class MakerWorldImportRequestJsonConverter : JsonConverter<MakerWorldImportRequest>
    {
        /// <summary>
        /// Deserializes json to <see cref="MakerWorldImportRequest" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override MakerWorldImportRequest Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<int?> modelId = default;
            Option<int?> profileId = default;
            Option<int?> instanceId = default;
            Option<int?> folderId = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "model_id":
                            modelId = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "profile_id":
                            profileId = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "instance_id":
                            instanceId = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "folder_id":
                            folderId = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!modelId.IsSet)
                throw new ArgumentException("Property is required for class MakerWorldImportRequest.", nameof(modelId));

            if (modelId.IsSet && modelId.Value == null)
                throw new ArgumentNullException(nameof(modelId), "Property is not nullable for class MakerWorldImportRequest.");

            return new MakerWorldImportRequest(modelId.Value!.Value!, profileId, instanceId, folderId);
        }

        /// <summary>
        /// Serializes a <see cref="MakerWorldImportRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="makerWorldImportRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, MakerWorldImportRequest makerWorldImportRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, makerWorldImportRequest, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="MakerWorldImportRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="makerWorldImportRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, MakerWorldImportRequest makerWorldImportRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteNumber("model_id", makerWorldImportRequest.ModelId);

            if (makerWorldImportRequest.ProfileIdOption.IsSet)
                if (makerWorldImportRequest.ProfileIdOption.Value != null)
                    writer.WriteNumber("profile_id", makerWorldImportRequest.ProfileIdOption.Value!.Value);
                else
                    writer.WriteNull("profile_id");

            if (makerWorldImportRequest.InstanceIdOption.IsSet)
                if (makerWorldImportRequest.InstanceIdOption.Value != null)
                    writer.WriteNumber("instance_id", makerWorldImportRequest.InstanceIdOption.Value!.Value);
                else
                    writer.WriteNull("instance_id");

            if (makerWorldImportRequest.FolderIdOption.IsSet)
                if (makerWorldImportRequest.FolderIdOption.Value != null)
                    writer.WriteNumber("folder_id", makerWorldImportRequest.FolderIdOption.Value!.Value);
                else
                    writer.WriteNull("folder_id");
        }
    }
}
