// <auto-generated>
/*
 * Bambuddy
 *
 * Archive and manage Bambu Lab 3MF files
 *
 * The version of the OpenAPI document: 0.2.4.5
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Bambuddy.Api.Client;

namespace Bambuddy.Api.Model
{
    /// <summary>
    /// Submitted by the frontend after the user pastes the callback URL from their browser. The URL contains a Supabase &#x60;&#x60;code&#x60;&#x60; (and our &#x60;&#x60;state&#x60;&#x60;) that we exchange for tokens.
    /// </summary>
    public partial class OrcaAuthFinishRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="OrcaAuthFinishRequest" /> class.
        /// </summary>
        /// <param name="callbackUrl">The full URL the browser was redirected to after sign-in</param>
        [JsonConstructor]
        public OrcaAuthFinishRequest(string callbackUrl)
        {
            CallbackUrl = callbackUrl;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// The full URL the browser was redirected to after sign-in
        /// </summary>
        /// <value>The full URL the browser was redirected to after sign-in</value>
        [JsonPropertyName("callback_url")]
        public string CallbackUrl { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class OrcaAuthFinishRequest {\n");
            sb.Append("  CallbackUrl: ").Append(CallbackUrl).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="OrcaAuthFinishRequest" />
    /// </summary>
    public class OrcaAuthFinishRequestJsonConverter : JsonConverter<OrcaAuthFinishRequest>
    {
        /// <summary>
        /// Deserializes json to <see cref="OrcaAuthFinishRequest" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override OrcaAuthFinishRequest Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> callbackUrl = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "callback_url":
                            callbackUrl = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!callbackUrl.IsSet)
                throw new ArgumentException("Property is required for class OrcaAuthFinishRequest.", nameof(callbackUrl));

            if (callbackUrl.IsSet && callbackUrl.Value == null)
                throw new ArgumentNullException(nameof(callbackUrl), "Property is not nullable for class OrcaAuthFinishRequest.");

            return new OrcaAuthFinishRequest(callbackUrl.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="OrcaAuthFinishRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="orcaAuthFinishRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, OrcaAuthFinishRequest orcaAuthFinishRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, orcaAuthFinishRequest, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="OrcaAuthFinishRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="orcaAuthFinishRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, OrcaAuthFinishRequest orcaAuthFinishRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            if (orcaAuthFinishRequest.CallbackUrl == null)
                throw new ArgumentNullException(nameof(orcaAuthFinishRequest.CallbackUrl), "Property is required for class OrcaAuthFinishRequest.");

            writer.WriteString("callback_url", orcaAuthFinishRequest.CallbackUrl);
        }
    }
}
