// <auto-generated>
/*
 * Bambuddy
 *
 * Archive and manage Bambu Lab 3MF files
 *
 * The version of the OpenAPI document: 0.2.4.5
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Bambuddy.Api.Client;

namespace Bambuddy.Api.Model
{
    /// <summary>
    /// Response for a print batch with progress stats.
    /// </summary>
    public partial class PrintBatchResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PrintBatchResponse" /> class.
        /// </summary>
        /// <param name="id">id</param>
        /// <param name="name">name</param>
        /// <param name="quantity">quantity</param>
        /// <param name="status">status</param>
        /// <param name="archiveId">archiveId</param>
        /// <param name="libraryFileId">libraryFileId</param>
        /// <param name="createdAt">createdAt</param>
        /// <param name="createdById">createdById</param>
        /// <param name="createdByUsername">createdByUsername</param>
        /// <param name="pendingCount">pendingCount (default to 0)</param>
        /// <param name="printingCount">printingCount (default to 0)</param>
        /// <param name="completedCount">completedCount (default to 0)</param>
        /// <param name="failedCount">failedCount (default to 0)</param>
        /// <param name="cancelledCount">cancelledCount (default to 0)</param>
        [JsonConstructor]
        public PrintBatchResponse(int id, string name, int quantity, string status, Option<int?> archiveId = default, Option<int?> libraryFileId = default, string? createdAt = default, Option<int?> createdById = default, Option<string?> createdByUsername = default, Option<int?> pendingCount = default, Option<int?> printingCount = default, Option<int?> completedCount = default, Option<int?> failedCount = default, Option<int?> cancelledCount = default)
        {
            Id = id;
            Name = name;
            Quantity = quantity;
            Status = status;
            ArchiveIdOption = archiveId;
            LibraryFileIdOption = libraryFileId;
            CreatedAt = createdAt;
            CreatedByIdOption = createdById;
            CreatedByUsernameOption = createdByUsername;
            PendingCountOption = pendingCount;
            PrintingCountOption = printingCount;
            CompletedCountOption = completedCount;
            FailedCountOption = failedCount;
            CancelledCountOption = cancelledCount;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [JsonPropertyName("id")]
        public int Id { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [JsonPropertyName("name")]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets Quantity
        /// </summary>
        [JsonPropertyName("quantity")]
        public int Quantity { get; set; }

        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [JsonPropertyName("status")]
        public string Status { get; set; }

        /// <summary>
        /// Used to track the state of ArchiveId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> ArchiveIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets ArchiveId
        /// </summary>
        [JsonPropertyName("archive_id")]
        public int? ArchiveId { get { return this.ArchiveIdOption.Value; } set { this.ArchiveIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of LibraryFileId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> LibraryFileIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets LibraryFileId
        /// </summary>
        [JsonPropertyName("library_file_id")]
        public int? LibraryFileId { get { return this.LibraryFileIdOption.Value; } set { this.LibraryFileIdOption = new(value); } }

        /// <summary>
        /// Gets or Sets CreatedAt
        /// </summary>
        [JsonPropertyName("created_at")]
        public string? CreatedAt { get; set; }

        /// <summary>
        /// Used to track the state of CreatedById
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> CreatedByIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets CreatedById
        /// </summary>
        [JsonPropertyName("created_by_id")]
        public int? CreatedById { get { return this.CreatedByIdOption.Value; } set { this.CreatedByIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of CreatedByUsername
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> CreatedByUsernameOption { get; private set; }

        /// <summary>
        /// Gets or Sets CreatedByUsername
        /// </summary>
        [JsonPropertyName("created_by_username")]
        public string? CreatedByUsername { get { return this.CreatedByUsernameOption.Value; } set { this.CreatedByUsernameOption = new(value); } }

        /// <summary>
        /// Used to track the state of PendingCount
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> PendingCountOption { get; private set; }

        /// <summary>
        /// Gets or Sets PendingCount
        /// </summary>
        [JsonPropertyName("pending_count")]
        public int? PendingCount { get { return this.PendingCountOption.Value; } set { this.PendingCountOption = new(value); } }

        /// <summary>
        /// Used to track the state of PrintingCount
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> PrintingCountOption { get; private set; }

        /// <summary>
        /// Gets or Sets PrintingCount
        /// </summary>
        [JsonPropertyName("printing_count")]
        public int? PrintingCount { get { return this.PrintingCountOption.Value; } set { this.PrintingCountOption = new(value); } }

        /// <summary>
        /// Used to track the state of CompletedCount
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> CompletedCountOption { get; private set; }

        /// <summary>
        /// Gets or Sets CompletedCount
        /// </summary>
        [JsonPropertyName("completed_count")]
        public int? CompletedCount { get { return this.CompletedCountOption.Value; } set { this.CompletedCountOption = new(value); } }

        /// <summary>
        /// Used to track the state of FailedCount
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> FailedCountOption { get; private set; }

        /// <summary>
        /// Gets or Sets FailedCount
        /// </summary>
        [JsonPropertyName("failed_count")]
        public int? FailedCount { get { return this.FailedCountOption.Value; } set { this.FailedCountOption = new(value); } }

        /// <summary>
        /// Used to track the state of CancelledCount
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> CancelledCountOption { get; private set; }

        /// <summary>
        /// Gets or Sets CancelledCount
        /// </summary>
        [JsonPropertyName("cancelled_count")]
        public int? CancelledCount { get { return this.CancelledCountOption.Value; } set { this.CancelledCountOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PrintBatchResponse {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Quantity: ").Append(Quantity).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  ArchiveId: ").Append(ArchiveId).Append("\n");
            sb.Append("  LibraryFileId: ").Append(LibraryFileId).Append("\n");
            sb.Append("  CreatedAt: ").Append(CreatedAt).Append("\n");
            sb.Append("  CreatedById: ").Append(CreatedById).Append("\n");
            sb.Append("  CreatedByUsername: ").Append(CreatedByUsername).Append("\n");
            sb.Append("  PendingCount: ").Append(PendingCount).Append("\n");
            sb.Append("  PrintingCount: ").Append(PrintingCount).Append("\n");
            sb.Append("  CompletedCount: ").Append(CompletedCount).Append("\n");
            sb.Append("  FailedCount: ").Append(FailedCount).Append("\n");
            sb.Append("  CancelledCount: ").Append(CancelledCount).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="PrintBatchResponse" />
    /// </summary>
    public class PrintBatchResponseJsonConverter : JsonConverter<PrintBatchResponse>
    {
        /// <summary>
        /// Deserializes json to <see cref="PrintBatchResponse" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override PrintBatchResponse Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<int?> id = default;
            Option<string?> name = default;
            Option<int?> quantity = default;
            Option<string?> status = default;
            Option<int?> archiveId = default;
            Option<int?> libraryFileId = default;
            Option<string?> createdAt = default;
            Option<int?> createdById = default;
            Option<string?> createdByUsername = default;
            Option<int?> pendingCount = default;
            Option<int?> printingCount = default;
            Option<int?> completedCount = default;
            Option<int?> failedCount = default;
            Option<int?> cancelledCount = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "id":
                            id = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "name":
                            name = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "quantity":
                            quantity = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "status":
                            status = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "archive_id":
                            archiveId = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "library_file_id":
                            libraryFileId = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "created_at":
                            createdAt = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "created_by_id":
                            createdById = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "created_by_username":
                            createdByUsername = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "pending_count":
                            pendingCount = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "printing_count":
                            printingCount = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "completed_count":
                            completedCount = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "failed_count":
                            failedCount = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "cancelled_count":
                            cancelledCount = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!id.IsSet)
                throw new ArgumentException("Property is required for class PrintBatchResponse.", nameof(id));

            if (!name.IsSet)
                throw new ArgumentException("Property is required for class PrintBatchResponse.", nameof(name));

            if (!quantity.IsSet)
                throw new ArgumentException("Property is required for class PrintBatchResponse.", nameof(quantity));

            if (!status.IsSet)
                throw new ArgumentException("Property is required for class PrintBatchResponse.", nameof(status));

            if (!createdAt.IsSet)
                throw new ArgumentException("Property is required for class PrintBatchResponse.", nameof(createdAt));

            if (id.IsSet && id.Value == null)
                throw new ArgumentNullException(nameof(id), "Property is not nullable for class PrintBatchResponse.");

            if (name.IsSet && name.Value == null)
                throw new ArgumentNullException(nameof(name), "Property is not nullable for class PrintBatchResponse.");

            if (quantity.IsSet && quantity.Value == null)
                throw new ArgumentNullException(nameof(quantity), "Property is not nullable for class PrintBatchResponse.");

            if (status.IsSet && status.Value == null)
                throw new ArgumentNullException(nameof(status), "Property is not nullable for class PrintBatchResponse.");

            if (pendingCount.IsSet && pendingCount.Value == null)
                throw new ArgumentNullException(nameof(pendingCount), "Property is not nullable for class PrintBatchResponse.");

            if (printingCount.IsSet && printingCount.Value == null)
                throw new ArgumentNullException(nameof(printingCount), "Property is not nullable for class PrintBatchResponse.");

            if (completedCount.IsSet && completedCount.Value == null)
                throw new ArgumentNullException(nameof(completedCount), "Property is not nullable for class PrintBatchResponse.");

            if (failedCount.IsSet && failedCount.Value == null)
                throw new ArgumentNullException(nameof(failedCount), "Property is not nullable for class PrintBatchResponse.");

            if (cancelledCount.IsSet && cancelledCount.Value == null)
                throw new ArgumentNullException(nameof(cancelledCount), "Property is not nullable for class PrintBatchResponse.");

            return new PrintBatchResponse(id.Value!.Value!, name.Value!, quantity.Value!.Value!, status.Value!, archiveId, libraryFileId, createdAt.Value!, createdById, createdByUsername, pendingCount, printingCount, completedCount, failedCount, cancelledCount);
        }

        /// <summary>
        /// Serializes a <see cref="PrintBatchResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="printBatchResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, PrintBatchResponse printBatchResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, printBatchResponse, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="PrintBatchResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="printBatchResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, PrintBatchResponse printBatchResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            if (printBatchResponse.Name == null)
                throw new ArgumentNullException(nameof(printBatchResponse.Name), "Property is required for class PrintBatchResponse.");

            if (printBatchResponse.Status == null)
                throw new ArgumentNullException(nameof(printBatchResponse.Status), "Property is required for class PrintBatchResponse.");

            writer.WriteNumber("id", printBatchResponse.Id);

            writer.WriteString("name", printBatchResponse.Name);

            writer.WriteNumber("quantity", printBatchResponse.Quantity);

            writer.WriteString("status", printBatchResponse.Status);

            if (printBatchResponse.ArchiveIdOption.IsSet)
                if (printBatchResponse.ArchiveIdOption.Value != null)
                    writer.WriteNumber("archive_id", printBatchResponse.ArchiveIdOption.Value!.Value);
                else
                    writer.WriteNull("archive_id");

            if (printBatchResponse.LibraryFileIdOption.IsSet)
                if (printBatchResponse.LibraryFileIdOption.Value != null)
                    writer.WriteNumber("library_file_id", printBatchResponse.LibraryFileIdOption.Value!.Value);
                else
                    writer.WriteNull("library_file_id");

            if (printBatchResponse.CreatedAt != null)
                writer.WriteString("created_at", printBatchResponse.CreatedAt);
            else
                writer.WriteNull("created_at");

            if (printBatchResponse.CreatedByIdOption.IsSet)
                if (printBatchResponse.CreatedByIdOption.Value != null)
                    writer.WriteNumber("created_by_id", printBatchResponse.CreatedByIdOption.Value!.Value);
                else
                    writer.WriteNull("created_by_id");

            if (printBatchResponse.CreatedByUsernameOption.IsSet)
                if (printBatchResponse.CreatedByUsernameOption.Value != null)
                    writer.WriteString("created_by_username", printBatchResponse.CreatedByUsername);
                else
                    writer.WriteNull("created_by_username");

            if (printBatchResponse.PendingCountOption.IsSet)
                writer.WriteNumber("pending_count", printBatchResponse.PendingCountOption.Value!.Value);

            if (printBatchResponse.PrintingCountOption.IsSet)
                writer.WriteNumber("printing_count", printBatchResponse.PrintingCountOption.Value!.Value);

            if (printBatchResponse.CompletedCountOption.IsSet)
                writer.WriteNumber("completed_count", printBatchResponse.CompletedCountOption.Value!.Value);

            if (printBatchResponse.FailedCountOption.IsSet)
                writer.WriteNumber("failed_count", printBatchResponse.FailedCountOption.Value!.Value);

            if (printBatchResponse.CancelledCountOption.IsSet)
                writer.WriteNumber("cancelled_count", printBatchResponse.CancelledCountOption.Value!.Value);
        }
    }
}
