// <auto-generated>
/*
 * Bambuddy
 *
 * Archive and manage Bambu Lab 3MF files
 *
 * The version of the OpenAPI document: 0.2.4.5
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Bambuddy.Api.Client;

namespace Bambuddy.Api.Model
{
    /// <summary>
    /// PrintQueueItemCreate
    /// </summary>
    public partial class PrintQueueItemCreate : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PrintQueueItemCreate" /> class.
        /// </summary>
        /// <param name="printerId">printerId</param>
        /// <param name="targetModel">targetModel</param>
        /// <param name="targetLocation">targetLocation</param>
        /// <param name="requiredFilamentTypes">requiredFilamentTypes</param>
        /// <param name="filamentOverrides">filamentOverrides</param>
        /// <param name="archiveId">archiveId</param>
        /// <param name="libraryFileId">libraryFileId</param>
        /// <param name="scheduledTime">scheduledTime</param>
        /// <param name="requirePreviousSuccess">requirePreviousSuccess (default to false)</param>
        /// <param name="autoOffAfter">autoOffAfter (default to false)</param>
        /// <param name="manualStart">manualStart (default to false)</param>
        /// <param name="amsMapping">amsMapping</param>
        /// <param name="plateId">plateId</param>
        /// <param name="bedLevelling">bedLevelling (default to true)</param>
        /// <param name="flowCali">flowCali (default to false)</param>
        /// <param name="vibrationCali">vibrationCali (default to true)</param>
        /// <param name="layerInspect">layerInspect (default to false)</param>
        /// <param name="timelapse">timelapse (default to false)</param>
        /// <param name="useAms">useAms (default to true)</param>
        /// <param name="gcodeInjection">gcodeInjection (default to false)</param>
        /// <param name="quantity">quantity (default to 1)</param>
        /// <param name="projectId">projectId</param>
        [JsonConstructor]
        public PrintQueueItemCreate(Option<int?> printerId = default, Option<string?> targetModel = default, Option<string?> targetLocation = default, Option<List<string>?> requiredFilamentTypes = default, Option<List<Dictionary<string, Object>>?> filamentOverrides = default, Option<int?> archiveId = default, Option<int?> libraryFileId = default, Option<DateTime?> scheduledTime = default, Option<bool?> requirePreviousSuccess = default, Option<bool?> autoOffAfter = default, Option<bool?> manualStart = default, Option<List<int>?> amsMapping = default, Option<int?> plateId = default, Option<bool?> bedLevelling = default, Option<bool?> flowCali = default, Option<bool?> vibrationCali = default, Option<bool?> layerInspect = default, Option<bool?> timelapse = default, Option<bool?> useAms = default, Option<bool?> gcodeInjection = default, Option<int?> quantity = default, Option<int?> projectId = default)
        {
            PrinterIdOption = printerId;
            TargetModelOption = targetModel;
            TargetLocationOption = targetLocation;
            RequiredFilamentTypesOption = requiredFilamentTypes;
            FilamentOverridesOption = filamentOverrides;
            ArchiveIdOption = archiveId;
            LibraryFileIdOption = libraryFileId;
            ScheduledTimeOption = scheduledTime;
            RequirePreviousSuccessOption = requirePreviousSuccess;
            AutoOffAfterOption = autoOffAfter;
            ManualStartOption = manualStart;
            AmsMappingOption = amsMapping;
            PlateIdOption = plateId;
            BedLevellingOption = bedLevelling;
            FlowCaliOption = flowCali;
            VibrationCaliOption = vibrationCali;
            LayerInspectOption = layerInspect;
            TimelapseOption = timelapse;
            UseAmsOption = useAms;
            GcodeInjectionOption = gcodeInjection;
            QuantityOption = quantity;
            ProjectIdOption = projectId;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of PrinterId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> PrinterIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets PrinterId
        /// </summary>
        [JsonPropertyName("printer_id")]
        public int? PrinterId { get { return this.PrinterIdOption.Value; } set { this.PrinterIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of TargetModel
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> TargetModelOption { get; private set; }

        /// <summary>
        /// Gets or Sets TargetModel
        /// </summary>
        [JsonPropertyName("target_model")]
        public string? TargetModel { get { return this.TargetModelOption.Value; } set { this.TargetModelOption = new(value); } }

        /// <summary>
        /// Used to track the state of TargetLocation
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> TargetLocationOption { get; private set; }

        /// <summary>
        /// Gets or Sets TargetLocation
        /// </summary>
        [JsonPropertyName("target_location")]
        public string? TargetLocation { get { return this.TargetLocationOption.Value; } set { this.TargetLocationOption = new(value); } }

        /// <summary>
        /// Used to track the state of RequiredFilamentTypes
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<string>?> RequiredFilamentTypesOption { get; private set; }

        /// <summary>
        /// Gets or Sets RequiredFilamentTypes
        /// </summary>
        [JsonPropertyName("required_filament_types")]
        public List<string>? RequiredFilamentTypes { get { return this.RequiredFilamentTypesOption.Value; } set { this.RequiredFilamentTypesOption = new(value); } }

        /// <summary>
        /// Used to track the state of FilamentOverrides
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<Dictionary<string, Object>>?> FilamentOverridesOption { get; private set; }

        /// <summary>
        /// Gets or Sets FilamentOverrides
        /// </summary>
        [JsonPropertyName("filament_overrides")]
        public List<Dictionary<string, Object>>? FilamentOverrides { get { return this.FilamentOverridesOption.Value; } set { this.FilamentOverridesOption = new(value); } }

        /// <summary>
        /// Used to track the state of ArchiveId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> ArchiveIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets ArchiveId
        /// </summary>
        [JsonPropertyName("archive_id")]
        public int? ArchiveId { get { return this.ArchiveIdOption.Value; } set { this.ArchiveIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of LibraryFileId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> LibraryFileIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets LibraryFileId
        /// </summary>
        [JsonPropertyName("library_file_id")]
        public int? LibraryFileId { get { return this.LibraryFileIdOption.Value; } set { this.LibraryFileIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of ScheduledTime
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DateTime?> ScheduledTimeOption { get; private set; }

        /// <summary>
        /// Gets or Sets ScheduledTime
        /// </summary>
        [JsonPropertyName("scheduled_time")]
        public DateTime? ScheduledTime { get { return this.ScheduledTimeOption.Value; } set { this.ScheduledTimeOption = new(value); } }

        /// <summary>
        /// Used to track the state of RequirePreviousSuccess
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> RequirePreviousSuccessOption { get; private set; }

        /// <summary>
        /// Gets or Sets RequirePreviousSuccess
        /// </summary>
        [JsonPropertyName("require_previous_success")]
        public bool? RequirePreviousSuccess { get { return this.RequirePreviousSuccessOption.Value; } set { this.RequirePreviousSuccessOption = new(value); } }

        /// <summary>
        /// Used to track the state of AutoOffAfter
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> AutoOffAfterOption { get; private set; }

        /// <summary>
        /// Gets or Sets AutoOffAfter
        /// </summary>
        [JsonPropertyName("auto_off_after")]
        public bool? AutoOffAfter { get { return this.AutoOffAfterOption.Value; } set { this.AutoOffAfterOption = new(value); } }

        /// <summary>
        /// Used to track the state of ManualStart
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> ManualStartOption { get; private set; }

        /// <summary>
        /// Gets or Sets ManualStart
        /// </summary>
        [JsonPropertyName("manual_start")]
        public bool? ManualStart { get { return this.ManualStartOption.Value; } set { this.ManualStartOption = new(value); } }

        /// <summary>
        /// Used to track the state of AmsMapping
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<int>?> AmsMappingOption { get; private set; }

        /// <summary>
        /// Gets or Sets AmsMapping
        /// </summary>
        [JsonPropertyName("ams_mapping")]
        public List<int>? AmsMapping { get { return this.AmsMappingOption.Value; } set { this.AmsMappingOption = new(value); } }

        /// <summary>
        /// Used to track the state of PlateId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> PlateIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets PlateId
        /// </summary>
        [JsonPropertyName("plate_id")]
        public int? PlateId { get { return this.PlateIdOption.Value; } set { this.PlateIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of BedLevelling
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> BedLevellingOption { get; private set; }

        /// <summary>
        /// Gets or Sets BedLevelling
        /// </summary>
        [JsonPropertyName("bed_levelling")]
        public bool? BedLevelling { get { return this.BedLevellingOption.Value; } set { this.BedLevellingOption = new(value); } }

        /// <summary>
        /// Used to track the state of FlowCali
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> FlowCaliOption { get; private set; }

        /// <summary>
        /// Gets or Sets FlowCali
        /// </summary>
        [JsonPropertyName("flow_cali")]
        public bool? FlowCali { get { return this.FlowCaliOption.Value; } set { this.FlowCaliOption = new(value); } }

        /// <summary>
        /// Used to track the state of VibrationCali
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> VibrationCaliOption { get; private set; }

        /// <summary>
        /// Gets or Sets VibrationCali
        /// </summary>
        [JsonPropertyName("vibration_cali")]
        public bool? VibrationCali { get { return this.VibrationCaliOption.Value; } set { this.VibrationCaliOption = new(value); } }

        /// <summary>
        /// Used to track the state of LayerInspect
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> LayerInspectOption { get; private set; }

        /// <summary>
        /// Gets or Sets LayerInspect
        /// </summary>
        [JsonPropertyName("layer_inspect")]
        public bool? LayerInspect { get { return this.LayerInspectOption.Value; } set { this.LayerInspectOption = new(value); } }

        /// <summary>
        /// Used to track the state of Timelapse
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> TimelapseOption { get; private set; }

        /// <summary>
        /// Gets or Sets Timelapse
        /// </summary>
        [JsonPropertyName("timelapse")]
        public bool? Timelapse { get { return this.TimelapseOption.Value; } set { this.TimelapseOption = new(value); } }

        /// <summary>
        /// Used to track the state of UseAms
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> UseAmsOption { get; private set; }

        /// <summary>
        /// Gets or Sets UseAms
        /// </summary>
        [JsonPropertyName("use_ams")]
        public bool? UseAms { get { return this.UseAmsOption.Value; } set { this.UseAmsOption = new(value); } }

        /// <summary>
        /// Used to track the state of GcodeInjection
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> GcodeInjectionOption { get; private set; }

        /// <summary>
        /// Gets or Sets GcodeInjection
        /// </summary>
        [JsonPropertyName("gcode_injection")]
        public bool? GcodeInjection { get { return this.GcodeInjectionOption.Value; } set { this.GcodeInjectionOption = new(value); } }

        /// <summary>
        /// Used to track the state of Quantity
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> QuantityOption { get; private set; }

        /// <summary>
        /// Gets or Sets Quantity
        /// </summary>
        [JsonPropertyName("quantity")]
        public int? Quantity { get { return this.QuantityOption.Value; } set { this.QuantityOption = new(value); } }

        /// <summary>
        /// Used to track the state of ProjectId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> ProjectIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets ProjectId
        /// </summary>
        [JsonPropertyName("project_id")]
        public int? ProjectId { get { return this.ProjectIdOption.Value; } set { this.ProjectIdOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PrintQueueItemCreate {\n");
            sb.Append("  PrinterId: ").Append(PrinterId).Append("\n");
            sb.Append("  TargetModel: ").Append(TargetModel).Append("\n");
            sb.Append("  TargetLocation: ").Append(TargetLocation).Append("\n");
            sb.Append("  RequiredFilamentTypes: ").Append(RequiredFilamentTypes).Append("\n");
            sb.Append("  FilamentOverrides: ").Append(FilamentOverrides).Append("\n");
            sb.Append("  ArchiveId: ").Append(ArchiveId).Append("\n");
            sb.Append("  LibraryFileId: ").Append(LibraryFileId).Append("\n");
            sb.Append("  ScheduledTime: ").Append(ScheduledTime).Append("\n");
            sb.Append("  RequirePreviousSuccess: ").Append(RequirePreviousSuccess).Append("\n");
            sb.Append("  AutoOffAfter: ").Append(AutoOffAfter).Append("\n");
            sb.Append("  ManualStart: ").Append(ManualStart).Append("\n");
            sb.Append("  AmsMapping: ").Append(AmsMapping).Append("\n");
            sb.Append("  PlateId: ").Append(PlateId).Append("\n");
            sb.Append("  BedLevelling: ").Append(BedLevelling).Append("\n");
            sb.Append("  FlowCali: ").Append(FlowCali).Append("\n");
            sb.Append("  VibrationCali: ").Append(VibrationCali).Append("\n");
            sb.Append("  LayerInspect: ").Append(LayerInspect).Append("\n");
            sb.Append("  Timelapse: ").Append(Timelapse).Append("\n");
            sb.Append("  UseAms: ").Append(UseAms).Append("\n");
            sb.Append("  GcodeInjection: ").Append(GcodeInjection).Append("\n");
            sb.Append("  Quantity: ").Append(Quantity).Append("\n");
            sb.Append("  ProjectId: ").Append(ProjectId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="PrintQueueItemCreate" />
    /// </summary>
    public class PrintQueueItemCreateJsonConverter : JsonConverter<PrintQueueItemCreate>
    {
        /// <summary>
        /// The format to use to serialize ScheduledTime
        /// </summary>
        public static string ScheduledTimeFormat { get; set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// Deserializes json to <see cref="PrintQueueItemCreate" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override PrintQueueItemCreate Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<int?> printerId = default;
            Option<string?> targetModel = default;
            Option<string?> targetLocation = default;
            Option<List<string>?> requiredFilamentTypes = default;
            Option<List<Dictionary<string, Object>>?> filamentOverrides = default;
            Option<int?> archiveId = default;
            Option<int?> libraryFileId = default;
            Option<DateTime?> scheduledTime = default;
            Option<bool?> requirePreviousSuccess = default;
            Option<bool?> autoOffAfter = default;
            Option<bool?> manualStart = default;
            Option<List<int>?> amsMapping = default;
            Option<int?> plateId = default;
            Option<bool?> bedLevelling = default;
            Option<bool?> flowCali = default;
            Option<bool?> vibrationCali = default;
            Option<bool?> layerInspect = default;
            Option<bool?> timelapse = default;
            Option<bool?> useAms = default;
            Option<bool?> gcodeInjection = default;
            Option<int?> quantity = default;
            Option<int?> projectId = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "printer_id":
                            printerId = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "target_model":
                            targetModel = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "target_location":
                            targetLocation = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "required_filament_types":
                            requiredFilamentTypes = new Option<List<string>?>(JsonSerializer.Deserialize<List<string>>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "filament_overrides":
                            filamentOverrides = new Option<List<Dictionary<string, Object>>?>(JsonSerializer.Deserialize<List<Dictionary<string, Object>>>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "archive_id":
                            archiveId = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "library_file_id":
                            libraryFileId = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "scheduled_time":
                            scheduledTime = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime?>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "require_previous_success":
                            requirePreviousSuccess = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "auto_off_after":
                            autoOffAfter = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "manual_start":
                            manualStart = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "ams_mapping":
                            amsMapping = new Option<List<int>?>(JsonSerializer.Deserialize<List<int>>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "plate_id":
                            plateId = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "bed_levelling":
                            bedLevelling = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "flow_cali":
                            flowCali = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "vibration_cali":
                            vibrationCali = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "layer_inspect":
                            layerInspect = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "timelapse":
                            timelapse = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "use_ams":
                            useAms = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "gcode_injection":
                            gcodeInjection = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "quantity":
                            quantity = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "project_id":
                            projectId = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (requirePreviousSuccess.IsSet && requirePreviousSuccess.Value == null)
                throw new ArgumentNullException(nameof(requirePreviousSuccess), "Property is not nullable for class PrintQueueItemCreate.");

            if (autoOffAfter.IsSet && autoOffAfter.Value == null)
                throw new ArgumentNullException(nameof(autoOffAfter), "Property is not nullable for class PrintQueueItemCreate.");

            if (manualStart.IsSet && manualStart.Value == null)
                throw new ArgumentNullException(nameof(manualStart), "Property is not nullable for class PrintQueueItemCreate.");

            if (bedLevelling.IsSet && bedLevelling.Value == null)
                throw new ArgumentNullException(nameof(bedLevelling), "Property is not nullable for class PrintQueueItemCreate.");

            if (flowCali.IsSet && flowCali.Value == null)
                throw new ArgumentNullException(nameof(flowCali), "Property is not nullable for class PrintQueueItemCreate.");

            if (vibrationCali.IsSet && vibrationCali.Value == null)
                throw new ArgumentNullException(nameof(vibrationCali), "Property is not nullable for class PrintQueueItemCreate.");

            if (layerInspect.IsSet && layerInspect.Value == null)
                throw new ArgumentNullException(nameof(layerInspect), "Property is not nullable for class PrintQueueItemCreate.");

            if (timelapse.IsSet && timelapse.Value == null)
                throw new ArgumentNullException(nameof(timelapse), "Property is not nullable for class PrintQueueItemCreate.");

            if (useAms.IsSet && useAms.Value == null)
                throw new ArgumentNullException(nameof(useAms), "Property is not nullable for class PrintQueueItemCreate.");

            if (gcodeInjection.IsSet && gcodeInjection.Value == null)
                throw new ArgumentNullException(nameof(gcodeInjection), "Property is not nullable for class PrintQueueItemCreate.");

            if (quantity.IsSet && quantity.Value == null)
                throw new ArgumentNullException(nameof(quantity), "Property is not nullable for class PrintQueueItemCreate.");

            return new PrintQueueItemCreate(printerId, targetModel, targetLocation, requiredFilamentTypes, filamentOverrides, archiveId, libraryFileId, scheduledTime, requirePreviousSuccess, autoOffAfter, manualStart, amsMapping, plateId, bedLevelling, flowCali, vibrationCali, layerInspect, timelapse, useAms, gcodeInjection, quantity, projectId);
        }

        /// <summary>
        /// Serializes a <see cref="PrintQueueItemCreate" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="printQueueItemCreate"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, PrintQueueItemCreate printQueueItemCreate, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, printQueueItemCreate, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="PrintQueueItemCreate" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="printQueueItemCreate"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, PrintQueueItemCreate printQueueItemCreate, JsonSerializerOptions jsonSerializerOptions)
        {
            if (printQueueItemCreate.PrinterIdOption.IsSet)
                if (printQueueItemCreate.PrinterIdOption.Value != null)
                    writer.WriteNumber("printer_id", printQueueItemCreate.PrinterIdOption.Value!.Value);
                else
                    writer.WriteNull("printer_id");

            if (printQueueItemCreate.TargetModelOption.IsSet)
                if (printQueueItemCreate.TargetModelOption.Value != null)
                    writer.WriteString("target_model", printQueueItemCreate.TargetModel);
                else
                    writer.WriteNull("target_model");

            if (printQueueItemCreate.TargetLocationOption.IsSet)
                if (printQueueItemCreate.TargetLocationOption.Value != null)
                    writer.WriteString("target_location", printQueueItemCreate.TargetLocation);
                else
                    writer.WriteNull("target_location");

            if (printQueueItemCreate.RequiredFilamentTypesOption.IsSet)
                if (printQueueItemCreate.RequiredFilamentTypesOption.Value != null)
                {
                    writer.WritePropertyName("required_filament_types");
                    JsonSerializer.Serialize(writer, printQueueItemCreate.RequiredFilamentTypes, jsonSerializerOptions);
                }
                else
                    writer.WriteNull("required_filament_types");
            if (printQueueItemCreate.FilamentOverridesOption.IsSet)
                if (printQueueItemCreate.FilamentOverridesOption.Value != null)
                {
                    writer.WritePropertyName("filament_overrides");
                    JsonSerializer.Serialize(writer, printQueueItemCreate.FilamentOverrides, jsonSerializerOptions);
                }
                else
                    writer.WriteNull("filament_overrides");
            if (printQueueItemCreate.ArchiveIdOption.IsSet)
                if (printQueueItemCreate.ArchiveIdOption.Value != null)
                    writer.WriteNumber("archive_id", printQueueItemCreate.ArchiveIdOption.Value!.Value);
                else
                    writer.WriteNull("archive_id");

            if (printQueueItemCreate.LibraryFileIdOption.IsSet)
                if (printQueueItemCreate.LibraryFileIdOption.Value != null)
                    writer.WriteNumber("library_file_id", printQueueItemCreate.LibraryFileIdOption.Value!.Value);
                else
                    writer.WriteNull("library_file_id");

            if (printQueueItemCreate.ScheduledTimeOption.IsSet)
                if (printQueueItemCreate.ScheduledTimeOption.Value != null)
                    writer.WriteString("scheduled_time", printQueueItemCreate.ScheduledTimeOption.Value!.Value.ToString(ScheduledTimeFormat));
                else
                    writer.WriteNull("scheduled_time");

            if (printQueueItemCreate.RequirePreviousSuccessOption.IsSet)
                writer.WriteBoolean("require_previous_success", printQueueItemCreate.RequirePreviousSuccessOption.Value!.Value);

            if (printQueueItemCreate.AutoOffAfterOption.IsSet)
                writer.WriteBoolean("auto_off_after", printQueueItemCreate.AutoOffAfterOption.Value!.Value);

            if (printQueueItemCreate.ManualStartOption.IsSet)
                writer.WriteBoolean("manual_start", printQueueItemCreate.ManualStartOption.Value!.Value);

            if (printQueueItemCreate.AmsMappingOption.IsSet)
                if (printQueueItemCreate.AmsMappingOption.Value != null)
                {
                    writer.WritePropertyName("ams_mapping");
                    JsonSerializer.Serialize(writer, printQueueItemCreate.AmsMapping, jsonSerializerOptions);
                }
                else
                    writer.WriteNull("ams_mapping");
            if (printQueueItemCreate.PlateIdOption.IsSet)
                if (printQueueItemCreate.PlateIdOption.Value != null)
                    writer.WriteNumber("plate_id", printQueueItemCreate.PlateIdOption.Value!.Value);
                else
                    writer.WriteNull("plate_id");

            if (printQueueItemCreate.BedLevellingOption.IsSet)
                writer.WriteBoolean("bed_levelling", printQueueItemCreate.BedLevellingOption.Value!.Value);

            if (printQueueItemCreate.FlowCaliOption.IsSet)
                writer.WriteBoolean("flow_cali", printQueueItemCreate.FlowCaliOption.Value!.Value);

            if (printQueueItemCreate.VibrationCaliOption.IsSet)
                writer.WriteBoolean("vibration_cali", printQueueItemCreate.VibrationCaliOption.Value!.Value);

            if (printQueueItemCreate.LayerInspectOption.IsSet)
                writer.WriteBoolean("layer_inspect", printQueueItemCreate.LayerInspectOption.Value!.Value);

            if (printQueueItemCreate.TimelapseOption.IsSet)
                writer.WriteBoolean("timelapse", printQueueItemCreate.TimelapseOption.Value!.Value);

            if (printQueueItemCreate.UseAmsOption.IsSet)
                writer.WriteBoolean("use_ams", printQueueItemCreate.UseAmsOption.Value!.Value);

            if (printQueueItemCreate.GcodeInjectionOption.IsSet)
                writer.WriteBoolean("gcode_injection", printQueueItemCreate.GcodeInjectionOption.Value!.Value);

            if (printQueueItemCreate.QuantityOption.IsSet)
                writer.WriteNumber("quantity", printQueueItemCreate.QuantityOption.Value!.Value);

            if (printQueueItemCreate.ProjectIdOption.IsSet)
                if (printQueueItemCreate.ProjectIdOption.Value != null)
                    writer.WriteNumber("project_id", printQueueItemCreate.ProjectIdOption.Value!.Value);
                else
                    writer.WriteNull("project_id");
        }
    }
}
