// <auto-generated>
/*
 * Bambuddy
 *
 * Archive and manage Bambu Lab 3MF files
 *
 * The version of the OpenAPI document: 0.2.4.5
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Bambuddy.Api.Client;

namespace Bambuddy.Api.Model
{
    /// <summary>
    /// Schema for project list item (lighter weight).
    /// </summary>
    public partial class ProjectListResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ProjectListResponse" /> class.
        /// </summary>
        /// <param name="id">id</param>
        /// <param name="name">name</param>
        /// <param name="status">status</param>
        /// <param name="createdAt">createdAt</param>
        /// <param name="description">description</param>
        /// <param name="color">color</param>
        /// <param name="targetCount">targetCount</param>
        /// <param name="targetPartsCount">targetPartsCount</param>
        /// <param name="budget">budget</param>
        /// <param name="archiveCount">archiveCount (default to 0)</param>
        /// <param name="totalItems">totalItems (default to 0)</param>
        /// <param name="completedCount">completedCount (default to 0)</param>
        /// <param name="failedCount">failedCount (default to 0)</param>
        /// <param name="queueCount">queueCount (default to 0)</param>
        /// <param name="progressPercent">progressPercent</param>
        /// <param name="archives">archives</param>
        /// <param name="url">url</param>
        /// <param name="coverImageFilename">coverImageFilename</param>
        [JsonConstructor]
        public ProjectListResponse(int id, string name, string status, DateTime createdAt, string? description = default, string? color = default, int? targetCount = default, Option<int?> targetPartsCount = default, Option<decimal?> budget = default, Option<int?> archiveCount = default, Option<int?> totalItems = default, Option<int?> completedCount = default, Option<int?> failedCount = default, Option<int?> queueCount = default, Option<decimal?> progressPercent = default, Option<List<ArchivePreview>?> archives = default, Option<string?> url = default, Option<string?> coverImageFilename = default)
        {
            Id = id;
            Name = name;
            Status = status;
            CreatedAt = createdAt;
            Description = description;
            Color = color;
            TargetCount = targetCount;
            TargetPartsCountOption = targetPartsCount;
            BudgetOption = budget;
            ArchiveCountOption = archiveCount;
            TotalItemsOption = totalItems;
            CompletedCountOption = completedCount;
            FailedCountOption = failedCount;
            QueueCountOption = queueCount;
            ProgressPercentOption = progressPercent;
            ArchivesOption = archives;
            UrlOption = url;
            CoverImageFilenameOption = coverImageFilename;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [JsonPropertyName("id")]
        public int Id { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [JsonPropertyName("name")]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [JsonPropertyName("status")]
        public string Status { get; set; }

        /// <summary>
        /// Gets or Sets CreatedAt
        /// </summary>
        [JsonPropertyName("created_at")]
        public DateTime CreatedAt { get; set; }

        /// <summary>
        /// Gets or Sets Description
        /// </summary>
        [JsonPropertyName("description")]
        public string? Description { get; set; }

        /// <summary>
        /// Gets or Sets Color
        /// </summary>
        [JsonPropertyName("color")]
        public string? Color { get; set; }

        /// <summary>
        /// Gets or Sets TargetCount
        /// </summary>
        [JsonPropertyName("target_count")]
        public int? TargetCount { get; set; }

        /// <summary>
        /// Used to track the state of TargetPartsCount
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> TargetPartsCountOption { get; private set; }

        /// <summary>
        /// Gets or Sets TargetPartsCount
        /// </summary>
        [JsonPropertyName("target_parts_count")]
        public int? TargetPartsCount { get { return this.TargetPartsCountOption.Value; } set { this.TargetPartsCountOption = new(value); } }

        /// <summary>
        /// Used to track the state of Budget
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<decimal?> BudgetOption { get; private set; }

        /// <summary>
        /// Gets or Sets Budget
        /// </summary>
        [JsonPropertyName("budget")]
        public decimal? Budget { get { return this.BudgetOption.Value; } set { this.BudgetOption = new(value); } }

        /// <summary>
        /// Used to track the state of ArchiveCount
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> ArchiveCountOption { get; private set; }

        /// <summary>
        /// Gets or Sets ArchiveCount
        /// </summary>
        [JsonPropertyName("archive_count")]
        public int? ArchiveCount { get { return this.ArchiveCountOption.Value; } set { this.ArchiveCountOption = new(value); } }

        /// <summary>
        /// Used to track the state of TotalItems
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> TotalItemsOption { get; private set; }

        /// <summary>
        /// Gets or Sets TotalItems
        /// </summary>
        [JsonPropertyName("total_items")]
        public int? TotalItems { get { return this.TotalItemsOption.Value; } set { this.TotalItemsOption = new(value); } }

        /// <summary>
        /// Used to track the state of CompletedCount
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> CompletedCountOption { get; private set; }

        /// <summary>
        /// Gets or Sets CompletedCount
        /// </summary>
        [JsonPropertyName("completed_count")]
        public int? CompletedCount { get { return this.CompletedCountOption.Value; } set { this.CompletedCountOption = new(value); } }

        /// <summary>
        /// Used to track the state of FailedCount
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> FailedCountOption { get; private set; }

        /// <summary>
        /// Gets or Sets FailedCount
        /// </summary>
        [JsonPropertyName("failed_count")]
        public int? FailedCount { get { return this.FailedCountOption.Value; } set { this.FailedCountOption = new(value); } }

        /// <summary>
        /// Used to track the state of QueueCount
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> QueueCountOption { get; private set; }

        /// <summary>
        /// Gets or Sets QueueCount
        /// </summary>
        [JsonPropertyName("queue_count")]
        public int? QueueCount { get { return this.QueueCountOption.Value; } set { this.QueueCountOption = new(value); } }

        /// <summary>
        /// Used to track the state of ProgressPercent
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<decimal?> ProgressPercentOption { get; private set; }

        /// <summary>
        /// Gets or Sets ProgressPercent
        /// </summary>
        [JsonPropertyName("progress_percent")]
        public decimal? ProgressPercent { get { return this.ProgressPercentOption.Value; } set { this.ProgressPercentOption = new(value); } }

        /// <summary>
        /// Used to track the state of Archives
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<ArchivePreview>?> ArchivesOption { get; private set; }

        /// <summary>
        /// Gets or Sets Archives
        /// </summary>
        [JsonPropertyName("archives")]
        public List<ArchivePreview>? Archives { get { return this.ArchivesOption.Value; } set { this.ArchivesOption = new(value); } }

        /// <summary>
        /// Used to track the state of Url
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> UrlOption { get; private set; }

        /// <summary>
        /// Gets or Sets Url
        /// </summary>
        [JsonPropertyName("url")]
        public string? Url { get { return this.UrlOption.Value; } set { this.UrlOption = new(value); } }

        /// <summary>
        /// Used to track the state of CoverImageFilename
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> CoverImageFilenameOption { get; private set; }

        /// <summary>
        /// Gets or Sets CoverImageFilename
        /// </summary>
        [JsonPropertyName("cover_image_filename")]
        public string? CoverImageFilename { get { return this.CoverImageFilenameOption.Value; } set { this.CoverImageFilenameOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ProjectListResponse {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  CreatedAt: ").Append(CreatedAt).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  Color: ").Append(Color).Append("\n");
            sb.Append("  TargetCount: ").Append(TargetCount).Append("\n");
            sb.Append("  TargetPartsCount: ").Append(TargetPartsCount).Append("\n");
            sb.Append("  Budget: ").Append(Budget).Append("\n");
            sb.Append("  ArchiveCount: ").Append(ArchiveCount).Append("\n");
            sb.Append("  TotalItems: ").Append(TotalItems).Append("\n");
            sb.Append("  CompletedCount: ").Append(CompletedCount).Append("\n");
            sb.Append("  FailedCount: ").Append(FailedCount).Append("\n");
            sb.Append("  QueueCount: ").Append(QueueCount).Append("\n");
            sb.Append("  ProgressPercent: ").Append(ProgressPercent).Append("\n");
            sb.Append("  Archives: ").Append(Archives).Append("\n");
            sb.Append("  Url: ").Append(Url).Append("\n");
            sb.Append("  CoverImageFilename: ").Append(CoverImageFilename).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="ProjectListResponse" />
    /// </summary>
    public class ProjectListResponseJsonConverter : JsonConverter<ProjectListResponse>
    {
        /// <summary>
        /// The format to use to serialize CreatedAt
        /// </summary>
        public static string CreatedAtFormat { get; set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// Deserializes json to <see cref="ProjectListResponse" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override ProjectListResponse Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<int?> id = default;
            Option<string?> name = default;
            Option<string?> status = default;
            Option<DateTime?> createdAt = default;
            Option<string?> description = default;
            Option<string?> color = default;
            Option<int?> targetCount = default;
            Option<int?> targetPartsCount = default;
            Option<decimal?> budget = default;
            Option<int?> archiveCount = default;
            Option<int?> totalItems = default;
            Option<int?> completedCount = default;
            Option<int?> failedCount = default;
            Option<int?> queueCount = default;
            Option<decimal?> progressPercent = default;
            Option<List<ArchivePreview>?> archives = default;
            Option<string?> url = default;
            Option<string?> coverImageFilename = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "id":
                            id = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "name":
                            name = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "status":
                            status = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "created_at":
                            createdAt = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "description":
                            description = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "color":
                            color = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "target_count":
                            targetCount = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "target_parts_count":
                            targetPartsCount = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "budget":
                            budget = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        case "archive_count":
                            archiveCount = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "total_items":
                            totalItems = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "completed_count":
                            completedCount = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "failed_count":
                            failedCount = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "queue_count":
                            queueCount = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "progress_percent":
                            progressPercent = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        case "archives":
                            archives = new Option<List<ArchivePreview>?>(JsonSerializer.Deserialize<List<ArchivePreview>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "url":
                            url = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "cover_image_filename":
                            coverImageFilename = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!id.IsSet)
                throw new ArgumentException("Property is required for class ProjectListResponse.", nameof(id));

            if (!name.IsSet)
                throw new ArgumentException("Property is required for class ProjectListResponse.", nameof(name));

            if (!status.IsSet)
                throw new ArgumentException("Property is required for class ProjectListResponse.", nameof(status));

            if (!createdAt.IsSet)
                throw new ArgumentException("Property is required for class ProjectListResponse.", nameof(createdAt));

            if (!description.IsSet)
                throw new ArgumentException("Property is required for class ProjectListResponse.", nameof(description));

            if (!color.IsSet)
                throw new ArgumentException("Property is required for class ProjectListResponse.", nameof(color));

            if (!targetCount.IsSet)
                throw new ArgumentException("Property is required for class ProjectListResponse.", nameof(targetCount));

            if (id.IsSet && id.Value == null)
                throw new ArgumentNullException(nameof(id), "Property is not nullable for class ProjectListResponse.");

            if (name.IsSet && name.Value == null)
                throw new ArgumentNullException(nameof(name), "Property is not nullable for class ProjectListResponse.");

            if (status.IsSet && status.Value == null)
                throw new ArgumentNullException(nameof(status), "Property is not nullable for class ProjectListResponse.");

            if (createdAt.IsSet && createdAt.Value == null)
                throw new ArgumentNullException(nameof(createdAt), "Property is not nullable for class ProjectListResponse.");

            if (archiveCount.IsSet && archiveCount.Value == null)
                throw new ArgumentNullException(nameof(archiveCount), "Property is not nullable for class ProjectListResponse.");

            if (totalItems.IsSet && totalItems.Value == null)
                throw new ArgumentNullException(nameof(totalItems), "Property is not nullable for class ProjectListResponse.");

            if (completedCount.IsSet && completedCount.Value == null)
                throw new ArgumentNullException(nameof(completedCount), "Property is not nullable for class ProjectListResponse.");

            if (failedCount.IsSet && failedCount.Value == null)
                throw new ArgumentNullException(nameof(failedCount), "Property is not nullable for class ProjectListResponse.");

            if (queueCount.IsSet && queueCount.Value == null)
                throw new ArgumentNullException(nameof(queueCount), "Property is not nullable for class ProjectListResponse.");

            if (archives.IsSet && archives.Value == null)
                throw new ArgumentNullException(nameof(archives), "Property is not nullable for class ProjectListResponse.");

            return new ProjectListResponse(id.Value!.Value!, name.Value!, status.Value!, createdAt.Value!.Value!, description.Value!, color.Value!, targetCount.Value!, targetPartsCount, budget, archiveCount, totalItems, completedCount, failedCount, queueCount, progressPercent, archives, url, coverImageFilename);
        }

        /// <summary>
        /// Serializes a <see cref="ProjectListResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="projectListResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, ProjectListResponse projectListResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, projectListResponse, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="ProjectListResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="projectListResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, ProjectListResponse projectListResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            if (projectListResponse.Name == null)
                throw new ArgumentNullException(nameof(projectListResponse.Name), "Property is required for class ProjectListResponse.");

            if (projectListResponse.Status == null)
                throw new ArgumentNullException(nameof(projectListResponse.Status), "Property is required for class ProjectListResponse.");

            if (projectListResponse.ArchivesOption.IsSet && projectListResponse.Archives == null)
                throw new ArgumentNullException(nameof(projectListResponse.Archives), "Property is required for class ProjectListResponse.");

            writer.WriteNumber("id", projectListResponse.Id);

            writer.WriteString("name", projectListResponse.Name);

            writer.WriteString("status", projectListResponse.Status);

            writer.WriteString("created_at", projectListResponse.CreatedAt.ToString(CreatedAtFormat));

            if (projectListResponse.Description != null)
                writer.WriteString("description", projectListResponse.Description);
            else
                writer.WriteNull("description");

            if (projectListResponse.Color != null)
                writer.WriteString("color", projectListResponse.Color);
            else
                writer.WriteNull("color");

            if (projectListResponse.TargetCount != null)
                writer.WriteNumber("target_count", projectListResponse.TargetCount.Value);
            else
                writer.WriteNull("target_count");

            if (projectListResponse.TargetPartsCountOption.IsSet)
                if (projectListResponse.TargetPartsCountOption.Value != null)
                    writer.WriteNumber("target_parts_count", projectListResponse.TargetPartsCountOption.Value!.Value);
                else
                    writer.WriteNull("target_parts_count");

            if (projectListResponse.BudgetOption.IsSet)
                if (projectListResponse.BudgetOption.Value != null)
                    writer.WriteNumber("budget", projectListResponse.BudgetOption.Value!.Value);
                else
                    writer.WriteNull("budget");

            if (projectListResponse.ArchiveCountOption.IsSet)
                writer.WriteNumber("archive_count", projectListResponse.ArchiveCountOption.Value!.Value);

            if (projectListResponse.TotalItemsOption.IsSet)
                writer.WriteNumber("total_items", projectListResponse.TotalItemsOption.Value!.Value);

            if (projectListResponse.CompletedCountOption.IsSet)
                writer.WriteNumber("completed_count", projectListResponse.CompletedCountOption.Value!.Value);

            if (projectListResponse.FailedCountOption.IsSet)
                writer.WriteNumber("failed_count", projectListResponse.FailedCountOption.Value!.Value);

            if (projectListResponse.QueueCountOption.IsSet)
                writer.WriteNumber("queue_count", projectListResponse.QueueCountOption.Value!.Value);

            if (projectListResponse.ProgressPercentOption.IsSet)
                if (projectListResponse.ProgressPercentOption.Value != null)
                    writer.WriteNumber("progress_percent", projectListResponse.ProgressPercentOption.Value!.Value);
                else
                    writer.WriteNull("progress_percent");

            if (projectListResponse.ArchivesOption.IsSet)
            {
                writer.WritePropertyName("archives");
                JsonSerializer.Serialize(writer, projectListResponse.Archives, jsonSerializerOptions);
            }
            if (projectListResponse.UrlOption.IsSet)
                if (projectListResponse.UrlOption.Value != null)
                    writer.WriteString("url", projectListResponse.Url);
                else
                    writer.WriteNull("url");

            if (projectListResponse.CoverImageFilenameOption.IsSet)
                if (projectListResponse.CoverImageFilenameOption.Value != null)
                    writer.WriteString("cover_image_filename", projectListResponse.CoverImageFilename);
                else
                    writer.WriteNull("cover_image_filename");
        }
    }
}
