// <auto-generated>
/*
 * Bambuddy
 *
 * Archive and manage Bambu Lab 3MF files
 *
 * The version of the OpenAPI document: 0.2.4.5
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Bambuddy.Api.Client;

namespace Bambuddy.Api.Model
{
    /// <summary>
    /// Schema for updating a project.
    /// </summary>
    public partial class ProjectUpdate : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ProjectUpdate" /> class.
        /// </summary>
        /// <param name="name">name</param>
        /// <param name="description">description</param>
        /// <param name="color">color</param>
        /// <param name="status">status</param>
        /// <param name="targetCount">targetCount</param>
        /// <param name="targetPartsCount">targetPartsCount</param>
        /// <param name="notes">notes</param>
        /// <param name="tags">tags</param>
        /// <param name="dueDate">dueDate</param>
        /// <param name="priority">priority</param>
        /// <param name="budget">budget</param>
        /// <param name="parentId">parentId</param>
        /// <param name="url">url</param>
        [JsonConstructor]
        public ProjectUpdate(Option<string?> name = default, Option<string?> description = default, Option<string?> color = default, Option<string?> status = default, Option<int?> targetCount = default, Option<int?> targetPartsCount = default, Option<string?> notes = default, Option<string?> tags = default, Option<DateTime?> dueDate = default, Option<string?> priority = default, Option<decimal?> budget = default, Option<int?> parentId = default, Option<string?> url = default)
        {
            NameOption = name;
            DescriptionOption = description;
            ColorOption = color;
            StatusOption = status;
            TargetCountOption = targetCount;
            TargetPartsCountOption = targetPartsCount;
            NotesOption = notes;
            TagsOption = tags;
            DueDateOption = dueDate;
            PriorityOption = priority;
            BudgetOption = budget;
            ParentIdOption = parentId;
            UrlOption = url;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Name
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> NameOption { get; private set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [JsonPropertyName("name")]
        public string? Name { get { return this.NameOption.Value; } set { this.NameOption = new(value); } }

        /// <summary>
        /// Used to track the state of Description
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> DescriptionOption { get; private set; }

        /// <summary>
        /// Gets or Sets Description
        /// </summary>
        [JsonPropertyName("description")]
        public string? Description { get { return this.DescriptionOption.Value; } set { this.DescriptionOption = new(value); } }

        /// <summary>
        /// Used to track the state of Color
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ColorOption { get; private set; }

        /// <summary>
        /// Gets or Sets Color
        /// </summary>
        [JsonPropertyName("color")]
        public string? Color { get { return this.ColorOption.Value; } set { this.ColorOption = new(value); } }

        /// <summary>
        /// Used to track the state of Status
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> StatusOption { get; private set; }

        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [JsonPropertyName("status")]
        public string? Status { get { return this.StatusOption.Value; } set { this.StatusOption = new(value); } }

        /// <summary>
        /// Used to track the state of TargetCount
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> TargetCountOption { get; private set; }

        /// <summary>
        /// Gets or Sets TargetCount
        /// </summary>
        [JsonPropertyName("target_count")]
        public int? TargetCount { get { return this.TargetCountOption.Value; } set { this.TargetCountOption = new(value); } }

        /// <summary>
        /// Used to track the state of TargetPartsCount
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> TargetPartsCountOption { get; private set; }

        /// <summary>
        /// Gets or Sets TargetPartsCount
        /// </summary>
        [JsonPropertyName("target_parts_count")]
        public int? TargetPartsCount { get { return this.TargetPartsCountOption.Value; } set { this.TargetPartsCountOption = new(value); } }

        /// <summary>
        /// Used to track the state of Notes
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> NotesOption { get; private set; }

        /// <summary>
        /// Gets or Sets Notes
        /// </summary>
        [JsonPropertyName("notes")]
        public string? Notes { get { return this.NotesOption.Value; } set { this.NotesOption = new(value); } }

        /// <summary>
        /// Used to track the state of Tags
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> TagsOption { get; private set; }

        /// <summary>
        /// Gets or Sets Tags
        /// </summary>
        [JsonPropertyName("tags")]
        public string? Tags { get { return this.TagsOption.Value; } set { this.TagsOption = new(value); } }

        /// <summary>
        /// Used to track the state of DueDate
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DateTime?> DueDateOption { get; private set; }

        /// <summary>
        /// Gets or Sets DueDate
        /// </summary>
        [JsonPropertyName("due_date")]
        public DateTime? DueDate { get { return this.DueDateOption.Value; } set { this.DueDateOption = new(value); } }

        /// <summary>
        /// Used to track the state of Priority
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> PriorityOption { get; private set; }

        /// <summary>
        /// Gets or Sets Priority
        /// </summary>
        [JsonPropertyName("priority")]
        public string? Priority { get { return this.PriorityOption.Value; } set { this.PriorityOption = new(value); } }

        /// <summary>
        /// Used to track the state of Budget
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<decimal?> BudgetOption { get; private set; }

        /// <summary>
        /// Gets or Sets Budget
        /// </summary>
        [JsonPropertyName("budget")]
        public decimal? Budget { get { return this.BudgetOption.Value; } set { this.BudgetOption = new(value); } }

        /// <summary>
        /// Used to track the state of ParentId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> ParentIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets ParentId
        /// </summary>
        [JsonPropertyName("parent_id")]
        public int? ParentId { get { return this.ParentIdOption.Value; } set { this.ParentIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of Url
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> UrlOption { get; private set; }

        /// <summary>
        /// Gets or Sets Url
        /// </summary>
        [JsonPropertyName("url")]
        public string? Url { get { return this.UrlOption.Value; } set { this.UrlOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ProjectUpdate {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  Color: ").Append(Color).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  TargetCount: ").Append(TargetCount).Append("\n");
            sb.Append("  TargetPartsCount: ").Append(TargetPartsCount).Append("\n");
            sb.Append("  Notes: ").Append(Notes).Append("\n");
            sb.Append("  Tags: ").Append(Tags).Append("\n");
            sb.Append("  DueDate: ").Append(DueDate).Append("\n");
            sb.Append("  Priority: ").Append(Priority).Append("\n");
            sb.Append("  Budget: ").Append(Budget).Append("\n");
            sb.Append("  ParentId: ").Append(ParentId).Append("\n");
            sb.Append("  Url: ").Append(Url).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="ProjectUpdate" />
    /// </summary>
    public class ProjectUpdateJsonConverter : JsonConverter<ProjectUpdate>
    {
        /// <summary>
        /// The format to use to serialize DueDate
        /// </summary>
        public static string DueDateFormat { get; set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// Deserializes json to <see cref="ProjectUpdate" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override ProjectUpdate Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> name = default;
            Option<string?> description = default;
            Option<string?> color = default;
            Option<string?> status = default;
            Option<int?> targetCount = default;
            Option<int?> targetPartsCount = default;
            Option<string?> notes = default;
            Option<string?> tags = default;
            Option<DateTime?> dueDate = default;
            Option<string?> priority = default;
            Option<decimal?> budget = default;
            Option<int?> parentId = default;
            Option<string?> url = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "name":
                            name = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "description":
                            description = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "color":
                            color = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "status":
                            status = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "target_count":
                            targetCount = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "target_parts_count":
                            targetPartsCount = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "notes":
                            notes = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "tags":
                            tags = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "due_date":
                            dueDate = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime?>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "priority":
                            priority = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "budget":
                            budget = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        case "parent_id":
                            parentId = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "url":
                            url = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        default:
                            break;
                    }
                }
            }

            return new ProjectUpdate(name, description, color, status, targetCount, targetPartsCount, notes, tags, dueDate, priority, budget, parentId, url);
        }

        /// <summary>
        /// Serializes a <see cref="ProjectUpdate" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="projectUpdate"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, ProjectUpdate projectUpdate, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, projectUpdate, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="ProjectUpdate" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="projectUpdate"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, ProjectUpdate projectUpdate, JsonSerializerOptions jsonSerializerOptions)
        {
            if (projectUpdate.NameOption.IsSet)
                if (projectUpdate.NameOption.Value != null)
                    writer.WriteString("name", projectUpdate.Name);
                else
                    writer.WriteNull("name");

            if (projectUpdate.DescriptionOption.IsSet)
                if (projectUpdate.DescriptionOption.Value != null)
                    writer.WriteString("description", projectUpdate.Description);
                else
                    writer.WriteNull("description");

            if (projectUpdate.ColorOption.IsSet)
                if (projectUpdate.ColorOption.Value != null)
                    writer.WriteString("color", projectUpdate.Color);
                else
                    writer.WriteNull("color");

            if (projectUpdate.StatusOption.IsSet)
                if (projectUpdate.StatusOption.Value != null)
                    writer.WriteString("status", projectUpdate.Status);
                else
                    writer.WriteNull("status");

            if (projectUpdate.TargetCountOption.IsSet)
                if (projectUpdate.TargetCountOption.Value != null)
                    writer.WriteNumber("target_count", projectUpdate.TargetCountOption.Value!.Value);
                else
                    writer.WriteNull("target_count");

            if (projectUpdate.TargetPartsCountOption.IsSet)
                if (projectUpdate.TargetPartsCountOption.Value != null)
                    writer.WriteNumber("target_parts_count", projectUpdate.TargetPartsCountOption.Value!.Value);
                else
                    writer.WriteNull("target_parts_count");

            if (projectUpdate.NotesOption.IsSet)
                if (projectUpdate.NotesOption.Value != null)
                    writer.WriteString("notes", projectUpdate.Notes);
                else
                    writer.WriteNull("notes");

            if (projectUpdate.TagsOption.IsSet)
                if (projectUpdate.TagsOption.Value != null)
                    writer.WriteString("tags", projectUpdate.Tags);
                else
                    writer.WriteNull("tags");

            if (projectUpdate.DueDateOption.IsSet)
                if (projectUpdate.DueDateOption.Value != null)
                    writer.WriteString("due_date", projectUpdate.DueDateOption.Value!.Value.ToString(DueDateFormat));
                else
                    writer.WriteNull("due_date");

            if (projectUpdate.PriorityOption.IsSet)
                if (projectUpdate.PriorityOption.Value != null)
                    writer.WriteString("priority", projectUpdate.Priority);
                else
                    writer.WriteNull("priority");

            if (projectUpdate.BudgetOption.IsSet)
                if (projectUpdate.BudgetOption.Value != null)
                    writer.WriteNumber("budget", projectUpdate.BudgetOption.Value!.Value);
                else
                    writer.WriteNull("budget");

            if (projectUpdate.ParentIdOption.IsSet)
                if (projectUpdate.ParentIdOption.Value != null)
                    writer.WriteNumber("parent_id", projectUpdate.ParentIdOption.Value!.Value);
                else
                    writer.WriteNull("parent_id");

            if (projectUpdate.UrlOption.IsSet)
                if (projectUpdate.UrlOption.Value != null)
                    writer.WriteString("url", projectUpdate.Url);
                else
                    writer.WriteNull("url");
        }
    }
}
