// <auto-generated>
/*
 * Bambuddy
 *
 * Archive and manage Bambu Lab 3MF files
 *
 * The version of the OpenAPI document: 0.2.4.5
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Bambuddy.Api.Client;

namespace Bambuddy.Api.Model
{
    /// <summary>
    /// Information about a skipped spool during sync.
    /// </summary>
    public partial class SkippedSpool : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SkippedSpool" /> class.
        /// </summary>
        /// <param name="location">location</param>
        /// <param name="reason">reason</param>
        /// <param name="filamentType">filamentType</param>
        /// <param name="color">color</param>
        [JsonConstructor]
        public SkippedSpool(string location, ReasonEnum reason, Option<string?> filamentType = default, Option<string?> color = default)
        {
            Location = location;
            Reason = reason;
            FilamentTypeOption = filamentType;
            ColorOption = color;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Defines Reason
        /// </summary>
        public enum ReasonEnum
        {
            /// <summary>
            /// Enum NoRFIDTagAndNoSlotAssignment for value: No RFID tag and no slot assignment
            /// </summary>
            NoRFIDTagAndNoSlotAssignment = 1
        }

        /// <summary>
        /// Returns a <see cref="ReasonEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static ReasonEnum ReasonEnumFromString(string value)
        {
            if (value.Equals("No RFID tag and no slot assignment"))
                return ReasonEnum.NoRFIDTagAndNoSlotAssignment;

            throw new NotImplementedException($"Could not convert value to type ReasonEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="ReasonEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static ReasonEnum? ReasonEnumFromStringOrDefault(string value)
        {
            if (value.Equals("No RFID tag and no slot assignment"))
                return ReasonEnum.NoRFIDTagAndNoSlotAssignment;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="ReasonEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string ReasonEnumToJsonValue(ReasonEnum value)
        {
            if (value == ReasonEnum.NoRFIDTagAndNoSlotAssignment)
                return "No RFID tag and no slot assignment";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Gets or Sets Reason
        /// </summary>
        [JsonPropertyName("reason")]
        public ReasonEnum Reason { get; set; }

        /// <summary>
        /// Gets or Sets Location
        /// </summary>
        [JsonPropertyName("location")]
        public string Location { get; set; }

        /// <summary>
        /// Used to track the state of FilamentType
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> FilamentTypeOption { get; private set; }

        /// <summary>
        /// Gets or Sets FilamentType
        /// </summary>
        [JsonPropertyName("filament_type")]
        public string? FilamentType { get { return this.FilamentTypeOption.Value; } set { this.FilamentTypeOption = new(value); } }

        /// <summary>
        /// Used to track the state of Color
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ColorOption { get; private set; }

        /// <summary>
        /// Gets or Sets Color
        /// </summary>
        [JsonPropertyName("color")]
        public string? Color { get { return this.ColorOption.Value; } set { this.ColorOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SkippedSpool {\n");
            sb.Append("  Location: ").Append(Location).Append("\n");
            sb.Append("  Reason: ").Append(Reason).Append("\n");
            sb.Append("  FilamentType: ").Append(FilamentType).Append("\n");
            sb.Append("  Color: ").Append(Color).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="SkippedSpool" />
    /// </summary>
    public class SkippedSpoolJsonConverter : JsonConverter<SkippedSpool>
    {
        /// <summary>
        /// Deserializes json to <see cref="SkippedSpool" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override SkippedSpool Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> location = default;
            Option<SkippedSpool.ReasonEnum?> reason = default;
            Option<string?> filamentType = default;
            Option<string?> color = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "location":
                            location = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "reason":
                            string? reasonRawValue = utf8JsonReader.GetString();
                            if (reasonRawValue != null)
                                reason = new Option<SkippedSpool.ReasonEnum?>(SkippedSpool.ReasonEnumFromStringOrDefault(reasonRawValue));
                            break;
                        case "filament_type":
                            filamentType = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "color":
                            color = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!location.IsSet)
                throw new ArgumentException("Property is required for class SkippedSpool.", nameof(location));

            if (!reason.IsSet)
                throw new ArgumentException("Property is required for class SkippedSpool.", nameof(reason));

            if (location.IsSet && location.Value == null)
                throw new ArgumentNullException(nameof(location), "Property is not nullable for class SkippedSpool.");

            if (reason.IsSet && reason.Value == null)
                throw new ArgumentNullException(nameof(reason), "Property is not nullable for class SkippedSpool.");

            return new SkippedSpool(location.Value!, reason.Value!.Value!, filamentType, color);
        }

        /// <summary>
        /// Serializes a <see cref="SkippedSpool" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="skippedSpool"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, SkippedSpool skippedSpool, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, skippedSpool, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="SkippedSpool" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="skippedSpool"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, SkippedSpool skippedSpool, JsonSerializerOptions jsonSerializerOptions)
        {
            if (skippedSpool.Location == null)
                throw new ArgumentNullException(nameof(skippedSpool.Location), "Property is required for class SkippedSpool.");

            writer.WriteString("location", skippedSpool.Location);

            var reasonRawValue = SkippedSpool.ReasonEnumToJsonValue(skippedSpool.Reason);
            writer.WriteString("reason", reasonRawValue);
            if (skippedSpool.FilamentTypeOption.IsSet)
                if (skippedSpool.FilamentTypeOption.Value != null)
                    writer.WriteString("filament_type", skippedSpool.FilamentType);
                else
                    writer.WriteNull("filament_type");

            if (skippedSpool.ColorOption.IsSet)
                if (skippedSpool.ColorOption.Value != null)
                    writer.WriteString("color", skippedSpool.Color);
                else
                    writer.WriteNull("color");
        }
    }
}
