// <auto-generated>
/*
 * Bambuddy
 *
 * Archive and manage Bambu Lab 3MF files
 *
 * The version of the OpenAPI document: 0.2.4.5
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Bambuddy.Api.Client;

namespace Bambuddy.Api.Model
{
    /// <summary>
    /// SpoolUsageHistoryResponse
    /// </summary>
    public partial class SpoolUsageHistoryResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SpoolUsageHistoryResponse" /> class.
        /// </summary>
        /// <param name="id">id</param>
        /// <param name="spoolId">spoolId</param>
        /// <param name="weightUsed">weightUsed</param>
        /// <param name="percentUsed">percentUsed</param>
        /// <param name="status">status</param>
        /// <param name="createdAt">createdAt</param>
        /// <param name="printerId">printerId</param>
        /// <param name="printName">printName</param>
        /// <param name="cost">cost</param>
        [JsonConstructor]
        public SpoolUsageHistoryResponse(int id, int spoolId, decimal weightUsed, int percentUsed, string status, DateTime createdAt, Option<int?> printerId = default, Option<string?> printName = default, Option<decimal?> cost = default)
        {
            Id = id;
            SpoolId = spoolId;
            WeightUsed = weightUsed;
            PercentUsed = percentUsed;
            Status = status;
            CreatedAt = createdAt;
            PrinterIdOption = printerId;
            PrintNameOption = printName;
            CostOption = cost;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [JsonPropertyName("id")]
        public int Id { get; set; }

        /// <summary>
        /// Gets or Sets SpoolId
        /// </summary>
        [JsonPropertyName("spool_id")]
        public int SpoolId { get; set; }

        /// <summary>
        /// Gets or Sets WeightUsed
        /// </summary>
        [JsonPropertyName("weight_used")]
        public decimal WeightUsed { get; set; }

        /// <summary>
        /// Gets or Sets PercentUsed
        /// </summary>
        [JsonPropertyName("percent_used")]
        public int PercentUsed { get; set; }

        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [JsonPropertyName("status")]
        public string Status { get; set; }

        /// <summary>
        /// Gets or Sets CreatedAt
        /// </summary>
        [JsonPropertyName("created_at")]
        public DateTime CreatedAt { get; set; }

        /// <summary>
        /// Used to track the state of PrinterId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> PrinterIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets PrinterId
        /// </summary>
        [JsonPropertyName("printer_id")]
        public int? PrinterId { get { return this.PrinterIdOption.Value; } set { this.PrinterIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of PrintName
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> PrintNameOption { get; private set; }

        /// <summary>
        /// Gets or Sets PrintName
        /// </summary>
        [JsonPropertyName("print_name")]
        public string? PrintName { get { return this.PrintNameOption.Value; } set { this.PrintNameOption = new(value); } }

        /// <summary>
        /// Used to track the state of Cost
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<decimal?> CostOption { get; private set; }

        /// <summary>
        /// Gets or Sets Cost
        /// </summary>
        [JsonPropertyName("cost")]
        public decimal? Cost { get { return this.CostOption.Value; } set { this.CostOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SpoolUsageHistoryResponse {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  SpoolId: ").Append(SpoolId).Append("\n");
            sb.Append("  WeightUsed: ").Append(WeightUsed).Append("\n");
            sb.Append("  PercentUsed: ").Append(PercentUsed).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  CreatedAt: ").Append(CreatedAt).Append("\n");
            sb.Append("  PrinterId: ").Append(PrinterId).Append("\n");
            sb.Append("  PrintName: ").Append(PrintName).Append("\n");
            sb.Append("  Cost: ").Append(Cost).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="SpoolUsageHistoryResponse" />
    /// </summary>
    public class SpoolUsageHistoryResponseJsonConverter : JsonConverter<SpoolUsageHistoryResponse>
    {
        /// <summary>
        /// The format to use to serialize CreatedAt
        /// </summary>
        public static string CreatedAtFormat { get; set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// Deserializes json to <see cref="SpoolUsageHistoryResponse" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override SpoolUsageHistoryResponse Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<int?> id = default;
            Option<int?> spoolId = default;
            Option<decimal?> weightUsed = default;
            Option<int?> percentUsed = default;
            Option<string?> status = default;
            Option<DateTime?> createdAt = default;
            Option<int?> printerId = default;
            Option<string?> printName = default;
            Option<decimal?> cost = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "id":
                            id = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "spool_id":
                            spoolId = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "weight_used":
                            weightUsed = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        case "percent_used":
                            percentUsed = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "status":
                            status = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "created_at":
                            createdAt = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "printer_id":
                            printerId = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "print_name":
                            printName = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "cost":
                            cost = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!id.IsSet)
                throw new ArgumentException("Property is required for class SpoolUsageHistoryResponse.", nameof(id));

            if (!spoolId.IsSet)
                throw new ArgumentException("Property is required for class SpoolUsageHistoryResponse.", nameof(spoolId));

            if (!weightUsed.IsSet)
                throw new ArgumentException("Property is required for class SpoolUsageHistoryResponse.", nameof(weightUsed));

            if (!percentUsed.IsSet)
                throw new ArgumentException("Property is required for class SpoolUsageHistoryResponse.", nameof(percentUsed));

            if (!status.IsSet)
                throw new ArgumentException("Property is required for class SpoolUsageHistoryResponse.", nameof(status));

            if (!createdAt.IsSet)
                throw new ArgumentException("Property is required for class SpoolUsageHistoryResponse.", nameof(createdAt));

            if (id.IsSet && id.Value == null)
                throw new ArgumentNullException(nameof(id), "Property is not nullable for class SpoolUsageHistoryResponse.");

            if (spoolId.IsSet && spoolId.Value == null)
                throw new ArgumentNullException(nameof(spoolId), "Property is not nullable for class SpoolUsageHistoryResponse.");

            if (weightUsed.IsSet && weightUsed.Value == null)
                throw new ArgumentNullException(nameof(weightUsed), "Property is not nullable for class SpoolUsageHistoryResponse.");

            if (percentUsed.IsSet && percentUsed.Value == null)
                throw new ArgumentNullException(nameof(percentUsed), "Property is not nullable for class SpoolUsageHistoryResponse.");

            if (status.IsSet && status.Value == null)
                throw new ArgumentNullException(nameof(status), "Property is not nullable for class SpoolUsageHistoryResponse.");

            if (createdAt.IsSet && createdAt.Value == null)
                throw new ArgumentNullException(nameof(createdAt), "Property is not nullable for class SpoolUsageHistoryResponse.");

            return new SpoolUsageHistoryResponse(id.Value!.Value!, spoolId.Value!.Value!, weightUsed.Value!.Value!, percentUsed.Value!.Value!, status.Value!, createdAt.Value!.Value!, printerId, printName, cost);
        }

        /// <summary>
        /// Serializes a <see cref="SpoolUsageHistoryResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="spoolUsageHistoryResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, SpoolUsageHistoryResponse spoolUsageHistoryResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, spoolUsageHistoryResponse, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="SpoolUsageHistoryResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="spoolUsageHistoryResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, SpoolUsageHistoryResponse spoolUsageHistoryResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            if (spoolUsageHistoryResponse.Status == null)
                throw new ArgumentNullException(nameof(spoolUsageHistoryResponse.Status), "Property is required for class SpoolUsageHistoryResponse.");

            writer.WriteNumber("id", spoolUsageHistoryResponse.Id);

            writer.WriteNumber("spool_id", spoolUsageHistoryResponse.SpoolId);

            writer.WriteNumber("weight_used", spoolUsageHistoryResponse.WeightUsed);

            writer.WriteNumber("percent_used", spoolUsageHistoryResponse.PercentUsed);

            writer.WriteString("status", spoolUsageHistoryResponse.Status);

            writer.WriteString("created_at", spoolUsageHistoryResponse.CreatedAt.ToString(CreatedAtFormat));

            if (spoolUsageHistoryResponse.PrinterIdOption.IsSet)
                if (spoolUsageHistoryResponse.PrinterIdOption.Value != null)
                    writer.WriteNumber("printer_id", spoolUsageHistoryResponse.PrinterIdOption.Value!.Value);
                else
                    writer.WriteNull("printer_id");

            if (spoolUsageHistoryResponse.PrintNameOption.IsSet)
                if (spoolUsageHistoryResponse.PrintNameOption.Value != null)
                    writer.WriteString("print_name", spoolUsageHistoryResponse.PrintName);
                else
                    writer.WriteNull("print_name");

            if (spoolUsageHistoryResponse.CostOption.IsSet)
                if (spoolUsageHistoryResponse.CostOption.Value != null)
                    writer.WriteNumber("cost", spoolUsageHistoryResponse.CostOption.Value!.Value);
                else
                    writer.WriteNull("cost");
        }
    }
}
