// <auto-generated>
/*
 * Bambuddy
 *
 * Archive and manage Bambu Lab 3MF files
 *
 * The version of the OpenAPI document: 0.2.4.5
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Bambuddy.Api.Client;

namespace Bambuddy.Api.Model
{
    /// <summary>
    /// TwoFAStatusResponse
    /// </summary>
    public partial class TwoFAStatusResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TwoFAStatusResponse" /> class.
        /// </summary>
        /// <param name="totpEnabled">totpEnabled</param>
        /// <param name="emailOtpEnabled">emailOtpEnabled</param>
        /// <param name="backupCodesRemaining">backupCodesRemaining</param>
        [JsonConstructor]
        public TwoFAStatusResponse(bool totpEnabled, bool emailOtpEnabled, int backupCodesRemaining)
        {
            TotpEnabled = totpEnabled;
            EmailOtpEnabled = emailOtpEnabled;
            BackupCodesRemaining = backupCodesRemaining;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets TotpEnabled
        /// </summary>
        [JsonPropertyName("totp_enabled")]
        public bool TotpEnabled { get; set; }

        /// <summary>
        /// Gets or Sets EmailOtpEnabled
        /// </summary>
        [JsonPropertyName("email_otp_enabled")]
        public bool EmailOtpEnabled { get; set; }

        /// <summary>
        /// Gets or Sets BackupCodesRemaining
        /// </summary>
        [JsonPropertyName("backup_codes_remaining")]
        public int BackupCodesRemaining { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class TwoFAStatusResponse {\n");
            sb.Append("  TotpEnabled: ").Append(TotpEnabled).Append("\n");
            sb.Append("  EmailOtpEnabled: ").Append(EmailOtpEnabled).Append("\n");
            sb.Append("  BackupCodesRemaining: ").Append(BackupCodesRemaining).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="TwoFAStatusResponse" />
    /// </summary>
    public class TwoFAStatusResponseJsonConverter : JsonConverter<TwoFAStatusResponse>
    {
        /// <summary>
        /// Deserializes json to <see cref="TwoFAStatusResponse" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override TwoFAStatusResponse Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<bool?> totpEnabled = default;
            Option<bool?> emailOtpEnabled = default;
            Option<int?> backupCodesRemaining = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "totp_enabled":
                            totpEnabled = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "email_otp_enabled":
                            emailOtpEnabled = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "backup_codes_remaining":
                            backupCodesRemaining = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!totpEnabled.IsSet)
                throw new ArgumentException("Property is required for class TwoFAStatusResponse.", nameof(totpEnabled));

            if (!emailOtpEnabled.IsSet)
                throw new ArgumentException("Property is required for class TwoFAStatusResponse.", nameof(emailOtpEnabled));

            if (!backupCodesRemaining.IsSet)
                throw new ArgumentException("Property is required for class TwoFAStatusResponse.", nameof(backupCodesRemaining));

            if (totpEnabled.IsSet && totpEnabled.Value == null)
                throw new ArgumentNullException(nameof(totpEnabled), "Property is not nullable for class TwoFAStatusResponse.");

            if (emailOtpEnabled.IsSet && emailOtpEnabled.Value == null)
                throw new ArgumentNullException(nameof(emailOtpEnabled), "Property is not nullable for class TwoFAStatusResponse.");

            if (backupCodesRemaining.IsSet && backupCodesRemaining.Value == null)
                throw new ArgumentNullException(nameof(backupCodesRemaining), "Property is not nullable for class TwoFAStatusResponse.");

            return new TwoFAStatusResponse(totpEnabled.Value!.Value!, emailOtpEnabled.Value!.Value!, backupCodesRemaining.Value!.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="TwoFAStatusResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="twoFAStatusResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, TwoFAStatusResponse twoFAStatusResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, twoFAStatusResponse, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="TwoFAStatusResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="twoFAStatusResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, TwoFAStatusResponse twoFAStatusResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteBoolean("totp_enabled", twoFAStatusResponse.TotpEnabled);

            writer.WriteBoolean("email_otp_enabled", twoFAStatusResponse.EmailOtpEnabled);

            writer.WriteNumber("backup_codes_remaining", twoFAStatusResponse.BackupCodesRemaining);
        }
    }
}
