// <auto-generated>
/*
 * Bambuddy
 *
 * Archive and manage Bambu Lab 3MF files
 *
 * The version of the OpenAPI document: 0.2.4.5
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Bambuddy.Api.Client;

namespace Bambuddy.Api.Model
{
    /// <summary>
    /// WriteTagResultRequest
    /// </summary>
    public partial class WriteTagResultRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="WriteTagResultRequest" /> class.
        /// </summary>
        /// <param name="deviceId">deviceId</param>
        /// <param name="spoolId">spoolId</param>
        /// <param name="tagUid">tagUid</param>
        /// <param name="success">success</param>
        /// <param name="message">message</param>
        [JsonConstructor]
        public WriteTagResultRequest(string deviceId, long spoolId, string tagUid, bool success, Option<string?> message = default)
        {
            DeviceId = deviceId;
            SpoolId = spoolId;
            TagUid = tagUid;
            Success = success;
            MessageOption = message;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets DeviceId
        /// </summary>
        [JsonPropertyName("device_id")]
        public string DeviceId { get; set; }

        /// <summary>
        /// Gets or Sets SpoolId
        /// </summary>
        [JsonPropertyName("spool_id")]
        public long SpoolId { get; set; }

        /// <summary>
        /// Gets or Sets TagUid
        /// </summary>
        [JsonPropertyName("tag_uid")]
        public string TagUid { get; set; }

        /// <summary>
        /// Gets or Sets Success
        /// </summary>
        [JsonPropertyName("success")]
        public bool Success { get; set; }

        /// <summary>
        /// Used to track the state of Message
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> MessageOption { get; private set; }

        /// <summary>
        /// Gets or Sets Message
        /// </summary>
        [JsonPropertyName("message")]
        public string? Message { get { return this.MessageOption.Value; } set { this.MessageOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class WriteTagResultRequest {\n");
            sb.Append("  DeviceId: ").Append(DeviceId).Append("\n");
            sb.Append("  SpoolId: ").Append(SpoolId).Append("\n");
            sb.Append("  TagUid: ").Append(TagUid).Append("\n");
            sb.Append("  Success: ").Append(Success).Append("\n");
            sb.Append("  Message: ").Append(Message).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // DeviceId (string) maxLength
            if (this.DeviceId != null && this.DeviceId.Length > 50)
            {
                yield return new ValidationResult("Invalid value for DeviceId, length must be less than 50.", new [] { "DeviceId" });
            }

            // SpoolId (long) minimum
            if (this.SpoolId < (long)0)
            {
                yield return new ValidationResult("Invalid value for SpoolId, must be a value greater than 0.", new [] { "SpoolId" });
            }

            // TagUid (string) maxLength
            if (this.TagUid != null && this.TagUid.Length > 30)
            {
                yield return new ValidationResult("Invalid value for TagUid, length must be less than 30.", new [] { "TagUid" });
            }

            // TagUid (string) minLength
            if (this.TagUid != null && this.TagUid.Length < 8)
            {
                yield return new ValidationResult("Invalid value for TagUid, length must be greater than 8.", new [] { "TagUid" });
            }

            if (this.TagUid != null) {
                // TagUid (string) pattern
                Regex regexTagUid = new Regex(@"^[0-9A-Fa-f]+$", RegexOptions.CultureInvariant);

                if (!regexTagUid.Match(this.TagUid).Success)
                {
                    yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for TagUid, must match a pattern of " + regexTagUid, new [] { "TagUid" });
                }
            }

            // Message (string) maxLength
            if (this.Message != null && this.Message.Length > 500)
            {
                yield return new ValidationResult("Invalid value for Message, length must be less than 500.", new [] { "Message" });
            }

            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="WriteTagResultRequest" />
    /// </summary>
    public class WriteTagResultRequestJsonConverter : JsonConverter<WriteTagResultRequest>
    {
        /// <summary>
        /// Deserializes json to <see cref="WriteTagResultRequest" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override WriteTagResultRequest Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> deviceId = default;
            Option<long?> spoolId = default;
            Option<string?> tagUid = default;
            Option<bool?> success = default;
            Option<string?> message = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "device_id":
                            deviceId = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "spool_id":
                            spoolId = new Option<long?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "tag_uid":
                            tagUid = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "success":
                            success = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "message":
                            message = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!deviceId.IsSet)
                throw new ArgumentException("Property is required for class WriteTagResultRequest.", nameof(deviceId));

            if (!spoolId.IsSet)
                throw new ArgumentException("Property is required for class WriteTagResultRequest.", nameof(spoolId));

            if (!tagUid.IsSet)
                throw new ArgumentException("Property is required for class WriteTagResultRequest.", nameof(tagUid));

            if (!success.IsSet)
                throw new ArgumentException("Property is required for class WriteTagResultRequest.", nameof(success));

            if (deviceId.IsSet && deviceId.Value == null)
                throw new ArgumentNullException(nameof(deviceId), "Property is not nullable for class WriteTagResultRequest.");

            if (spoolId.IsSet && spoolId.Value == null)
                throw new ArgumentNullException(nameof(spoolId), "Property is not nullable for class WriteTagResultRequest.");

            if (tagUid.IsSet && tagUid.Value == null)
                throw new ArgumentNullException(nameof(tagUid), "Property is not nullable for class WriteTagResultRequest.");

            if (success.IsSet && success.Value == null)
                throw new ArgumentNullException(nameof(success), "Property is not nullable for class WriteTagResultRequest.");

            return new WriteTagResultRequest(deviceId.Value!, spoolId.Value!.Value!, tagUid.Value!, success.Value!.Value!, message);
        }

        /// <summary>
        /// Serializes a <see cref="WriteTagResultRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="writeTagResultRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, WriteTagResultRequest writeTagResultRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, writeTagResultRequest, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="WriteTagResultRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="writeTagResultRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, WriteTagResultRequest writeTagResultRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            if (writeTagResultRequest.DeviceId == null)
                throw new ArgumentNullException(nameof(writeTagResultRequest.DeviceId), "Property is required for class WriteTagResultRequest.");

            if (writeTagResultRequest.TagUid == null)
                throw new ArgumentNullException(nameof(writeTagResultRequest.TagUid), "Property is required for class WriteTagResultRequest.");

            writer.WriteString("device_id", writeTagResultRequest.DeviceId);

            writer.WriteNumber("spool_id", writeTagResultRequest.SpoolId);

            writer.WriteString("tag_uid", writeTagResultRequest.TagUid);

            writer.WriteBoolean("success", writeTagResultRequest.Success);

            if (writeTagResultRequest.MessageOption.IsSet)
                if (writeTagResultRequest.MessageOption.Value != null)
                    writer.WriteString("message", writeTagResultRequest.Message);
                else
                    writer.WriteNull("message");
        }
    }
}
