// <auto-generated />
// Material Symbols (Sharp) glyph constants — self-hosted replacement for
// UraniumUI.Icons.MaterialSymbols. Regenerate with tools/generate_material_icons.py.
namespace BambuMan.Resources.Icons;

/// <summary>Material Symbols (Sharp) glyphs. Use as {x:Static m:MaterialSharp.Name}.</summary>
public static class MaterialSharp
{
    public const string FontFamily = "MaterialSharp";

    public const string Add = "\ue145";
    public const string Arrow_back = "\ue5c4";
    public const string Arrow_forward = "\ue5c8";
    public const string Attach_money = "\ue227";
    public const string Brightness_1 = "\ue3fa";
    public const string Bug_report = "\ue868";
    public const string Calendar_month = "\uebcc";
    public const string Cancel = "\ue888";
    public const string Category = "\ue72c";
    public const string Check = "\ue668";
    public const string Check_circle = "\uf0be";
    public const string Chevron_right = "\ue5cc";
    public const string Circle = "\uef4a";
    public const string Close = "\ue5cd";
    public const string Contactless = "\uea71";
    public const string Content_copy = "\ue14d";
    public const string Dark_mode = "\ue51c";
    public const string Delete = "\ue92e";
    public const string Download = "\uf090";
    public const string Edit = "\uf097";
    public const string Error = "\uf8b6";
    public const string Expand_more = "\ue5cf";
    public const string Flash_off = "\ue3e6";
    public const string Flash_on = "\ue3e7";
    public const string Help = "\ue8fd";
    public const string House = "\uea44";
    public const string Inbox = "\ue156";
    public const string Info = "\ue88e";
    public const string Inventory_2 = "\ue1a1";
    public const string Key = "\ue73c";
    public const string Label = "\ue893";
    public const string Light_mode = "\ue518";
    public const string Link = "\ue250";
    public const string Location_on = "\uf1db";
    public const string Map = "\ue55b";
    public const string Menu = "\ue5d2";
    public const string More_vert = "\ue5d4";
    public const string Nfc = "\ue1bb";
    public const string Palette = "\ue40a";
    public const string Place = "\uf1db";
    public const string Print = "\ue8ad";
    public const string Qr_code_scanner = "\uf206";
    public const string Refresh = "\ue5d5";
    public const string Scale = "\ueb5f";
    public const string Science = "\uea4b";
    public const string Search = "\uef7a";
    public const string Sell = "\uf05b";
    public const string Settings = "\ue8b8";
    public const string Settings_backup_restore = "\ue8ba";
    public const string Share = "\ue80d";
    public const string Straighten = "\ue41c";
    public const string Sync = "\ue627";
    public const string Tag = "\ue9ef";
    public const string Upload = "\uf09b";
    public const string Visibility = "\ue8f4";
    public const string Visibility_off = "\ue8f5";
    public const string Warning = "\uf083";
    public const string Weight = "\ue13d";
    public const string Wifi = "\ue63e";
    public const string Wifi_off = "\ue648";
}
