/*
 * Bambuddy
 *
 * Archive and manage Bambu Lab 3MF files
 *
 * The version of the OpenAPI document: 0.2.4.5
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Net.Http;
using Microsoft.Extensions.DependencyInjection;
using Bambuddy.Api.Api;
using Bambuddy.Api.Model;

namespace Bambuddy.Api.Client
{
    /// <summary>
    /// Provides hosting configuration for Bambuddy.Api
    /// </summary>
    public class HostConfiguration
    {
        private readonly IServiceCollection _services;
        private readonly JsonSerializerOptions _jsonOptions = new JsonSerializerOptions();

        internal bool HttpClientsAdded { get; private set; }

        /// <summary>
        /// Instantiates the class 
        /// </summary>
        /// <param name="services"></param>
        public HostConfiguration(IServiceCollection services)
        {
            _services = services;
            _jsonOptions.Converters.Add(new JsonStringEnumConverter());
            _jsonOptions.Converters.Add(new DateTimeJsonConverter());
            _jsonOptions.Converters.Add(new DateTimeNullableJsonConverter());
            _jsonOptions.Converters.Add(new DateOnlyJsonConverter());
            _jsonOptions.Converters.Add(new DateOnlyNullableJsonConverter());
            _jsonOptions.Converters.Add(new AMSHistoryPointJsonConverter());
            _jsonOptions.Converters.Add(new AMSHistoryResponseJsonConverter());
            _jsonOptions.Converters.Add(new AMSTrayJsonConverter());
            _jsonOptions.Converters.Add(new AMSUnitJsonConverter());
            _jsonOptions.Converters.Add(new APIKeyCreateJsonConverter());
            _jsonOptions.Converters.Add(new APIKeyCreateResponseJsonConverter());
            _jsonOptions.Converters.Add(new APIKeyResponseJsonConverter());
            _jsonOptions.Converters.Add(new APIKeyUpdateJsonConverter());
            _jsonOptions.Converters.Add(new AddToQueueErrorJsonConverter());
            _jsonOptions.Converters.Add(new AddToQueueRequestJsonConverter());
            _jsonOptions.Converters.Add(new AddToQueueResponseJsonConverter());
            _jsonOptions.Converters.Add(new AddToQueueResultJsonConverter());
            _jsonOptions.Converters.Add(new AdminDisable2FARequestJsonConverter());
            _jsonOptions.Converters.Add(new AmsLabelBodyJsonConverter());
            _jsonOptions.Converters.Add(new AppSettingsJsonConverter());
            _jsonOptions.Converters.Add(new AppSettingsUpdateJsonConverter());
            _jsonOptions.Converters.Add(new ArchiveDuplicateJsonConverter());
            _jsonOptions.Converters.Add(new ArchivePreviewJsonConverter());
            _jsonOptions.Converters.Add(new ArchivePurgePreviewResponseJsonConverter());
            _jsonOptions.Converters.Add(new ArchivePurgeRequestJsonConverter());
            _jsonOptions.Converters.Add(new ArchivePurgeResponseJsonConverter());
            _jsonOptions.Converters.Add(new ArchivePurgeSettingsJsonConverter());
            _jsonOptions.Converters.Add(new ArchiveRequestJsonConverter());
            _jsonOptions.Converters.Add(new ArchiveResponseJsonConverter());
            _jsonOptions.Converters.Add(new ArchiveSlimJsonConverter());
            _jsonOptions.Converters.Add(new ArchiveStatsJsonConverter());
            _jsonOptions.Converters.Add(new ArchiveUpdateJsonConverter());
            _jsonOptions.Converters.Add(new AvailableFirmwareVersionJsonConverter());
            _jsonOptions.Converters.Add(new BOMItemCreateJsonConverter());
            _jsonOptions.Converters.Add(new BOMItemExportJsonConverter());
            _jsonOptions.Converters.Add(new BOMItemResponseJsonConverter());
            _jsonOptions.Converters.Add(new BOMItemUpdateJsonConverter());
            _jsonOptions.Converters.Add(new BackendAppApiRoutesFirmwareFirmwareUpdateInfoJsonConverter());
            _jsonOptions.Converters.Add(new BackendAppApiRoutesFirmwareFirmwareUpdatesResponseJsonConverter());
            _jsonOptions.Converters.Add(new BackendAppSchemasCloudFirmwareUpdateInfoJsonConverter());
            _jsonOptions.Converters.Add(new BackendAppSchemasCloudFirmwareUpdatesResponseJsonConverter());
            _jsonOptions.Converters.Add(new BackendAppSchemasGithubBackupProviderTypeJsonConverter());
            _jsonOptions.Converters.Add(new BackendAppSchemasGithubBackupProviderTypeNullableJsonConverter());
            _jsonOptions.Converters.Add(new BackupCodesResponseJsonConverter());
            _jsonOptions.Converters.Add(new BatchAddArchivesJsonConverter());
            _jsonOptions.Converters.Add(new BatchAddQueueItemsJsonConverter());
            _jsonOptions.Converters.Add(new BatchThumbnailRequestJsonConverter());
            _jsonOptions.Converters.Add(new BatchThumbnailResponseJsonConverter());
            _jsonOptions.Converters.Add(new BatchThumbnailResultJsonConverter());
            _jsonOptions.Converters.Add(new BugReportRequestJsonConverter());
            _jsonOptions.Converters.Add(new BugReportResponseJsonConverter());
            _jsonOptions.Converters.Add(new BulkDeleteIdsRequestJsonConverter());
            _jsonOptions.Converters.Add(new BulkDeleteRequestJsonConverter());
            _jsonOptions.Converters.Add(new BulkDeleteResponseJsonConverter());
            _jsonOptions.Converters.Add(new CalibrationResponseJsonConverter());
            _jsonOptions.Converters.Add(new CatalogEntryCreateJsonConverter());
            _jsonOptions.Converters.Add(new CatalogEntryResponseJsonConverter());
            _jsonOptions.Converters.Add(new CatalogEntryUpdateJsonConverter());
            _jsonOptions.Converters.Add(new ChangePasswordRequestJsonConverter());
            _jsonOptions.Converters.Add(new CloudAuthStatusJsonConverter());
            _jsonOptions.Converters.Add(new CloudDeviceJsonConverter());
            _jsonOptions.Converters.Add(new CloudLoginRequestJsonConverter());
            _jsonOptions.Converters.Add(new CloudLoginResponseJsonConverter());
            _jsonOptions.Converters.Add(new CloudTokenRequestJsonConverter());
            _jsonOptions.Converters.Add(new CloudVerifyRequestJsonConverter());
            _jsonOptions.Converters.Add(new ColorEntryCreateJsonConverter());
            _jsonOptions.Converters.Add(new ColorEntryResponseJsonConverter());
            _jsonOptions.Converters.Add(new ColorEntryUpdateJsonConverter());
            _jsonOptions.Converters.Add(new ColorLookupResultJsonConverter());
            _jsonOptions.Converters.Add(new DebugLoggingStateJsonConverter());
            _jsonOptions.Converters.Add(new DebugLoggingToggleJsonConverter());
            _jsonOptions.Converters.Add(new DeviceRegisterRequestJsonConverter());
            _jsonOptions.Converters.Add(new DeviceResponseJsonConverter());
            _jsonOptions.Converters.Add(new DiagnosticCheckJsonConverter());
            _jsonOptions.Converters.Add(new DiagnosticRequestJsonConverter());
            _jsonOptions.Converters.Add(new DiagnosticResultRequestJsonConverter());
            _jsonOptions.Converters.Add(new DiscoveredPrinterResponseJsonConverter());
            _jsonOptions.Converters.Add(new DiscoveredTasmotaDeviceJsonConverter());
            _jsonOptions.Converters.Add(new DiscoveryInfoJsonConverter());
            _jsonOptions.Converters.Add(new DiscoveryStatusJsonConverter());
            _jsonOptions.Converters.Add(new DisplaySettingsRequestJsonConverter());
            _jsonOptions.Converters.Add(new ElectricityPriceUpdateJsonConverter());
            _jsonOptions.Converters.Add(new EmailOTPDisableRequestJsonConverter());
            _jsonOptions.Converters.Add(new EmailOTPEnableConfirmRequestJsonConverter());
            _jsonOptions.Converters.Add(new EmailOTPSendRequestJsonConverter());
            _jsonOptions.Converters.Add(new EmptyTrashResponseJsonConverter());
            _jsonOptions.Converters.Add(new EncryptionRowCountsJsonConverter());
            _jsonOptions.Converters.Add(new EncryptionStatusResponseJsonConverter());
            _jsonOptions.Converters.Add(new EventVariablesResponseJsonConverter());
            _jsonOptions.Converters.Add(new ExternalFolderCreateJsonConverter());
            _jsonOptions.Converters.Add(new ExternalLinkCreateJsonConverter());
            _jsonOptions.Converters.Add(new ExternalLinkReorderJsonConverter());
            _jsonOptions.Converters.Add(new ExternalLinkResponseJsonConverter());
            _jsonOptions.Converters.Add(new ExternalLinkUpdateJsonConverter());
            _jsonOptions.Converters.Add(new FilaSwitchResponseJsonConverter());
            _jsonOptions.Converters.Add(new FilamentCostCalculationJsonConverter());
            _jsonOptions.Converters.Add(new FilamentCreateJsonConverter());
            _jsonOptions.Converters.Add(new FilamentResponseJsonConverter());
            _jsonOptions.Converters.Add(new FilamentSkuSettingsResponseJsonConverter());
            _jsonOptions.Converters.Add(new FilamentSkuSettingsUpsertJsonConverter());
            _jsonOptions.Converters.Add(new FilamentUpdateJsonConverter());
            _jsonOptions.Converters.Add(new FileDuplicateJsonConverter());
            _jsonOptions.Converters.Add(new FileListResponseJsonConverter());
            _jsonOptions.Converters.Add(new FileMoveRequestJsonConverter());
            _jsonOptions.Converters.Add(new FilePrintRequestJsonConverter());
            _jsonOptions.Converters.Add(new FileResponseJsonConverter());
            _jsonOptions.Converters.Add(new FileUpdateJsonConverter());
            _jsonOptions.Converters.Add(new FileUploadResponseJsonConverter());
            _jsonOptions.Converters.Add(new FirmwareUploadPrepareResponseJsonConverter());
            _jsonOptions.Converters.Add(new FirmwareUploadStartResponseJsonConverter());
            _jsonOptions.Converters.Add(new FirmwareUploadStatusResponseJsonConverter());
            _jsonOptions.Converters.Add(new FolderCreateJsonConverter());
            _jsonOptions.Converters.Add(new FolderResponseJsonConverter());
            _jsonOptions.Converters.Add(new FolderTreeItemJsonConverter());
            _jsonOptions.Converters.Add(new FolderUpdateJsonConverter());
            _jsonOptions.Converters.Add(new ForgotPasswordConfirmRequestJsonConverter());
            _jsonOptions.Converters.Add(new ForgotPasswordRequestJsonConverter());
            _jsonOptions.Converters.Add(new ForgotPasswordResponseJsonConverter());
            _jsonOptions.Converters.Add(new GitHubBackupConfigCreateJsonConverter());
            _jsonOptions.Converters.Add(new GitHubBackupConfigResponseJsonConverter());
            _jsonOptions.Converters.Add(new GitHubBackupConfigUpdateJsonConverter());
            _jsonOptions.Converters.Add(new GitHubBackupLogResponseJsonConverter());
            _jsonOptions.Converters.Add(new GitHubBackupStatusJsonConverter());
            _jsonOptions.Converters.Add(new GitHubBackupTriggerResponseJsonConverter());
            _jsonOptions.Converters.Add(new GitHubTestConnectionResponseJsonConverter());
            _jsonOptions.Converters.Add(new GroupBriefJsonConverter());
            _jsonOptions.Converters.Add(new GroupCreateJsonConverter());
            _jsonOptions.Converters.Add(new GroupDetailResponseJsonConverter());
            _jsonOptions.Converters.Add(new GroupResponseJsonConverter());
            _jsonOptions.Converters.Add(new GroupUpdateJsonConverter());
            _jsonOptions.Converters.Add(new HAEntityJsonConverter());
            _jsonOptions.Converters.Add(new HASensorEntityJsonConverter());
            _jsonOptions.Converters.Add(new HATestConnectionRequestJsonConverter());
            _jsonOptions.Converters.Add(new HATestConnectionResponseJsonConverter());
            _jsonOptions.Converters.Add(new HMSErrorResponseJsonConverter());
            _jsonOptions.Converters.Add(new HTTPValidationErrorJsonConverter());
            _jsonOptions.Converters.Add(new HeartbeatRequestJsonConverter());
            _jsonOptions.Converters.Add(new HeartbeatResponseJsonConverter());
            _jsonOptions.Converters.Add(new ImportResponseJsonConverter());
            _jsonOptions.Converters.Add(new KProfileJsonConverter());
            _jsonOptions.Converters.Add(new KProfileCreateJsonConverter());
            _jsonOptions.Converters.Add(new KProfileDeleteJsonConverter());
            _jsonOptions.Converters.Add(new KProfileNoteJsonConverter());
            _jsonOptions.Converters.Add(new KProfileNoteResponseJsonConverter());
            _jsonOptions.Converters.Add(new KProfilesResponseJsonConverter());
            _jsonOptions.Converters.Add(new LDAPProvisionRequestJsonConverter());
            _jsonOptions.Converters.Add(new LDAPSearchResultResponseJsonConverter());
            _jsonOptions.Converters.Add(new LabelRequestJsonConverter());
            _jsonOptions.Converters.Add(new LatestFirmwareInfoJsonConverter());
            _jsonOptions.Converters.Add(new LinkSpoolRequestJsonConverter());
            _jsonOptions.Converters.Add(new LinkTagRequestJsonConverter());
            _jsonOptions.Converters.Add(new LinkedFolderExportJsonConverter());
            _jsonOptions.Converters.Add(new LocalPresetCreateJsonConverter());
            _jsonOptions.Converters.Add(new LocalPresetDetailJsonConverter());
            _jsonOptions.Converters.Add(new LocalPresetResponseJsonConverter());
            _jsonOptions.Converters.Add(new LocalPresetUpdateJsonConverter());
            _jsonOptions.Converters.Add(new LocalPresetsResponseJsonConverter());
            _jsonOptions.Converters.Add(new LocationInnerJsonConverter());
            _jsonOptions.Converters.Add(new LogEntryJsonConverter());
            _jsonOptions.Converters.Add(new LogFindingJsonConverter());
            _jsonOptions.Converters.Add(new LoginRequestJsonConverter());
            _jsonOptions.Converters.Add(new LoginResponseJsonConverter());
            _jsonOptions.Converters.Add(new LogsResponseJsonConverter());
            _jsonOptions.Converters.Add(new MaintenanceHistoryResponseJsonConverter());
            _jsonOptions.Converters.Add(new MaintenanceStatusJsonConverter());
            _jsonOptions.Converters.Add(new MaintenanceTypeCreateJsonConverter());
            _jsonOptions.Converters.Add(new MaintenanceTypeResponseJsonConverter());
            _jsonOptions.Converters.Add(new MaintenanceTypeUpdateJsonConverter());
            _jsonOptions.Converters.Add(new MakerWorldImportRequestJsonConverter());
            _jsonOptions.Converters.Add(new MakerWorldImportResponseJsonConverter());
            _jsonOptions.Converters.Add(new MakerWorldRecentImportJsonConverter());
            _jsonOptions.Converters.Add(new MakerWorldResolveRequestJsonConverter());
            _jsonOptions.Converters.Add(new MakerWorldResolvedModelJsonConverter());
            _jsonOptions.Converters.Add(new MakerWorldStatusJsonConverter());
            _jsonOptions.Converters.Add(new NormalizedFilamentJsonConverter());
            _jsonOptions.Converters.Add(new NormalizedVendorRefJsonConverter());
            _jsonOptions.Converters.Add(new NotificationLogResponseJsonConverter());
            _jsonOptions.Converters.Add(new NotificationLogStatsJsonConverter());
            _jsonOptions.Converters.Add(new NotificationProviderCreateJsonConverter());
            _jsonOptions.Converters.Add(new NotificationProviderResponseJsonConverter());
            _jsonOptions.Converters.Add(new NotificationProviderUpdateJsonConverter());
            _jsonOptions.Converters.Add(new NotificationTemplateResponseJsonConverter());
            _jsonOptions.Converters.Add(new NotificationTemplateUpdateJsonConverter());
            _jsonOptions.Converters.Add(new NotificationTestRequestJsonConverter());
            _jsonOptions.Converters.Add(new NotificationTestResponseJsonConverter());
            _jsonOptions.Converters.Add(new NozzleInfoResponseJsonConverter());
            _jsonOptions.Converters.Add(new NozzleRackSlotJsonConverter());
            _jsonOptions.Converters.Add(new OIDCAuthorizeResponseJsonConverter());
            _jsonOptions.Converters.Add(new OIDCExchangeRequestJsonConverter());
            _jsonOptions.Converters.Add(new OIDCLinkResponseJsonConverter());
            _jsonOptions.Converters.Add(new OIDCProviderCreateJsonConverter());
            _jsonOptions.Converters.Add(new OIDCProviderResponseJsonConverter());
            _jsonOptions.Converters.Add(new OIDCProviderUpdateJsonConverter());
            _jsonOptions.Converters.Add(new OrcaAuthFinishRequestJsonConverter());
            _jsonOptions.Converters.Add(new OrcaAuthPasswordRequestJsonConverter());
            _jsonOptions.Converters.Add(new OrcaAuthStartRequestJsonConverter());
            _jsonOptions.Converters.Add(new OrcaAuthStartResponseJsonConverter());
            _jsonOptions.Converters.Add(new OrcaAuthStatusResponseJsonConverter());
            _jsonOptions.Converters.Add(new OrcaProfileDetailJsonConverter());
            _jsonOptions.Converters.Add(new OrcaProfileListResponseJsonConverter());
            _jsonOptions.Converters.Add(new OrcaProfileMetaJsonConverter());
            _jsonOptions.Converters.Add(new PendingUploadResponseJsonConverter());
            _jsonOptions.Converters.Add(new PerformMaintenanceRequestJsonConverter());
            _jsonOptions.Converters.Add(new PermissionCategoryJsonConverter());
            _jsonOptions.Converters.Add(new PermissionInfoJsonConverter());
            _jsonOptions.Converters.Add(new PermissionsListResponseJsonConverter());
            _jsonOptions.Converters.Add(new PlateDetectionROIJsonConverter());
            _jsonOptions.Converters.Add(new PresetRefJsonConverter());
            _jsonOptions.Converters.Add(new PrintBatchResponseJsonConverter());
            _jsonOptions.Converters.Add(new PrintLogEntrySchemaJsonConverter());
            _jsonOptions.Converters.Add(new PrintLogResponseJsonConverter());
            _jsonOptions.Converters.Add(new PrintOptionsResponseJsonConverter());
            _jsonOptions.Converters.Add(new PrintQueueBulkUpdateJsonConverter());
            _jsonOptions.Converters.Add(new PrintQueueBulkUpdateResponseJsonConverter());
            _jsonOptions.Converters.Add(new PrintQueueItemCreateJsonConverter());
            _jsonOptions.Converters.Add(new PrintQueueItemResponseJsonConverter());
            _jsonOptions.Converters.Add(new PrintQueueItemUpdateJsonConverter());
            _jsonOptions.Converters.Add(new PrintQueueReorderJsonConverter());
            _jsonOptions.Converters.Add(new PrintQueueReorderItemJsonConverter());
            _jsonOptions.Converters.Add(new PrinterCreateJsonConverter());
            _jsonOptions.Converters.Add(new PrinterDiagnosticResultJsonConverter());
            _jsonOptions.Converters.Add(new PrinterMaintenanceOverviewJsonConverter());
            _jsonOptions.Converters.Add(new PrinterMaintenanceResponseJsonConverter());
            _jsonOptions.Converters.Add(new PrinterMaintenanceUpdateJsonConverter());
            _jsonOptions.Converters.Add(new PrinterResponseJsonConverter());
            _jsonOptions.Converters.Add(new PrinterStatusJsonConverter());
            _jsonOptions.Converters.Add(new PrinterStatusResponseJsonConverter());
            _jsonOptions.Converters.Add(new PrinterUpdateJsonConverter());
            _jsonOptions.Converters.Add(new ProjectChildPreviewJsonConverter());
            _jsonOptions.Converters.Add(new ProjectCreateJsonConverter());
            _jsonOptions.Converters.Add(new ProjectImportJsonConverter());
            _jsonOptions.Converters.Add(new ProjectListResponseJsonConverter());
            _jsonOptions.Converters.Add(new ProjectResponseJsonConverter());
            _jsonOptions.Converters.Add(new ProjectStatsJsonConverter());
            _jsonOptions.Converters.Add(new ProjectUpdateJsonConverter());
            _jsonOptions.Converters.Add(new ProviderTypeOutputJsonConverter());
            _jsonOptions.Converters.Add(new ProviderTypeOutputNullableJsonConverter());
            _jsonOptions.Converters.Add(new PurgePreviewResponseJsonConverter());
            _jsonOptions.Converters.Add(new PurgeRequestJsonConverter());
            _jsonOptions.Converters.Add(new PurgeResponseJsonConverter());
            _jsonOptions.Converters.Add(new QueueAddRequestJsonConverter());
            _jsonOptions.Converters.Add(new QueueAddResponseJsonConverter());
            _jsonOptions.Converters.Add(new QueueStatusResponseJsonConverter());
            _jsonOptions.Converters.Add(new RESTTestConnectionRequestJsonConverter());
            _jsonOptions.Converters.Add(new RESTTestConnectionResponseJsonConverter());
            _jsonOptions.Converters.Add(new ReprintRequestJsonConverter());
            _jsonOptions.Converters.Add(new ResetPasswordRequestJsonConverter());
            _jsonOptions.Converters.Add(new ResetPasswordResponseJsonConverter());
            _jsonOptions.Converters.Add(new SMTPSettingsJsonConverter());
            _jsonOptions.Converters.Add(new ScaleReadingRequestJsonConverter());
            _jsonOptions.Converters.Add(new ScanResultJsonConverter());
            _jsonOptions.Converters.Add(new ScheduleTypeJsonConverter());
            _jsonOptions.Converters.Add(new ScheduleTypeNullableJsonConverter());
            _jsonOptions.Converters.Add(new SetCalibrationFactorRequestJsonConverter());
            _jsonOptions.Converters.Add(new SetTareRequestJsonConverter());
            _jsonOptions.Converters.Add(new SetupRequestJsonConverter());
            _jsonOptions.Converters.Add(new SetupResponseJsonConverter());
            _jsonOptions.Converters.Add(new ShoppingListItemCreateJsonConverter());
            _jsonOptions.Converters.Add(new ShoppingListItemResponseJsonConverter());
            _jsonOptions.Converters.Add(new ShoppingListItemStatusUpdateJsonConverter());
            _jsonOptions.Converters.Add(new SkippedSpoolJsonConverter());
            _jsonOptions.Converters.Add(new SliceBundleSpecJsonConverter());
            _jsonOptions.Converters.Add(new SliceRequestJsonConverter());
            _jsonOptions.Converters.Add(new SlicerSettingJsonConverter());
            _jsonOptions.Converters.Add(new SlicerSettingCreateJsonConverter());
            _jsonOptions.Converters.Add(new SlicerSettingDeleteResponseJsonConverter());
            _jsonOptions.Converters.Add(new SlicerSettingUpdateJsonConverter());
            _jsonOptions.Converters.Add(new SlicerSettingsResponseJsonConverter());
            _jsonOptions.Converters.Add(new SmartPlugControlJsonConverter());
            _jsonOptions.Converters.Add(new SmartPlugCreateJsonConverter());
            _jsonOptions.Converters.Add(new SmartPlugEnergyJsonConverter());
            _jsonOptions.Converters.Add(new SmartPlugResponseJsonConverter());
            _jsonOptions.Converters.Add(new SmartPlugStatusJsonConverter());
            _jsonOptions.Converters.Add(new SmartPlugTestConnectionJsonConverter());
            _jsonOptions.Converters.Add(new SmartPlugUpdateJsonConverter());
            _jsonOptions.Converters.Add(new SpoolAssignmentCreateJsonConverter());
            _jsonOptions.Converters.Add(new SpoolAssignmentResponseJsonConverter());
            _jsonOptions.Converters.Add(new SpoolBulkCreateJsonConverter());
            _jsonOptions.Converters.Add(new SpoolCreateJsonConverter());
            _jsonOptions.Converters.Add(new SpoolKProfileBaseJsonConverter());
            _jsonOptions.Converters.Add(new SpoolKProfileResponseJsonConverter());
            _jsonOptions.Converters.Add(new SpoolResponseJsonConverter());
            _jsonOptions.Converters.Add(new SpoolSlotAssignmentRequestJsonConverter());
            _jsonOptions.Converters.Add(new SpoolTagLinkRequestJsonConverter());
            _jsonOptions.Converters.Add(new SpoolUpdateJsonConverter());
            _jsonOptions.Converters.Add(new SpoolUsageHistoryResponseJsonConverter());
            _jsonOptions.Converters.Add(new SpoolWeightUpdateJsonConverter());
            _jsonOptions.Converters.Add(new SpoolmanFilamentPatchJsonConverter());
            _jsonOptions.Converters.Add(new SpoolmanInventoryBulkCreateJsonConverter());
            _jsonOptions.Converters.Add(new SpoolmanInventoryCreateJsonConverter());
            _jsonOptions.Converters.Add(new SpoolmanInventoryUpdateJsonConverter());
            _jsonOptions.Converters.Add(new SpoolmanSlotAssignmentEnrichedJsonConverter());
            _jsonOptions.Converters.Add(new SpoolmanStatusJsonConverter());
            _jsonOptions.Converters.Add(new StartLoggingResponseJsonConverter());
            _jsonOptions.Converters.Add(new StopLoggingResponseJsonConverter());
            _jsonOptions.Converters.Add(new SubnetScanRequestJsonConverter());
            _jsonOptions.Converters.Add(new SubnetScanStatusJsonConverter());
            _jsonOptions.Converters.Add(new SyncResultJsonConverter());
            _jsonOptions.Converters.Add(new SystemCommandRequestJsonConverter());
            _jsonOptions.Converters.Add(new SystemCommandResultRequestJsonConverter());
            _jsonOptions.Converters.Add(new SystemConfigRequestJsonConverter());
            _jsonOptions.Converters.Add(new TOTPDisableRequestJsonConverter());
            _jsonOptions.Converters.Add(new TOTPEnableRequestJsonConverter());
            _jsonOptions.Converters.Add(new TOTPEnableResponseJsonConverter());
            _jsonOptions.Converters.Add(new TOTPSetupRequestJsonConverter());
            _jsonOptions.Converters.Add(new TOTPSetupResponseJsonConverter());
            _jsonOptions.Converters.Add(new TagRemovedRequestJsonConverter());
            _jsonOptions.Converters.Add(new TagScannedRequestJsonConverter());
            _jsonOptions.Converters.Add(new TailscaleStatusResponseJsonConverter());
            _jsonOptions.Converters.Add(new TasmotaScanRequestJsonConverter());
            _jsonOptions.Converters.Add(new TasmotaScanStatusJsonConverter());
            _jsonOptions.Converters.Add(new TemplatePreviewRequestJsonConverter());
            _jsonOptions.Converters.Add(new TemplatePreviewResponseJsonConverter());
            _jsonOptions.Converters.Add(new TestConnectionRequestJsonConverter());
            _jsonOptions.Converters.Add(new TestSMTPRequestJsonConverter());
            _jsonOptions.Converters.Add(new TestSMTPResponseJsonConverter());
            _jsonOptions.Converters.Add(new TimelineEventJsonConverter());
            _jsonOptions.Converters.Add(new TrashFileJsonConverter());
            _jsonOptions.Converters.Add(new TrashListResponseJsonConverter());
            _jsonOptions.Converters.Add(new TrashSettingsJsonConverter());
            _jsonOptions.Converters.Add(new TwoFAStatusResponseJsonConverter());
            _jsonOptions.Converters.Add(new TwoFAVerifyRequestJsonConverter());
            _jsonOptions.Converters.Add(new TwoFAVerifyResponseJsonConverter());
            _jsonOptions.Converters.Add(new UnifiedPresetJsonConverter());
            _jsonOptions.Converters.Add(new UnifiedPresetsBySlotJsonConverter());
            _jsonOptions.Converters.Add(new UnifiedPresetsResponseJsonConverter());
            _jsonOptions.Converters.Add(new UnlinkedSpoolJsonConverter());
            _jsonOptions.Converters.Add(new UpdateSpoolWeightRequestJsonConverter());
            _jsonOptions.Converters.Add(new UpdateStatusRequestJsonConverter());
            _jsonOptions.Converters.Add(new UserBriefJsonConverter());
            _jsonOptions.Converters.Add(new UserCreateJsonConverter());
            _jsonOptions.Converters.Add(new UserEmailPreferenceResponseJsonConverter());
            _jsonOptions.Converters.Add(new UserEmailPreferenceUpdateJsonConverter());
            _jsonOptions.Converters.Add(new UserResponseJsonConverter());
            _jsonOptions.Converters.Add(new UserUpdateJsonConverter());
            _jsonOptions.Converters.Add(new VPDiagnosticResultJsonConverter());
            _jsonOptions.Converters.Add(new ValidationErrorJsonConverter());
            _jsonOptions.Converters.Add(new VirtualPrinterCreateJsonConverter());
            _jsonOptions.Converters.Add(new VirtualPrinterUpdateJsonConverter());
            _jsonOptions.Converters.Add(new WriteTagRequestJsonConverter());
            _jsonOptions.Converters.Add(new WriteTagResultRequestJsonConverter());
            _jsonOptions.Converters.Add(new ZipExtractErrorJsonConverter());
            _jsonOptions.Converters.Add(new ZipExtractResponseJsonConverter());
            _jsonOptions.Converters.Add(new ZipExtractResultJsonConverter());
            JsonSerializerOptionsProvider jsonSerializerOptionsProvider = new(_jsonOptions);
            _services.AddSingleton(jsonSerializerOptionsProvider);
            _services.AddSingleton<IApiFactory, ApiFactory>();
            _services.AddSingleton<AmsHistoryApiEvents>();
            _services.AddSingleton<ApiKeysApiEvents>();
            _services.AddSingleton<ArchivesApiEvents>();
            _services.AddSingleton<ArchivesPurgeApiEvents>();
            _services.AddSingleton<AuthenticationApiEvents>();
            _services.AddSingleton<BackgroundDispatchApiEvents>();
            _services.AddSingleton<BugReportApiEvents>();
            _services.AddSingleton<CameraApiEvents>();
            _services.AddSingleton<Class2faApiEvents>();
            _services.AddSingleton<CloudApiEvents>();
            _services.AddSingleton<DefaultApiEvents>();
            _services.AddSingleton<DiscoveryApiEvents>();
            _services.AddSingleton<ExternalLinksApiEvents>();
            _services.AddSingleton<FilamentCatalogApiEvents>();
            _services.AddSingleton<FirmwareApiEvents>();
            _services.AddSingleton<GithubBackupApiEvents>();
            _services.AddSingleton<GroupsApiEvents>();
            _services.AddSingleton<InventoryApiEvents>();
            _services.AddSingleton<KprofilesApiEvents>();
            _services.AddSingleton<LabelsApiEvents>();
            _services.AddSingleton<LibraryApiEvents>();
            _services.AddSingleton<LibraryTrashApiEvents>();
            _services.AddSingleton<LocalBackupApiEvents>();
            _services.AddSingleton<LocalPresetsApiEvents>();
            _services.AddSingleton<MaintenanceApiEvents>();
            _services.AddSingleton<MakerworldApiEvents>();
            _services.AddSingleton<MetricsApiEvents>();
            _services.AddSingleton<NotificationTemplatesApiEvents>();
            _services.AddSingleton<NotificationsApiEvents>();
            _services.AddSingleton<ObicoApiEvents>();
            _services.AddSingleton<OidcApiEvents>();
            _services.AddSingleton<OrcaCloudApiEvents>();
            _services.AddSingleton<PendingUploadsApiEvents>();
            _services.AddSingleton<PrintLogApiEvents>();
            _services.AddSingleton<PrintersApiEvents>();
            _services.AddSingleton<ProjectsApiEvents>();
            _services.AddSingleton<QueueApiEvents>();
            _services.AddSingleton<SettingsApiEvents>();
            _services.AddSingleton<SliceJobsApiEvents>();
            _services.AddSingleton<SlicerPresetsApiEvents>();
            _services.AddSingleton<SmartPlugsApiEvents>();
            _services.AddSingleton<SpoolbuddyApiEvents>();
            _services.AddSingleton<SpoolmanApiEvents>();
            _services.AddSingleton<SpoolmanInventoryApiEvents>();
            _services.AddSingleton<SupportApiEvents>();
            _services.AddSingleton<SystemApiEvents>();
            _services.AddSingleton<UpdatesApiEvents>();
            _services.AddSingleton<UserNotificationsApiEvents>();
            _services.AddSingleton<UsersApiEvents>();
            _services.AddSingleton<VirtualPrintersApiEvents>();
            _services.AddSingleton<WebhookApiEvents>();
        }

        /// <summary>
        /// Configures the HttpClients.
        /// </summary>
        /// <param name="client"></param>
        /// <param name="builder"></param>
        /// <returns></returns>
        public HostConfiguration AddApiHttpClients
        (
            Action<HttpClient>? client = null, Action<IHttpClientBuilder>? builder = null)
        {
            if (client == null)
                client = c => c.BaseAddress = new Uri(ClientUtils.BASE_ADDRESS);

            List<IHttpClientBuilder> builders = new List<IHttpClientBuilder>();

            builders.Add(_services.AddHttpClient<IAmsHistoryApi, AmsHistoryApi>("Bambuddy.Api.Api.IAmsHistoryApi", client));
            builders.Add(_services.AddHttpClient<IApiKeysApi, ApiKeysApi>("Bambuddy.Api.Api.IApiKeysApi", client));
            builders.Add(_services.AddHttpClient<IArchivesApi, ArchivesApi>("Bambuddy.Api.Api.IArchivesApi", client));
            builders.Add(_services.AddHttpClient<IArchivesPurgeApi, ArchivesPurgeApi>("Bambuddy.Api.Api.IArchivesPurgeApi", client));
            builders.Add(_services.AddHttpClient<IAuthenticationApi, AuthenticationApi>("Bambuddy.Api.Api.IAuthenticationApi", client));
            builders.Add(_services.AddHttpClient<IBackgroundDispatchApi, BackgroundDispatchApi>("Bambuddy.Api.Api.IBackgroundDispatchApi", client));
            builders.Add(_services.AddHttpClient<IBugReportApi, BugReportApi>("Bambuddy.Api.Api.IBugReportApi", client));
            builders.Add(_services.AddHttpClient<ICameraApi, CameraApi>("Bambuddy.Api.Api.ICameraApi", client));
            builders.Add(_services.AddHttpClient<IClass2faApi, Class2faApi>("Bambuddy.Api.Api.IClass2faApi", client));
            builders.Add(_services.AddHttpClient<ICloudApi, CloudApi>("Bambuddy.Api.Api.ICloudApi", client));
            builders.Add(_services.AddHttpClient<IDefaultApi, DefaultApi>("Bambuddy.Api.Api.IDefaultApi", client));
            builders.Add(_services.AddHttpClient<IDiscoveryApi, DiscoveryApi>("Bambuddy.Api.Api.IDiscoveryApi", client));
            builders.Add(_services.AddHttpClient<IExternalLinksApi, ExternalLinksApi>("Bambuddy.Api.Api.IExternalLinksApi", client));
            builders.Add(_services.AddHttpClient<IFilamentCatalogApi, FilamentCatalogApi>("Bambuddy.Api.Api.IFilamentCatalogApi", client));
            builders.Add(_services.AddHttpClient<IFirmwareApi, FirmwareApi>("Bambuddy.Api.Api.IFirmwareApi", client));
            builders.Add(_services.AddHttpClient<IGithubBackupApi, GithubBackupApi>("Bambuddy.Api.Api.IGithubBackupApi", client));
            builders.Add(_services.AddHttpClient<IGroupsApi, GroupsApi>("Bambuddy.Api.Api.IGroupsApi", client));
            builders.Add(_services.AddHttpClient<IInventoryApi, InventoryApi>("Bambuddy.Api.Api.IInventoryApi", client));
            builders.Add(_services.AddHttpClient<IKprofilesApi, KprofilesApi>("Bambuddy.Api.Api.IKprofilesApi", client));
            builders.Add(_services.AddHttpClient<ILabelsApi, LabelsApi>("Bambuddy.Api.Api.ILabelsApi", client));
            builders.Add(_services.AddHttpClient<ILibraryApi, LibraryApi>("Bambuddy.Api.Api.ILibraryApi", client));
            builders.Add(_services.AddHttpClient<ILibraryTrashApi, LibraryTrashApi>("Bambuddy.Api.Api.ILibraryTrashApi", client));
            builders.Add(_services.AddHttpClient<ILocalBackupApi, LocalBackupApi>("Bambuddy.Api.Api.ILocalBackupApi", client));
            builders.Add(_services.AddHttpClient<ILocalPresetsApi, LocalPresetsApi>("Bambuddy.Api.Api.ILocalPresetsApi", client));
            builders.Add(_services.AddHttpClient<IMaintenanceApi, MaintenanceApi>("Bambuddy.Api.Api.IMaintenanceApi", client));
            builders.Add(_services.AddHttpClient<IMakerworldApi, MakerworldApi>("Bambuddy.Api.Api.IMakerworldApi", client));
            builders.Add(_services.AddHttpClient<IMetricsApi, MetricsApi>("Bambuddy.Api.Api.IMetricsApi", client));
            builders.Add(_services.AddHttpClient<INotificationTemplatesApi, NotificationTemplatesApi>("Bambuddy.Api.Api.INotificationTemplatesApi", client));
            builders.Add(_services.AddHttpClient<INotificationsApi, NotificationsApi>("Bambuddy.Api.Api.INotificationsApi", client));
            builders.Add(_services.AddHttpClient<IObicoApi, ObicoApi>("Bambuddy.Api.Api.IObicoApi", client));
            builders.Add(_services.AddHttpClient<IOidcApi, OidcApi>("Bambuddy.Api.Api.IOidcApi", client));
            builders.Add(_services.AddHttpClient<IOrcaCloudApi, OrcaCloudApi>("Bambuddy.Api.Api.IOrcaCloudApi", client));
            builders.Add(_services.AddHttpClient<IPendingUploadsApi, PendingUploadsApi>("Bambuddy.Api.Api.IPendingUploadsApi", client));
            builders.Add(_services.AddHttpClient<IPrintLogApi, PrintLogApi>("Bambuddy.Api.Api.IPrintLogApi", client));
            builders.Add(_services.AddHttpClient<IPrintersApi, PrintersApi>("Bambuddy.Api.Api.IPrintersApi", client));
            builders.Add(_services.AddHttpClient<IProjectsApi, ProjectsApi>("Bambuddy.Api.Api.IProjectsApi", client));
            builders.Add(_services.AddHttpClient<IQueueApi, QueueApi>("Bambuddy.Api.Api.IQueueApi", client));
            builders.Add(_services.AddHttpClient<ISettingsApi, SettingsApi>("Bambuddy.Api.Api.ISettingsApi", client));
            builders.Add(_services.AddHttpClient<ISliceJobsApi, SliceJobsApi>("Bambuddy.Api.Api.ISliceJobsApi", client));
            builders.Add(_services.AddHttpClient<ISlicerPresetsApi, SlicerPresetsApi>("Bambuddy.Api.Api.ISlicerPresetsApi", client));
            builders.Add(_services.AddHttpClient<ISmartPlugsApi, SmartPlugsApi>("Bambuddy.Api.Api.ISmartPlugsApi", client));
            builders.Add(_services.AddHttpClient<ISpoolbuddyApi, SpoolbuddyApi>("Bambuddy.Api.Api.ISpoolbuddyApi", client));
            builders.Add(_services.AddHttpClient<ISpoolmanApi, SpoolmanApi>("Bambuddy.Api.Api.ISpoolmanApi", client));
            builders.Add(_services.AddHttpClient<ISpoolmanInventoryApi, SpoolmanInventoryApi>("Bambuddy.Api.Api.ISpoolmanInventoryApi", client));
            builders.Add(_services.AddHttpClient<ISupportApi, SupportApi>("Bambuddy.Api.Api.ISupportApi", client));
            builders.Add(_services.AddHttpClient<ISystemApi, SystemApi>("Bambuddy.Api.Api.ISystemApi", client));
            builders.Add(_services.AddHttpClient<IUpdatesApi, UpdatesApi>("Bambuddy.Api.Api.IUpdatesApi", client));
            builders.Add(_services.AddHttpClient<IUserNotificationsApi, UserNotificationsApi>("Bambuddy.Api.Api.IUserNotificationsApi", client));
            builders.Add(_services.AddHttpClient<IUsersApi, UsersApi>("Bambuddy.Api.Api.IUsersApi", client));
            builders.Add(_services.AddHttpClient<IVirtualPrintersApi, VirtualPrintersApi>("Bambuddy.Api.Api.IVirtualPrintersApi", client));
            builders.Add(_services.AddHttpClient<IWebhookApi, WebhookApi>("Bambuddy.Api.Api.IWebhookApi", client));
            
            if (builder != null)
                foreach (IHttpClientBuilder instance in builders)
                    builder(instance);

            HttpClientsAdded = true;

            return this;
        }

        /// <summary>
        /// Configures the JsonSerializerSettings
        /// </summary>
        /// <param name="options"></param>
        /// <returns></returns>
        public HostConfiguration ConfigureJsonOptions(Action<JsonSerializerOptions> options)
        {
            options(_jsonOptions);

            return this;
        }

        /// <summary>
        /// Adds tokens to your IServiceCollection
        /// </summary>
        /// <typeparam name="TTokenBase"></typeparam>
        /// <param name="token"></param>
        /// <returns></returns>
        public HostConfiguration AddTokens<TTokenBase>(TTokenBase token) where TTokenBase : TokenBase
        {
            return AddTokens(new TTokenBase[]{ token });
        }

        /// <summary>
        /// Adds tokens to your IServiceCollection
        /// </summary>
        /// <typeparam name="TTokenBase"></typeparam>
        /// <param name="tokens"></param>
        /// <returns></returns>
        public HostConfiguration AddTokens<TTokenBase>(IEnumerable<TTokenBase> tokens) where TTokenBase : TokenBase
        {
            TokenContainer<TTokenBase> container = new TokenContainer<TTokenBase>(tokens);
            _services.AddSingleton(services => container);

            return this;
        }

        /// <summary>
        /// Adds a token provider to your IServiceCollection
        /// </summary>
        /// <typeparam name="TTokenProvider"></typeparam>
        /// <typeparam name="TTokenBase"></typeparam>
        /// <returns></returns>
        public HostConfiguration UseProvider<TTokenProvider, TTokenBase>() 
            where TTokenProvider : TokenProvider<TTokenBase>
            where TTokenBase : TokenBase
        {
            _services.AddSingleton<TTokenProvider>();
            _services.AddSingleton<TokenProvider<TTokenBase>>(services => services.GetRequiredService<TTokenProvider>());

            return this;
        }
    }
}
