/*
 * Bambuddy
 *
 * Archive and manage Bambu Lab 3MF files
 *
 * The version of the OpenAPI document: 0.2.4.5
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Bambuddy.Api.Model;
using Bambuddy.Api.Client;
using System.Reflection;

namespace Bambuddy.Api.Test.Model
{
    /// <summary>
    ///  Class for testing AMSUnit
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AMSUnitTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AMSUnit
        //private AMSUnit instance;

        public AMSUnitTests()
        {
            // TODO uncomment below to create an instance of AMSUnit
            //instance = new AMSUnit();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AMSUnit
        /// </summary>
        [Fact]
        public void AMSUnitInstanceTest()
        {
            // TODO uncomment below to test "IsType" AMSUnit
            //Assert.IsType<AMSUnit>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Humidity'
        /// </summary>
        [Fact]
        public void HumidityTest()
        {
            // TODO unit test for the property 'Humidity'
        }

        /// <summary>
        /// Test the property 'Temp'
        /// </summary>
        [Fact]
        public void TempTest()
        {
            // TODO unit test for the property 'Temp'
        }

        /// <summary>
        /// Test the property 'IsAmsHt'
        /// </summary>
        [Fact]
        public void IsAmsHtTest()
        {
            // TODO unit test for the property 'IsAmsHt'
        }

        /// <summary>
        /// Test the property 'Tray'
        /// </summary>
        [Fact]
        public void TrayTest()
        {
            // TODO unit test for the property 'Tray'
        }

        /// <summary>
        /// Test the property 'SerialNumber'
        /// </summary>
        [Fact]
        public void SerialNumberTest()
        {
            // TODO unit test for the property 'SerialNumber'
        }

        /// <summary>
        /// Test the property 'SwVer'
        /// </summary>
        [Fact]
        public void SwVerTest()
        {
            // TODO unit test for the property 'SwVer'
        }

        /// <summary>
        /// Test the property 'DryTime'
        /// </summary>
        [Fact]
        public void DryTimeTest()
        {
            // TODO unit test for the property 'DryTime'
        }

        /// <summary>
        /// Test the property 'DryStatus'
        /// </summary>
        [Fact]
        public void DryStatusTest()
        {
            // TODO unit test for the property 'DryStatus'
        }

        /// <summary>
        /// Test the property 'DrySubStatus'
        /// </summary>
        [Fact]
        public void DrySubStatusTest()
        {
            // TODO unit test for the property 'DrySubStatus'
        }

        /// <summary>
        /// Test the property 'DrySfReason'
        /// </summary>
        [Fact]
        public void DrySfReasonTest()
        {
            // TODO unit test for the property 'DrySfReason'
        }

        /// <summary>
        /// Test the property 'ModuleType'
        /// </summary>
        [Fact]
        public void ModuleTypeTest()
        {
            // TODO unit test for the property 'ModuleType'
        }
    }
}
