/*
 * Bambuddy
 *
 * Archive and manage Bambu Lab 3MF files
 *
 * The version of the OpenAPI document: 0.2.4.5
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Bambuddy.Api.Model;
using Bambuddy.Api.Client;
using System.Reflection;

namespace Bambuddy.Api.Test.Model
{
    /// <summary>
    ///  Class for testing DiscoveryStatus
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DiscoveryStatusTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DiscoveryStatus
        //private DiscoveryStatus instance;

        public DiscoveryStatusTests()
        {
            // TODO uncomment below to create an instance of DiscoveryStatus
            //instance = new DiscoveryStatus();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DiscoveryStatus
        /// </summary>
        [Fact]
        public void DiscoveryStatusInstanceTest()
        {
            // TODO uncomment below to test "IsType" DiscoveryStatus
            //Assert.IsType<DiscoveryStatus>(instance);
        }

        /// <summary>
        /// Test the property 'Running'
        /// </summary>
        [Fact]
        public void RunningTest()
        {
            // TODO unit test for the property 'Running'
        }
    }
}
