/*
 * Bambuddy
 *
 * Archive and manage Bambu Lab 3MF files
 *
 * The version of the OpenAPI document: 0.2.4.5
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Bambuddy.Api.Model;
using Bambuddy.Api.Client;
using System.Reflection;

namespace Bambuddy.Api.Test.Model
{
    /// <summary>
    ///  Class for testing FileUploadResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class FileUploadResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for FileUploadResponse
        //private FileUploadResponse instance;

        public FileUploadResponseTests()
        {
            // TODO uncomment below to create an instance of FileUploadResponse
            //instance = new FileUploadResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of FileUploadResponse
        /// </summary>
        [Fact]
        public void FileUploadResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" FileUploadResponse
            //Assert.IsType<FileUploadResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Filename'
        /// </summary>
        [Fact]
        public void FilenameTest()
        {
            // TODO unit test for the property 'Filename'
        }

        /// <summary>
        /// Test the property 'FileType'
        /// </summary>
        [Fact]
        public void FileTypeTest()
        {
            // TODO unit test for the property 'FileType'
        }

        /// <summary>
        /// Test the property 'FileSize'
        /// </summary>
        [Fact]
        public void FileSizeTest()
        {
            // TODO unit test for the property 'FileSize'
        }

        /// <summary>
        /// Test the property 'ThumbnailPath'
        /// </summary>
        [Fact]
        public void ThumbnailPathTest()
        {
            // TODO unit test for the property 'ThumbnailPath'
        }

        /// <summary>
        /// Test the property 'DuplicateOf'
        /// </summary>
        [Fact]
        public void DuplicateOfTest()
        {
            // TODO unit test for the property 'DuplicateOf'
        }

        /// <summary>
        /// Test the property 'Metadata'
        /// </summary>
        [Fact]
        public void MetadataTest()
        {
            // TODO unit test for the property 'Metadata'
        }
    }
}
