/*
 * Bambuddy
 *
 * Archive and manage Bambu Lab 3MF files
 *
 * The version of the OpenAPI document: 0.2.4.5
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Bambuddy.Api.Model;
using Bambuddy.Api.Client;
using System.Reflection;

namespace Bambuddy.Api.Test.Model
{
    /// <summary>
    ///  Class for testing FirmwareUploadPrepareResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class FirmwareUploadPrepareResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for FirmwareUploadPrepareResponse
        //private FirmwareUploadPrepareResponse instance;

        public FirmwareUploadPrepareResponseTests()
        {
            // TODO uncomment below to create an instance of FirmwareUploadPrepareResponse
            //instance = new FirmwareUploadPrepareResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of FirmwareUploadPrepareResponse
        /// </summary>
        [Fact]
        public void FirmwareUploadPrepareResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" FirmwareUploadPrepareResponse
            //Assert.IsType<FirmwareUploadPrepareResponse>(instance);
        }

        /// <summary>
        /// Test the property 'CanProceed'
        /// </summary>
        [Fact]
        public void CanProceedTest()
        {
            // TODO unit test for the property 'CanProceed'
        }

        /// <summary>
        /// Test the property 'SdCardPresent'
        /// </summary>
        [Fact]
        public void SdCardPresentTest()
        {
            // TODO unit test for the property 'SdCardPresent'
        }

        /// <summary>
        /// Test the property 'SpaceSufficient'
        /// </summary>
        [Fact]
        public void SpaceSufficientTest()
        {
            // TODO unit test for the property 'SpaceSufficient'
        }

        /// <summary>
        /// Test the property 'UpdateAvailable'
        /// </summary>
        [Fact]
        public void UpdateAvailableTest()
        {
            // TODO unit test for the property 'UpdateAvailable'
        }

        /// <summary>
        /// Test the property 'SdCardFreeSpace'
        /// </summary>
        [Fact]
        public void SdCardFreeSpaceTest()
        {
            // TODO unit test for the property 'SdCardFreeSpace'
        }

        /// <summary>
        /// Test the property 'FirmwareSize'
        /// </summary>
        [Fact]
        public void FirmwareSizeTest()
        {
            // TODO unit test for the property 'FirmwareSize'
        }

        /// <summary>
        /// Test the property 'CurrentVersion'
        /// </summary>
        [Fact]
        public void CurrentVersionTest()
        {
            // TODO unit test for the property 'CurrentVersion'
        }

        /// <summary>
        /// Test the property 'LatestVersion'
        /// </summary>
        [Fact]
        public void LatestVersionTest()
        {
            // TODO unit test for the property 'LatestVersion'
        }

        /// <summary>
        /// Test the property 'TargetVersion'
        /// </summary>
        [Fact]
        public void TargetVersionTest()
        {
            // TODO unit test for the property 'TargetVersion'
        }

        /// <summary>
        /// Test the property 'FirmwareFilename'
        /// </summary>
        [Fact]
        public void FirmwareFilenameTest()
        {
            // TODO unit test for the property 'FirmwareFilename'
        }

        /// <summary>
        /// Test the property 'Errors'
        /// </summary>
        [Fact]
        public void ErrorsTest()
        {
            // TODO unit test for the property 'Errors'
        }
    }
}
