/*
 * Bambuddy
 *
 * Archive and manage Bambu Lab 3MF files
 *
 * The version of the OpenAPI document: 0.2.4.5
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Bambuddy.Api.Model;
using Bambuddy.Api.Client;
using System.Reflection;

namespace Bambuddy.Api.Test.Model
{
    /// <summary>
    ///  Class for testing KProfileCreate
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class KProfileCreateTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for KProfileCreate
        //private KProfileCreate instance;

        public KProfileCreateTests()
        {
            // TODO uncomment below to create an instance of KProfileCreate
            //instance = new KProfileCreate();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of KProfileCreate
        /// </summary>
        [Fact]
        public void KProfileCreateInstanceTest()
        {
            // TODO uncomment below to test "IsType" KProfileCreate
            //Assert.IsType<KProfileCreate>(instance);
        }

        /// <summary>
        /// Test the property 'NozzleId'
        /// </summary>
        [Fact]
        public void NozzleIdTest()
        {
            // TODO unit test for the property 'NozzleId'
        }

        /// <summary>
        /// Test the property 'NozzleDiameter'
        /// </summary>
        [Fact]
        public void NozzleDiameterTest()
        {
            // TODO unit test for the property 'NozzleDiameter'
        }

        /// <summary>
        /// Test the property 'FilamentId'
        /// </summary>
        [Fact]
        public void FilamentIdTest()
        {
            // TODO unit test for the property 'FilamentId'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'KValue'
        /// </summary>
        [Fact]
        public void KValueTest()
        {
            // TODO unit test for the property 'KValue'
        }

        /// <summary>
        /// Test the property 'SlotId'
        /// </summary>
        [Fact]
        public void SlotIdTest()
        {
            // TODO unit test for the property 'SlotId'
        }

        /// <summary>
        /// Test the property 'ExtruderId'
        /// </summary>
        [Fact]
        public void ExtruderIdTest()
        {
            // TODO unit test for the property 'ExtruderId'
        }

        /// <summary>
        /// Test the property 'NCoef'
        /// </summary>
        [Fact]
        public void NCoefTest()
        {
            // TODO unit test for the property 'NCoef'
        }

        /// <summary>
        /// Test the property 'AmsId'
        /// </summary>
        [Fact]
        public void AmsIdTest()
        {
            // TODO unit test for the property 'AmsId'
        }

        /// <summary>
        /// Test the property 'TrayId'
        /// </summary>
        [Fact]
        public void TrayIdTest()
        {
            // TODO unit test for the property 'TrayId'
        }

        /// <summary>
        /// Test the property 'SettingId'
        /// </summary>
        [Fact]
        public void SettingIdTest()
        {
            // TODO unit test for the property 'SettingId'
        }
    }
}
