/*
 * Bambuddy
 *
 * Archive and manage Bambu Lab 3MF files
 *
 * The version of the OpenAPI document: 0.2.4.5
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Bambuddy.Api.Model;
using Bambuddy.Api.Client;
using System.Reflection;

namespace Bambuddy.Api.Test.Model
{
    /// <summary>
    ///  Class for testing OIDCLinkResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OIDCLinkResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OIDCLinkResponse
        //private OIDCLinkResponse instance;

        public OIDCLinkResponseTests()
        {
            // TODO uncomment below to create an instance of OIDCLinkResponse
            //instance = new OIDCLinkResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OIDCLinkResponse
        /// </summary>
        [Fact]
        public void OIDCLinkResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" OIDCLinkResponse
            //Assert.IsType<OIDCLinkResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'ProviderId'
        /// </summary>
        [Fact]
        public void ProviderIdTest()
        {
            // TODO unit test for the property 'ProviderId'
        }

        /// <summary>
        /// Test the property 'ProviderName'
        /// </summary>
        [Fact]
        public void ProviderNameTest()
        {
            // TODO unit test for the property 'ProviderName'
        }

        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Fact]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }

        /// <summary>
        /// Test the property 'ProviderEmail'
        /// </summary>
        [Fact]
        public void ProviderEmailTest()
        {
            // TODO unit test for the property 'ProviderEmail'
        }
    }
}
