/*
 * Bambuddy
 *
 * Archive and manage Bambu Lab 3MF files
 *
 * The version of the OpenAPI document: 0.2.4.5
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Bambuddy.Api.Model;
using Bambuddy.Api.Client;
using System.Reflection;

namespace Bambuddy.Api.Test.Model
{
    /// <summary>
    ///  Class for testing PrinterMaintenanceResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PrinterMaintenanceResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PrinterMaintenanceResponse
        //private PrinterMaintenanceResponse instance;

        public PrinterMaintenanceResponseTests()
        {
            // TODO uncomment below to create an instance of PrinterMaintenanceResponse
            //instance = new PrinterMaintenanceResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PrinterMaintenanceResponse
        /// </summary>
        [Fact]
        public void PrinterMaintenanceResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" PrinterMaintenanceResponse
            //Assert.IsType<PrinterMaintenanceResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'PrinterId'
        /// </summary>
        [Fact]
        public void PrinterIdTest()
        {
            // TODO unit test for the property 'PrinterId'
        }

        /// <summary>
        /// Test the property 'MaintenanceTypeId'
        /// </summary>
        [Fact]
        public void MaintenanceTypeIdTest()
        {
            // TODO unit test for the property 'MaintenanceTypeId'
        }

        /// <summary>
        /// Test the property 'MaintenanceType'
        /// </summary>
        [Fact]
        public void MaintenanceTypeTest()
        {
            // TODO unit test for the property 'MaintenanceType'
        }

        /// <summary>
        /// Test the property 'Enabled'
        /// </summary>
        [Fact]
        public void EnabledTest()
        {
            // TODO unit test for the property 'Enabled'
        }

        /// <summary>
        /// Test the property 'LastPerformedHours'
        /// </summary>
        [Fact]
        public void LastPerformedHoursTest()
        {
            // TODO unit test for the property 'LastPerformedHours'
        }

        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Fact]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }

        /// <summary>
        /// Test the property 'UpdatedAt'
        /// </summary>
        [Fact]
        public void UpdatedAtTest()
        {
            // TODO unit test for the property 'UpdatedAt'
        }

        /// <summary>
        /// Test the property 'CustomIntervalHours'
        /// </summary>
        [Fact]
        public void CustomIntervalHoursTest()
        {
            // TODO unit test for the property 'CustomIntervalHours'
        }

        /// <summary>
        /// Test the property 'LastPerformedAt'
        /// </summary>
        [Fact]
        public void LastPerformedAtTest()
        {
            // TODO unit test for the property 'LastPerformedAt'
        }
    }
}
