/*
 * Bambuddy
 *
 * Archive and manage Bambu Lab 3MF files
 *
 * The version of the OpenAPI document: 0.2.4.5
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Bambuddy.Api.Model;
using Bambuddy.Api.Client;
using System.Reflection;

namespace Bambuddy.Api.Test.Model
{
    /// <summary>
    ///  Class for testing PrintLogEntrySchema
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PrintLogEntrySchemaTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PrintLogEntrySchema
        //private PrintLogEntrySchema instance;

        public PrintLogEntrySchemaTests()
        {
            // TODO uncomment below to create an instance of PrintLogEntrySchema
            //instance = new PrintLogEntrySchema();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PrintLogEntrySchema
        /// </summary>
        [Fact]
        public void PrintLogEntrySchemaInstanceTest()
        {
            // TODO uncomment below to test "IsType" PrintLogEntrySchema
            //Assert.IsType<PrintLogEntrySchema>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Fact]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }

        /// <summary>
        /// Test the property 'ArchiveId'
        /// </summary>
        [Fact]
        public void ArchiveIdTest()
        {
            // TODO unit test for the property 'ArchiveId'
        }

        /// <summary>
        /// Test the property 'PrintName'
        /// </summary>
        [Fact]
        public void PrintNameTest()
        {
            // TODO unit test for the property 'PrintName'
        }

        /// <summary>
        /// Test the property 'PrinterName'
        /// </summary>
        [Fact]
        public void PrinterNameTest()
        {
            // TODO unit test for the property 'PrinterName'
        }

        /// <summary>
        /// Test the property 'PrinterId'
        /// </summary>
        [Fact]
        public void PrinterIdTest()
        {
            // TODO unit test for the property 'PrinterId'
        }

        /// <summary>
        /// Test the property 'StartedAt'
        /// </summary>
        [Fact]
        public void StartedAtTest()
        {
            // TODO unit test for the property 'StartedAt'
        }

        /// <summary>
        /// Test the property 'CompletedAt'
        /// </summary>
        [Fact]
        public void CompletedAtTest()
        {
            // TODO unit test for the property 'CompletedAt'
        }

        /// <summary>
        /// Test the property 'DurationSeconds'
        /// </summary>
        [Fact]
        public void DurationSecondsTest()
        {
            // TODO unit test for the property 'DurationSeconds'
        }

        /// <summary>
        /// Test the property 'FilamentType'
        /// </summary>
        [Fact]
        public void FilamentTypeTest()
        {
            // TODO unit test for the property 'FilamentType'
        }

        /// <summary>
        /// Test the property 'FilamentColor'
        /// </summary>
        [Fact]
        public void FilamentColorTest()
        {
            // TODO unit test for the property 'FilamentColor'
        }

        /// <summary>
        /// Test the property 'FilamentUsedGrams'
        /// </summary>
        [Fact]
        public void FilamentUsedGramsTest()
        {
            // TODO unit test for the property 'FilamentUsedGrams'
        }

        /// <summary>
        /// Test the property 'Cost'
        /// </summary>
        [Fact]
        public void CostTest()
        {
            // TODO unit test for the property 'Cost'
        }

        /// <summary>
        /// Test the property 'EnergyKwh'
        /// </summary>
        [Fact]
        public void EnergyKwhTest()
        {
            // TODO unit test for the property 'EnergyKwh'
        }

        /// <summary>
        /// Test the property 'EnergyCost'
        /// </summary>
        [Fact]
        public void EnergyCostTest()
        {
            // TODO unit test for the property 'EnergyCost'
        }

        /// <summary>
        /// Test the property 'FailureReason'
        /// </summary>
        [Fact]
        public void FailureReasonTest()
        {
            // TODO unit test for the property 'FailureReason'
        }

        /// <summary>
        /// Test the property 'ThumbnailPath'
        /// </summary>
        [Fact]
        public void ThumbnailPathTest()
        {
            // TODO unit test for the property 'ThumbnailPath'
        }

        /// <summary>
        /// Test the property 'CreatedById'
        /// </summary>
        [Fact]
        public void CreatedByIdTest()
        {
            // TODO unit test for the property 'CreatedById'
        }

        /// <summary>
        /// Test the property 'CreatedByUsername'
        /// </summary>
        [Fact]
        public void CreatedByUsernameTest()
        {
            // TODO unit test for the property 'CreatedByUsername'
        }
    }
}
