/*
 * Bambuddy
 *
 * Archive and manage Bambu Lab 3MF files
 *
 * The version of the OpenAPI document: 0.2.4.5
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Bambuddy.Api.Model;
using Bambuddy.Api.Client;
using System.Reflection;

namespace Bambuddy.Api.Test.Model
{
    /// <summary>
    ///  Class for testing ProjectResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ProjectResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ProjectResponse
        //private ProjectResponse instance;

        public ProjectResponseTests()
        {
            // TODO uncomment below to create an instance of ProjectResponse
            //instance = new ProjectResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ProjectResponse
        /// </summary>
        [Fact]
        public void ProjectResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" ProjectResponse
            //Assert.IsType<ProjectResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Fact]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }

        /// <summary>
        /// Test the property 'UpdatedAt'
        /// </summary>
        [Fact]
        public void UpdatedAtTest()
        {
            // TODO unit test for the property 'UpdatedAt'
        }

        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }

        /// <summary>
        /// Test the property 'Color'
        /// </summary>
        [Fact]
        public void ColorTest()
        {
            // TODO unit test for the property 'Color'
        }

        /// <summary>
        /// Test the property 'TargetCount'
        /// </summary>
        [Fact]
        public void TargetCountTest()
        {
            // TODO unit test for the property 'TargetCount'
        }

        /// <summary>
        /// Test the property 'TargetPartsCount'
        /// </summary>
        [Fact]
        public void TargetPartsCountTest()
        {
            // TODO unit test for the property 'TargetPartsCount'
        }

        /// <summary>
        /// Test the property 'Notes'
        /// </summary>
        [Fact]
        public void NotesTest()
        {
            // TODO unit test for the property 'Notes'
        }

        /// <summary>
        /// Test the property 'Attachments'
        /// </summary>
        [Fact]
        public void AttachmentsTest()
        {
            // TODO unit test for the property 'Attachments'
        }

        /// <summary>
        /// Test the property 'Tags'
        /// </summary>
        [Fact]
        public void TagsTest()
        {
            // TODO unit test for the property 'Tags'
        }

        /// <summary>
        /// Test the property 'DueDate'
        /// </summary>
        [Fact]
        public void DueDateTest()
        {
            // TODO unit test for the property 'DueDate'
        }

        /// <summary>
        /// Test the property 'Priority'
        /// </summary>
        [Fact]
        public void PriorityTest()
        {
            // TODO unit test for the property 'Priority'
        }

        /// <summary>
        /// Test the property 'Budget'
        /// </summary>
        [Fact]
        public void BudgetTest()
        {
            // TODO unit test for the property 'Budget'
        }

        /// <summary>
        /// Test the property 'IsTemplate'
        /// </summary>
        [Fact]
        public void IsTemplateTest()
        {
            // TODO unit test for the property 'IsTemplate'
        }

        /// <summary>
        /// Test the property 'TemplateSourceId'
        /// </summary>
        [Fact]
        public void TemplateSourceIdTest()
        {
            // TODO unit test for the property 'TemplateSourceId'
        }

        /// <summary>
        /// Test the property 'ParentId'
        /// </summary>
        [Fact]
        public void ParentIdTest()
        {
            // TODO unit test for the property 'ParentId'
        }

        /// <summary>
        /// Test the property 'ParentName'
        /// </summary>
        [Fact]
        public void ParentNameTest()
        {
            // TODO unit test for the property 'ParentName'
        }

        /// <summary>
        /// Test the property 'Children'
        /// </summary>
        [Fact]
        public void ChildrenTest()
        {
            // TODO unit test for the property 'Children'
        }

        /// <summary>
        /// Test the property 'Stats'
        /// </summary>
        [Fact]
        public void StatsTest()
        {
            // TODO unit test for the property 'Stats'
        }

        /// <summary>
        /// Test the property 'Url'
        /// </summary>
        [Fact]
        public void UrlTest()
        {
            // TODO unit test for the property 'Url'
        }

        /// <summary>
        /// Test the property 'CoverImageFilename'
        /// </summary>
        [Fact]
        public void CoverImageFilenameTest()
        {
            // TODO unit test for the property 'CoverImageFilename'
        }
    }
}
