/*
 * Bambuddy
 *
 * Archive and manage Bambu Lab 3MF files
 *
 * The version of the OpenAPI document: 0.2.4.5
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Bambuddy.Api.Model;
using Bambuddy.Api.Client;
using System.Reflection;

namespace Bambuddy.Api.Test.Model
{
    /// <summary>
    ///  Class for testing SlicerSettingsResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SlicerSettingsResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SlicerSettingsResponse
        //private SlicerSettingsResponse instance;

        public SlicerSettingsResponseTests()
        {
            // TODO uncomment below to create an instance of SlicerSettingsResponse
            //instance = new SlicerSettingsResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SlicerSettingsResponse
        /// </summary>
        [Fact]
        public void SlicerSettingsResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" SlicerSettingsResponse
            //Assert.IsType<SlicerSettingsResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Filament'
        /// </summary>
        [Fact]
        public void FilamentTest()
        {
            // TODO unit test for the property 'Filament'
        }

        /// <summary>
        /// Test the property 'Printer'
        /// </summary>
        [Fact]
        public void PrinterTest()
        {
            // TODO unit test for the property 'Printer'
        }

        /// <summary>
        /// Test the property 'Process'
        /// </summary>
        [Fact]
        public void ProcessTest()
        {
            // TODO unit test for the property 'Process'
        }
    }
}
