/*
 * Bambuddy
 *
 * Archive and manage Bambu Lab 3MF files
 *
 * The version of the OpenAPI document: 0.2.4.5
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Bambuddy.Api.Model;
using Bambuddy.Api.Client;
using System.Reflection;

namespace Bambuddy.Api.Test.Model
{
    /// <summary>
    ///  Class for testing SmartPlugResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SmartPlugResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SmartPlugResponse
        //private SmartPlugResponse instance;

        public SmartPlugResponseTests()
        {
            // TODO uncomment below to create an instance of SmartPlugResponse
            //instance = new SmartPlugResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SmartPlugResponse
        /// </summary>
        [Fact]
        public void SmartPlugResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" SmartPlugResponse
            //Assert.IsType<SmartPlugResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Fact]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }

        /// <summary>
        /// Test the property 'UpdatedAt'
        /// </summary>
        [Fact]
        public void UpdatedAtTest()
        {
            // TODO unit test for the property 'UpdatedAt'
        }

        /// <summary>
        /// Test the property 'PlugType'
        /// </summary>
        [Fact]
        public void PlugTypeTest()
        {
            // TODO unit test for the property 'PlugType'
        }

        /// <summary>
        /// Test the property 'IpAddress'
        /// </summary>
        [Fact]
        public void IpAddressTest()
        {
            // TODO unit test for the property 'IpAddress'
        }

        /// <summary>
        /// Test the property 'Username'
        /// </summary>
        [Fact]
        public void UsernameTest()
        {
            // TODO unit test for the property 'Username'
        }

        /// <summary>
        /// Test the property 'Password'
        /// </summary>
        [Fact]
        public void PasswordTest()
        {
            // TODO unit test for the property 'Password'
        }

        /// <summary>
        /// Test the property 'HaEntityId'
        /// </summary>
        [Fact]
        public void HaEntityIdTest()
        {
            // TODO unit test for the property 'HaEntityId'
        }

        /// <summary>
        /// Test the property 'HaPowerEntity'
        /// </summary>
        [Fact]
        public void HaPowerEntityTest()
        {
            // TODO unit test for the property 'HaPowerEntity'
        }

        /// <summary>
        /// Test the property 'HaEnergyTodayEntity'
        /// </summary>
        [Fact]
        public void HaEnergyTodayEntityTest()
        {
            // TODO unit test for the property 'HaEnergyTodayEntity'
        }

        /// <summary>
        /// Test the property 'HaEnergyTotalEntity'
        /// </summary>
        [Fact]
        public void HaEnergyTotalEntityTest()
        {
            // TODO unit test for the property 'HaEnergyTotalEntity'
        }

        /// <summary>
        /// Test the property 'MqttTopic'
        /// </summary>
        [Fact]
        public void MqttTopicTest()
        {
            // TODO unit test for the property 'MqttTopic'
        }

        /// <summary>
        /// Test the property 'MqttPowerTopic'
        /// </summary>
        [Fact]
        public void MqttPowerTopicTest()
        {
            // TODO unit test for the property 'MqttPowerTopic'
        }

        /// <summary>
        /// Test the property 'MqttPowerPath'
        /// </summary>
        [Fact]
        public void MqttPowerPathTest()
        {
            // TODO unit test for the property 'MqttPowerPath'
        }

        /// <summary>
        /// Test the property 'MqttPowerMultiplier'
        /// </summary>
        [Fact]
        public void MqttPowerMultiplierTest()
        {
            // TODO unit test for the property 'MqttPowerMultiplier'
        }

        /// <summary>
        /// Test the property 'MqttEnergyTopic'
        /// </summary>
        [Fact]
        public void MqttEnergyTopicTest()
        {
            // TODO unit test for the property 'MqttEnergyTopic'
        }

        /// <summary>
        /// Test the property 'MqttEnergyPath'
        /// </summary>
        [Fact]
        public void MqttEnergyPathTest()
        {
            // TODO unit test for the property 'MqttEnergyPath'
        }

        /// <summary>
        /// Test the property 'MqttEnergyMultiplier'
        /// </summary>
        [Fact]
        public void MqttEnergyMultiplierTest()
        {
            // TODO unit test for the property 'MqttEnergyMultiplier'
        }

        /// <summary>
        /// Test the property 'MqttStateTopic'
        /// </summary>
        [Fact]
        public void MqttStateTopicTest()
        {
            // TODO unit test for the property 'MqttStateTopic'
        }

        /// <summary>
        /// Test the property 'MqttStatePath'
        /// </summary>
        [Fact]
        public void MqttStatePathTest()
        {
            // TODO unit test for the property 'MqttStatePath'
        }

        /// <summary>
        /// Test the property 'MqttStateOnValue'
        /// </summary>
        [Fact]
        public void MqttStateOnValueTest()
        {
            // TODO unit test for the property 'MqttStateOnValue'
        }

        /// <summary>
        /// Test the property 'MqttMultiplier'
        /// </summary>
        [Fact]
        public void MqttMultiplierTest()
        {
            // TODO unit test for the property 'MqttMultiplier'
        }

        /// <summary>
        /// Test the property 'RestOnUrl'
        /// </summary>
        [Fact]
        public void RestOnUrlTest()
        {
            // TODO unit test for the property 'RestOnUrl'
        }

        /// <summary>
        /// Test the property 'RestOnBody'
        /// </summary>
        [Fact]
        public void RestOnBodyTest()
        {
            // TODO unit test for the property 'RestOnBody'
        }

        /// <summary>
        /// Test the property 'RestOffUrl'
        /// </summary>
        [Fact]
        public void RestOffUrlTest()
        {
            // TODO unit test for the property 'RestOffUrl'
        }

        /// <summary>
        /// Test the property 'RestOffBody'
        /// </summary>
        [Fact]
        public void RestOffBodyTest()
        {
            // TODO unit test for the property 'RestOffBody'
        }

        /// <summary>
        /// Test the property 'RestMethod'
        /// </summary>
        [Fact]
        public void RestMethodTest()
        {
            // TODO unit test for the property 'RestMethod'
        }

        /// <summary>
        /// Test the property 'RestHeaders'
        /// </summary>
        [Fact]
        public void RestHeadersTest()
        {
            // TODO unit test for the property 'RestHeaders'
        }

        /// <summary>
        /// Test the property 'RestStatusUrl'
        /// </summary>
        [Fact]
        public void RestStatusUrlTest()
        {
            // TODO unit test for the property 'RestStatusUrl'
        }

        /// <summary>
        /// Test the property 'RestStatusPath'
        /// </summary>
        [Fact]
        public void RestStatusPathTest()
        {
            // TODO unit test for the property 'RestStatusPath'
        }

        /// <summary>
        /// Test the property 'RestStatusOnValue'
        /// </summary>
        [Fact]
        public void RestStatusOnValueTest()
        {
            // TODO unit test for the property 'RestStatusOnValue'
        }

        /// <summary>
        /// Test the property 'RestPowerUrl'
        /// </summary>
        [Fact]
        public void RestPowerUrlTest()
        {
            // TODO unit test for the property 'RestPowerUrl'
        }

        /// <summary>
        /// Test the property 'RestPowerPath'
        /// </summary>
        [Fact]
        public void RestPowerPathTest()
        {
            // TODO unit test for the property 'RestPowerPath'
        }

        /// <summary>
        /// Test the property 'RestPowerMultiplier'
        /// </summary>
        [Fact]
        public void RestPowerMultiplierTest()
        {
            // TODO unit test for the property 'RestPowerMultiplier'
        }

        /// <summary>
        /// Test the property 'RestEnergyUrl'
        /// </summary>
        [Fact]
        public void RestEnergyUrlTest()
        {
            // TODO unit test for the property 'RestEnergyUrl'
        }

        /// <summary>
        /// Test the property 'RestEnergyPath'
        /// </summary>
        [Fact]
        public void RestEnergyPathTest()
        {
            // TODO unit test for the property 'RestEnergyPath'
        }

        /// <summary>
        /// Test the property 'RestEnergyMultiplier'
        /// </summary>
        [Fact]
        public void RestEnergyMultiplierTest()
        {
            // TODO unit test for the property 'RestEnergyMultiplier'
        }

        /// <summary>
        /// Test the property 'PrinterId'
        /// </summary>
        [Fact]
        public void PrinterIdTest()
        {
            // TODO unit test for the property 'PrinterId'
        }

        /// <summary>
        /// Test the property 'Enabled'
        /// </summary>
        [Fact]
        public void EnabledTest()
        {
            // TODO unit test for the property 'Enabled'
        }

        /// <summary>
        /// Test the property 'AutoOn'
        /// </summary>
        [Fact]
        public void AutoOnTest()
        {
            // TODO unit test for the property 'AutoOn'
        }

        /// <summary>
        /// Test the property 'AutoOff'
        /// </summary>
        [Fact]
        public void AutoOffTest()
        {
            // TODO unit test for the property 'AutoOff'
        }

        /// <summary>
        /// Test the property 'AutoOffPersistent'
        /// </summary>
        [Fact]
        public void AutoOffPersistentTest()
        {
            // TODO unit test for the property 'AutoOffPersistent'
        }

        /// <summary>
        /// Test the property 'OffDelayMode'
        /// </summary>
        [Fact]
        public void OffDelayModeTest()
        {
            // TODO unit test for the property 'OffDelayMode'
        }

        /// <summary>
        /// Test the property 'OffDelayMinutes'
        /// </summary>
        [Fact]
        public void OffDelayMinutesTest()
        {
            // TODO unit test for the property 'OffDelayMinutes'
        }

        /// <summary>
        /// Test the property 'OffTempThreshold'
        /// </summary>
        [Fact]
        public void OffTempThresholdTest()
        {
            // TODO unit test for the property 'OffTempThreshold'
        }

        /// <summary>
        /// Test the property 'AutoOffAfterDrying'
        /// </summary>
        [Fact]
        public void AutoOffAfterDryingTest()
        {
            // TODO unit test for the property 'AutoOffAfterDrying'
        }

        /// <summary>
        /// Test the property 'OffDelayAfterDryingMinutes'
        /// </summary>
        [Fact]
        public void OffDelayAfterDryingMinutesTest()
        {
            // TODO unit test for the property 'OffDelayAfterDryingMinutes'
        }

        /// <summary>
        /// Test the property 'PowerAlertEnabled'
        /// </summary>
        [Fact]
        public void PowerAlertEnabledTest()
        {
            // TODO unit test for the property 'PowerAlertEnabled'
        }

        /// <summary>
        /// Test the property 'PowerAlertHigh'
        /// </summary>
        [Fact]
        public void PowerAlertHighTest()
        {
            // TODO unit test for the property 'PowerAlertHigh'
        }

        /// <summary>
        /// Test the property 'PowerAlertLow'
        /// </summary>
        [Fact]
        public void PowerAlertLowTest()
        {
            // TODO unit test for the property 'PowerAlertLow'
        }

        /// <summary>
        /// Test the property 'ScheduleEnabled'
        /// </summary>
        [Fact]
        public void ScheduleEnabledTest()
        {
            // TODO unit test for the property 'ScheduleEnabled'
        }

        /// <summary>
        /// Test the property 'ScheduleOnTime'
        /// </summary>
        [Fact]
        public void ScheduleOnTimeTest()
        {
            // TODO unit test for the property 'ScheduleOnTime'
        }

        /// <summary>
        /// Test the property 'ScheduleOffTime'
        /// </summary>
        [Fact]
        public void ScheduleOffTimeTest()
        {
            // TODO unit test for the property 'ScheduleOffTime'
        }

        /// <summary>
        /// Test the property 'ShowInSwitchbar'
        /// </summary>
        [Fact]
        public void ShowInSwitchbarTest()
        {
            // TODO unit test for the property 'ShowInSwitchbar'
        }

        /// <summary>
        /// Test the property 'ShowOnPrinterCard'
        /// </summary>
        [Fact]
        public void ShowOnPrinterCardTest()
        {
            // TODO unit test for the property 'ShowOnPrinterCard'
        }

        /// <summary>
        /// Test the property 'LastState'
        /// </summary>
        [Fact]
        public void LastStateTest()
        {
            // TODO unit test for the property 'LastState'
        }

        /// <summary>
        /// Test the property 'LastChecked'
        /// </summary>
        [Fact]
        public void LastCheckedTest()
        {
            // TODO unit test for the property 'LastChecked'
        }

        /// <summary>
        /// Test the property 'AutoOffExecuted'
        /// </summary>
        [Fact]
        public void AutoOffExecutedTest()
        {
            // TODO unit test for the property 'AutoOffExecuted'
        }

        /// <summary>
        /// Test the property 'PowerAlertLastTriggered'
        /// </summary>
        [Fact]
        public void PowerAlertLastTriggeredTest()
        {
            // TODO unit test for the property 'PowerAlertLastTriggered'
        }
    }
}
