/*
 * Bambuddy
 *
 * Archive and manage Bambu Lab 3MF files
 *
 * The version of the OpenAPI document: 0.2.4.5
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Bambuddy.Api.Model;
using Bambuddy.Api.Client;
using System.Reflection;

namespace Bambuddy.Api.Test.Model
{
    /// <summary>
    ///  Class for testing SMTPSettings
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SMTPSettingsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SMTPSettings
        //private SMTPSettings instance;

        public SMTPSettingsTests()
        {
            // TODO uncomment below to create an instance of SMTPSettings
            //instance = new SMTPSettings();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SMTPSettings
        /// </summary>
        [Fact]
        public void SMTPSettingsInstanceTest()
        {
            // TODO uncomment below to test "IsType" SMTPSettings
            //Assert.IsType<SMTPSettings>(instance);
        }

        /// <summary>
        /// Test the property 'SmtpHost'
        /// </summary>
        [Fact]
        public void SmtpHostTest()
        {
            // TODO unit test for the property 'SmtpHost'
        }

        /// <summary>
        /// Test the property 'SmtpPort'
        /// </summary>
        [Fact]
        public void SmtpPortTest()
        {
            // TODO unit test for the property 'SmtpPort'
        }

        /// <summary>
        /// Test the property 'SmtpFromEmail'
        /// </summary>
        [Fact]
        public void SmtpFromEmailTest()
        {
            // TODO unit test for the property 'SmtpFromEmail'
        }

        /// <summary>
        /// Test the property 'SmtpUsername'
        /// </summary>
        [Fact]
        public void SmtpUsernameTest()
        {
            // TODO unit test for the property 'SmtpUsername'
        }

        /// <summary>
        /// Test the property 'SmtpPassword'
        /// </summary>
        [Fact]
        public void SmtpPasswordTest()
        {
            // TODO unit test for the property 'SmtpPassword'
        }

        /// <summary>
        /// Test the property 'SmtpSecurity'
        /// </summary>
        [Fact]
        public void SmtpSecurityTest()
        {
            // TODO unit test for the property 'SmtpSecurity'
        }

        /// <summary>
        /// Test the property 'SmtpAuthEnabled'
        /// </summary>
        [Fact]
        public void SmtpAuthEnabledTest()
        {
            // TODO unit test for the property 'SmtpAuthEnabled'
        }

        /// <summary>
        /// Test the property 'SmtpFromName'
        /// </summary>
        [Fact]
        public void SmtpFromNameTest()
        {
            // TODO unit test for the property 'SmtpFromName'
        }

        /// <summary>
        /// Test the property 'SmtpUseTls'
        /// </summary>
        [Fact]
        public void SmtpUseTlsTest()
        {
            // TODO unit test for the property 'SmtpUseTls'
        }
    }
}
