/*
 * Bambuddy
 *
 * Archive and manage Bambu Lab 3MF files
 *
 * The version of the OpenAPI document: 0.2.4.5
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Bambuddy.Api.Model;
using Bambuddy.Api.Client;
using System.Reflection;

namespace Bambuddy.Api.Test.Model
{
    /// <summary>
    ///  Class for testing SubnetScanStatus
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SubnetScanStatusTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SubnetScanStatus
        //private SubnetScanStatus instance;

        public SubnetScanStatusTests()
        {
            // TODO uncomment below to create an instance of SubnetScanStatus
            //instance = new SubnetScanStatus();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SubnetScanStatus
        /// </summary>
        [Fact]
        public void SubnetScanStatusInstanceTest()
        {
            // TODO uncomment below to test "IsType" SubnetScanStatus
            //Assert.IsType<SubnetScanStatus>(instance);
        }

        /// <summary>
        /// Test the property 'Running'
        /// </summary>
        [Fact]
        public void RunningTest()
        {
            // TODO unit test for the property 'Running'
        }

        /// <summary>
        /// Test the property 'Scanned'
        /// </summary>
        [Fact]
        public void ScannedTest()
        {
            // TODO unit test for the property 'Scanned'
        }

        /// <summary>
        /// Test the property 'Total'
        /// </summary>
        [Fact]
        public void TotalTest()
        {
            // TODO unit test for the property 'Total'
        }
    }
}
