/*
 * Bambuddy
 *
 * Archive and manage Bambu Lab 3MF files
 *
 * The version of the OpenAPI document: 0.2.4.5
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Bambuddy.Api.Model;
using Bambuddy.Api.Client;
using System.Reflection;

namespace Bambuddy.Api.Test.Model
{
    /// <summary>
    ///  Class for testing SystemCommandRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SystemCommandRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SystemCommandRequest
        //private SystemCommandRequest instance;

        public SystemCommandRequestTests()
        {
            // TODO uncomment below to create an instance of SystemCommandRequest
            //instance = new SystemCommandRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SystemCommandRequest
        /// </summary>
        [Fact]
        public void SystemCommandRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" SystemCommandRequest
            //Assert.IsType<SystemCommandRequest>(instance);
        }

        /// <summary>
        /// Test the property 'Command'
        /// </summary>
        [Fact]
        public void CommandTest()
        {
            // TODO unit test for the property 'Command'
        }
    }
}
