/*
 * Bambuddy
 *
 * Archive and manage Bambu Lab 3MF files
 *
 * The version of the OpenAPI document: 0.2.4.5
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Bambuddy.Api.Model;
using Bambuddy.Api.Client;
using System.Reflection;

namespace Bambuddy.Api.Test.Model
{
    /// <summary>
    ///  Class for testing TestSMTPRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TestSMTPRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TestSMTPRequest
        //private TestSMTPRequest instance;

        public TestSMTPRequestTests()
        {
            // TODO uncomment below to create an instance of TestSMTPRequest
            //instance = new TestSMTPRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TestSMTPRequest
        /// </summary>
        [Fact]
        public void TestSMTPRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" TestSMTPRequest
            //Assert.IsType<TestSMTPRequest>(instance);
        }

        /// <summary>
        /// Test the property 'TestRecipient'
        /// </summary>
        [Fact]
        public void TestRecipientTest()
        {
            // TODO unit test for the property 'TestRecipient'
        }
    }
}
